### ISSUE TITLE
Move TakeScreenshot from actions to controls

### ISSUE THREAD

**Issue by memiks** [vertigo17/Cerberus#123]
"Take Screenshot" is used to manually verified result of an action.
like where is a button
verify color of text
etc...

This is NOT an action but a verification of a action.
So it need be move from Actions to Controls.

**Comment by vertigo17** [comment]
I agree with memiks.
@cjmachado an action is something that is done on the application that is beeing tested.
Today, when we use the action TakeScreenshot, this is done in order to perform a control, not an action.

**Comment by vertigo17** [comment]
Still need to deprecate the takeScreenshot Action.

**Comment by vertigo17** [comment]
Done.

**Comment by cjmachado** [comment]
@vertigo17 What is the plan for migrating the test cases to accommodate this change?

**Comment by vertigo17** [comment]
You should replace the takescreenshot action by skippaction and add to it the take screenshot control. Or remove the action and add the takescreenshot control on previous action.

**Comment by gmoita** [comment]
Is this still usable or not?
If not, we just have to migrate around 1500 test cases. :(

**Comment by vertigo17** [comment]
Yes deprecated but usable.
We will warm before removing but from now (until we deploy it live) you can progressively remove its usage and stop using it in new testcases.
