### ISSUE TITLE
Test case fails when performing action 'switchToWindow'

### ISSUE THREAD

**Issue by cjmachado** [vertigo17/Cerberus#322]
Action 'switchToWindow' efectively switches to the desired window but it's not possible to return to the main window and execute the next actions. Example test case: Performance Monitor - 5026B (for FR)

**Comment by bcivel** [comment]
@cjmachado Could you please give more information on it? Do you observ it again?

**Comment by cjmachado** [comment]
Yes, the bug still persists. I implemented a test case that reproduces this issue: PAGE THESEUS search - 0001A.

**Comment by bcivel** [comment]
@cjmachado Thanks for the feedback.
The problem on the testcase you did is that you switch correctly to a new window and you perform an action which close this window. After you try to do an action on the main page and it fail.
The subject is that selenium is still focussed on the new window (that is closed) and can't parform any action. You must switch back to the main windows to continue on it.

Please have a look to my proposal bellow. I added a property to get the title of the main title that is calculated by the control verifyTitle (5.1) . Then I added the action (9) to switch back on the main window.

![capture](https://cloud.githubusercontent.com/assets/5376184/5659795/84bd4c72-9718-11e4-8210-926d6a903b43.JPG)

So I remove the tag "Bug" on this issue and I let you to close it if you agree with the proposal.

**Comment by cjmachado** [comment]
I agree with this solution. Thanks for the help.
