### ISSUE TITLE
Execution detail page is not showing correctly link between systems

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#329]
On the Execution detail page, the information related to the link between different systems is not being shown correctly.
On the image below, we can see that nothing is shown on the BuildRev area; it should be "[THESEUS] /", as no build/revision is defined; on BuildRev Linked area it should be displayed "[VC] 2014S1/R67", which is the information on the countryenvlink table.

![systemlink_not correctly shown](https://cloud.githubusercontent.com/assets/5640464/3977931/d2cd13da-2840-11e4-8aeb-bbd99bdd9a25.jpg)

Is the contryenvlink table information kept in historic, so that previous executions show the correct build/revision dependencies at that moment?

About the helping information on the BuildRev Linked area, it says "Build and Revision of the environment of the linked system. The linked systems are defined in the 'Environment Dependancy' section of the environment page."; where is the Environment Dependancy section?

**Comment by vertigo17** [comment]
Yes this is what is expected.
