### ISSUE TITLE
[OPEN A BUG] Evolution : Have some saved template to link on bug trackers

### ISSUE THREAD

**Issue by giyome** [vertigo17/Cerberus#447]
Example for REDMINE :
/issues/new?issue[subject]=%TEST%-%TESTCASE%%20on%20execution%20%EXEID%.&amp;issue[description]=Test%20Case%20Description:%TESTCASEDESC%%0DTest%20case%20ran%20on%20the%20 %EXEDATE%%0DEnvironment:%ENV%%0DCountry:%COUNTRY%%0DBrowser%20used%20:%20%BROWSER%%20-%20Browser%20version%20%BROWSERFULLVERSION%%0D%0DHi,%0DPlease check this execution, we notice that :%0D%0D

Example for MANTIS :
mantis/bug_report_page.php?summary=%TESTCASEDESC%%20on%20execution%20%EXEID%&steps_to_reproduce=http:%2F%2F192.168.134.35%2FCerberus%2FExecutionDetail.jsp%3Fid_tc%3D%EXEID%&additional_info=%TEST%-%TESTCASE%%20on%20execution%20%EXEID%%0DTest%20case%20ran%20on%20the%20 %EXEDATE%%0DEnvironment:%ENV%%0DCountry:%COUNTRY%%0DBrowser%20used%20:%20%BROWSER%%20-%20Browser%20version%20%BROWSERFULLVERSION%%0D%0D

Think to have same for others bugTrackers like Jira, GLPI, or others

**Comment by vertigo17** [comment]
Documentation is clear on how to use Operators to enrich the request.
A lot of dev for few added value.
I close the issue that can be easilly solved by checking the URL already used.
