### ISSUE TITLE
From a step library, let user to know if property has or has not to be redefine

### ISSUE THREAD

**Issue by abourdon** [vertigo17/Cerberus#448]
When using a step from a library, properties are not visible into the Test Case which import them. Reason is to let libraries to define a first value of a property without the need to redefine it from the Test Case which import it.

However, it could exist properties that have to be define into the Test Case which import them. In this case, we cannot know which ones and we have to look from the Test Case library.

It could be great to define an "override" type of a property from a library step that can be either:
- ``final``, then no overriding can be done from the Test Case which import it. In this case, then property cannot be modified and no "pen" icon is shown
- ``optional``, then overriding could be done from the Test Case which import it. In this case, property could be modified but it is not visible from the Test Case and the "pen" icon is shown
- ``needed``, then overriding must be done from the Test Case wich import it. In this case, property has to be modified by the Test Case and its so visible from the Test Case and no "pen" icon is shown.

**Comment by bcivel** [comment]
sloved by @afnogueira : 
If property not defined > Warning mark (With text descriding property not defined)
If property defined in used Step > a pen is displayed (With text to propose to override)
If property overriden in testcase > an arrow mark
