### ISSUE TITLE
Idea : Add an action type "manual action"

### ISSUE THREAD

**Issue by giyome** [vertigo17/Cerberus#456]
If I need do an manual action (no choice) because I need call another team to do something.

In a testcase with at least one manual action, the group of the testcase can be automacly set to "manual" ==> Not runable in automatic way (but may be in a semi-automatic way ? step by step)

**Comment by bcivel** [comment]
Won't implement that way.
issue #263 will allow to put an execution waiting for an event (manual trigger or whatever)
