### ISSUE TITLE
Cannot duplicate test cases to a different test

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#497]
We are not able to load a test case and save it as another test case, if new test is different from the original.

Example: save PAGE VCCRM Article Detail/0001A as PAGE MFCRM Article Detail/0001A

The destination test exists, but test case does not exist.

**Comment by bcivel** [comment]
Development done. I let you to validate it and close it

**Comment by gmoita** [comment]
Shouldn't I check it before being closed?
