### ISSUE TITLE
Allow to keep the current bug id at the test case execution level

### ISSUE THREAD

**Issue by cjmachado** [vertigo17/Cerberus#504]
The user is only allowed to add one bug ID at the test case page. The execution details of that test case will always include the current bug ID, but it will not keep the previous bugs. 
My suggestion to implement this feature is to add a column at the testcaseexecution table and fill it with the current bug id value whenever the test case is executed.

Thanks.

**Comment by vertigo17** [comment]
Carlos, I suggest you close that request as I am not sure it is needed to save that data at execution level.
We may reopen it only if we feel we want to automatise the analysis of previous executions.

**Comment by cjmachado** [comment]
Closed as requested.
