### ISSUE TITLE
Potential Connection leak

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#509]
We are seeing some messages of potential connection leaks on the Cerberus logs.
Most recent one is:
[#|2015-02-04T18:22:18.187+0100|WARNING|sun-appserver2.1|javax.enterprise.resource.resourceadapter|_ThreadID=31;_ThreadName=Timer-6;ConnectionPoolName=AS400_QA_ES;_RequestID=b13ef36e-e4e4-488a-bab4-8114975b6f31;|A potential connection leak detected for connection pool AS400_QA_ES. The stack trace of the thread is provided below : 
com.sun.enterprise.resource.AbstractResourcePool.setResourceStateToBusy(AbstractResourcePool.java:304)
com.sun.enterprise.resource.AbstractResourcePool.getUnenlistedResource(AbstractResourcePool.java:691)
com.sun.enterprise.resource.AbstractResourcePool.internalGetResource(AbstractResourcePool.java:609)
com.sun.enterprise.resource.AbstractResourcePool.getResource(AbstractResourcePool.java:458)
com.sun.enterprise.resource.PoolManagerImpl.getResourceFromPool(PoolManagerImpl.java:248)
com.sun.enterprise.resource.PoolManagerImpl.getResource(PoolManagerImpl.java:176)
com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:327)
com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:189)
com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:165)
com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:158)
com.sun.gjc.spi.base.DataSource.getConnection(DataSource.java:108)
org.cerberus.database.DatabaseSpring.connect(DatabaseSpring.java:72)
org.cerberus.serviceEngine.impl.SQLService.queryDatabase(SQLService.java:166)
org.cerberus.serviceEngine.impl.SQLService.calculateOnDatabase(SQLService.java:80)
org.cerberus.serviceEngine.impl.PropertyService.executeSql(PropertyService.java:398)
org.cerberus.serviceEngine.impl.PropertyService.calculateProperty(PropertyService.java:124)
org.cerberus.serviceEngine.impl.PropertyService.getValue(PropertyService.java:250)
org.cerberus.serviceEngine.impl.ExecutionRunService.executeStep(ExecutionRunService.java:464)
org.cerberus.serviceEngine.impl.ExecutionRunService.executeTestCase(ExecutionRunService.java:304)
sun.reflect.GeneratedMethodAccessor201.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
java.lang.reflect.Method.invoke(Method.java:597)
org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:318)
org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:196)
$Proxy21.executeTestCase(Unknown Source)
org.cerberus.serviceEngine.impl.RunTestCaseService.runTestCase(RunTestCaseService.java:82)
org.cerberus.servlet.publi.RunTestCase.doGet(RunTestCase.java:301)
javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
org.apache.catalina.core.ApplicationFilterChain.servletService(ApplicationFilterChain.java:427)
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:315)
org.apache.catalina.core.StandardContextValve.invokeInternal(StandardContextValve.java:287)
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:218)
org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:648)
org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:593)
com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:94)
com.sun.enterprise.web.PESessionLockingStandardPipeline.invoke(PESessionLockingStandardPipeline.java:98)
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:222)
org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:648)
org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:593)
org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:587)
org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:1093)
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:166)
org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:648)
org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:593)
org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:587)
org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:1093)
org.apache.coyote.tomcat5.CoyoteAdapter.service(CoyoteAdapter.java:291)
com.sun.enterprise.web.connector.grizzly.DefaultProcessorTask.invokeAdapter(DefaultProcessorTask.java:666)
com.sun.enterprise.web.connector.grizzly.DefaultProcessorTask.doProcess(DefaultProcessorTask.java:597)
com.sun.enterprise.web.connector.grizzly.DefaultProcessorTask.process(DefaultProcessorTask.java:872)
com.sun.enterprise.web.connector.grizzly.DefaultReadTask.executeProcessorTask(DefaultReadTask.java:341)
com.sun.enterprise.web.connector.grizzly.DefaultReadTask.doTask(DefaultReadTask.java:263)
com.sun.enterprise.web.connector.grizzly.DefaultReadTask.doTask(DefaultReadTask.java:214)
com.sun.enterprise.web.connector.grizzly.TaskBase.run(TaskBase.java:264)
com.sun.enterprise.web.connector.grizzly.ssl.SSLWorkerThread.run(SSLWorkerThread.java:106)

Monitoring Statistics :
PoolCounters: 
 maxNumConnUsed = 1
 minNumConnUsed = 0
 currNumConnUsed = 0
 maxNumConnFree =  = 3
 minNumConnFree = 0
 currNumConnFree = 2
 numConnCreated = 23
 numConnDestroyed = 22
 numConnFailedValidation = 0
 numConnTimedOut = 0
 numConnAcquired = 9
 numConnReleased = 8
 currConnectionRequestWait = 0
 minConnectionRequestWait = 0
 maxConnectionRequestWait = 1734
 totalConnectionRequestWait = 1734
 numConnSuccessfullyMatched = 0
 numConnNotSuccessfullyMatched = 0
 numPotentialConnLeak = 2|#]

**Comment by bcivel** [comment]
Again, no change on this part since several release.
Does that happen only with this connection pool? How many errors did you get? On which Environment?
To help me to understand, could you send me by email the full log file? Could you send me the settings of your connection pool?
Lets do the next exchanges by email as it become very specific. We'll go back on github after investigation
Thanks for your help.

**Comment by bcivel** [comment]
Did you have the opportunity to check? I do not be able to reproduce it.
Thanks

**Comment by gmoita** [comment]
Not seen again.
