### ISSUE TITLE
CalculateProperty with no value finish the test in PE status

### ISSUE THREAD

**Issue by bcivel** [vertigo17/Cerberus#512]
To Reproduce : 
Use CalculateProperty with no value nor property. An exception occur and the test finish in PE.

Solution : 
If value and propety empty, raise a FA, as the test is badly configured.

**Comment by abourdon** [comment]
And what about an empty value desired property? As empty string for
example. Is the exception is also raised? If yes, we should be  able to
handle this case and not raise a FA.

**Comment by bcivel** [comment]
FA should be raised only if nothing is specified in Object and Property.
I Mean :
> {cerberusAction: {action : 'calculateProperty', object: '', property : ''}}

If you calculate a Property that give you an empty result, it not raise a FA

**Comment by abourdon** [comment]
It sounds good to me ;-)

On Mon, Feb 23, 2015 at 8:52 AM, Benoit CIVEL <notifications@github.com>
wrote:

> FA should be raised only if nothing is specified in Object and Property.
> I Mean :
>
> {cerberusAction: {action : 'calculateProperty', object: '', property : ''}}
>
> If you calculate a Property that give you an empty result, it not raise a
> FA
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vertigo17/Cerberus/issues/512#issuecomment-75501249>.
>



-- 
Aurélien Bourdon

**Comment by bcivel** [comment]
solved by @afnogueira
