### ISSUE TITLE
Multiple test executions improvements

### ISSUE THREAD

**Issue by cjmachado** [vertigo17/Cerberus#513]
In order to fully replace the scripts to run multiple test cases, Cerberus needs 2 other features:
- Allow to specify the number of retries a test case is executed if it's not OK;
- Add a field to report the test case quality / stability percentage. This field should be calculated according to the number of OKs versus number of executions.

Thanks.

**Comment by cjmachado** [comment]
Another missing feature is the possibility to stop the multiple execution.

Thanks.

**Comment by bcivel** [comment]
I Close this issue because it is already developped.
Some new issue related to that feature are followed in other issues number. 
No need to keep it opened.
