### ISSUE TITLE
Users without permissions can create new Tests when duplicating TestCases

### ISSUE THREAD

**Issue by cjmachado** [vertigo17/Cerberus#515]
Steps to reproduce:
1. Login to Cerberus with a user without the TestAdmin role;
2. Go to TestCase page and select a case from the comboboxes;
3. Duplicate the TestCase. Specify a Test that doesn't exist;

A new Test is created along with the duplicated test case. 
My expectations are that Cerberus should prevent from duplicating a TestCase to a inexistent Test if user does not have the appropriate permissions.

**Comment by bcivel** [comment]
Correction just pushed.
@cjmachado could you validate and close if result is as exected

**Comment by cjmachado** [comment]
Sorry for the late reply.
Just tested in QA and when trying to duplicate a test case to a new test, Cerberus returns the following error message: 
"Error : You dont have the user right to create a Test. Please contact your Cerberus Administrator"

Thanks!
