### ISSUE TITLE
Delete execution via Report by tag

### ISSUE THREAD

**Issue by mflorid** [vertigo17/Cerberus#524]
It could be good allow to delete an execution directly on the "Reportingexecutionbytag" page

**Comment by gmoita** [comment]
Delete execution via a Report page?
Don't think it is a good idea.

**Comment by mflorid** [comment]
Maybe just remove it from the tag ?

**Comment by gmoita** [comment]
Like "detaching" it from a specific execution, to meet the reports request?
In that case, I would appreciate it and also the opposite, but not on this page.
For me, it would make more sense to manipulate the Tag information on the ExecutionDetail page (per ID).
Manipulation of this data would only be possible by TestAdmin members, to ensure that no one removes or adds Tag information without knowing the impacts; or, alternatively, creation of an additional security group, to be able to manipulate this.

**Comment by mflorid** [comment]
I am agree with your proposition.

**Comment by bcivel** [comment]
Fixed doing :
- Add a formulary allowing the tag definition/removal from the ExecutionDetail page.
- User Right allowed to do this is RunTest
