### ISSUE TITLE
Not possible to calculate properties from javascript (getFromJS)

### ISSUE THREAD

**Issue by cjmachado** [vertigo17/Cerberus#527]
Current Cerberus version is not able to calculate a property from javascript code. Current reported error message is: "Both object and property are null. Please specify one of them.". Please see screenshot attached below.
Link to a failed execution: /Cerberus/ExecutionDetail.jsp?id_tc=19484972

![bug_getfromjs](https://cloud.githubusercontent.com/assets/7592715/6815515/7c57802a-d282-11e4-8877-ba928b1fa014.PNG)

**Comment by afnogueira** [comment]
This issue is related to the issue #512 (CalculateProperty with no value finish the test in PE status).
The solution that addresses the issue #512 includes the specification of a FA message that should be returned when:
action = calculateProperty AND object = null/empty AND property = null/empty

**Comment by bcivel** [comment]
@cjmachado Correction pushed. 
Waiting for your confirmation

**Comment by cjmachado** [comment]
Tested the fix and it's working. 
Thanks for the help.
