### ISSUE TITLE
Cerberus is using the SQL string as property value when the query does not return results

### ISSUE THREAD

**Issue by cjmachado** [vertigo17/Cerberus#530]
When calculating an "executeSql" property, Cerberus is using the SQL string as its value when the query does not return any results. This has 2 consequences:
- Execution proceeds as if the property has value;
- Execution does not result in NA.

Example of a failed execution: /Cerberus/ExecutionDetail.jsp?id_tc=19509352

![bug_executesql](https://cloud.githubusercontent.com/assets/7592715/6844901/2e8e693c-d3a7-11e4-9bab-7c8f8864774c.png)

**Comment by afnogueira** [comment]
This bug can be reproduced by creating an action with similar specifications:

* Action type: openUrlWithBase
* Object: mypage.xhtml?id=%NUMSOC%

_NUMSOC_ - is a property that is calculated on the database through the "executeSql" method.

__Problem:__  Sometimes, when the query does not return data, Cerberus uses the SQL query as the property value. It seems that somehow, along the way, the _value_ is being set with _value1_. I think that it can be related with the following: 

__Where:__
[File: PropertyService.java][Method: calculateProperty()][Line: 108]
__testCaseExecutionData.setValue(decodedValue);__ 

```
private void calculateProperty(TestCaseExecutionData testCaseExecutionData, TestCaseStepActionExecution testCaseStepActionExecution, TestCaseCountryProperties testCaseCountryProperty, boolean forceRecalculation) {
        testCaseExecutionData.setStart(new Date().getTime());
        MessageEvent res;

        TestCaseExecution tCExecution = testCaseStepActionExecution.getTestCaseStepExecution().gettCExecution();

        /**
         * Decode Property replacing properties encaplsulated with %
         */
        if (testCaseCountryProperty.getValue1().contains("%")) {
            String decodedValue = decodeValue(testCaseCountryProperty.getValue1(), tCExecution);
            decodedValue = this.replaceWithCalculatedProperty(decodedValue, tCExecution);
            testCaseExecutionData.setValue(decodedValue); //<<<-----Check this line, is it necessary?
            testCaseExecutionData.setValue1(decodedValue);
        }
		...
}		
``` 
__Possible solution:__ Remove the line 108 if it is NOT necessary. By the way, what is the purpose of this instruction?

**Comment by afnogueira** [comment]
As @cjmachado stated, the action proceeds even if data is not found. I think we can solve it by performing some additional validations:

1)  After invoking the method _calculateProperty()_, we could check if the PropertyResultMessage holds a message that __must stop the test__:

__Where:__ [File: PropertyService.java] [ method: getValue(...)] [ line: 251] 
__Possible solution:__ Include the following verification after invoking the method that calculates the property:

```	
	[...]
	calculateProperty(tecd, testCaseStepActionExecution, eachTccp, forceCalculation);
	//if the property result message indicates that we need to stop the test action, then                
	if(tecd.getPropertyResultMessage().isStopTest()){
		testCaseStepActionExecution.setStopExecution(tecd.isStopExecution());
		testCaseStepActionExecution.setActionResultMessage(tecd.getPropertyResultMessage());
		testCaseStepActionExecution.setExecutionResultMessage(new MessageGeneral(tecd.getPropertyResultMessage().getMessage()));
	}

	[...]
```





2) Before executing the action, we could verify if the _propertyService_ was unable to get the value for the property that the action needs. 
__Where:__ [File: ActionService.java][method: doAction()] [Line: 79]
__Possible solution:__ Before proceeding with the specific _doAction_ method (e.g., doActionClick, doCalculateProperty,...), verify if the _getValue_ had generated a message that must stop the test. If true, then we don't proceed with the action.

```
	[...]
	testCaseStepActionExecution.setObject(propertyService.getValue(testCaseStepActionExecution.getObject(), testCaseStepActionExecution, isCalledFromCalculateProperty));
	
	//if the getvalue() indicates that the execution should stop then we stop it before the doAction 
	if(testCaseStepActionExecution.isStopExecution()){
		return testCaseStepActionExecution;
	} 
	[...]
```

* Do you think these verifications make sense?

**Comment by cjmachado** [comment]
Tested and it's working great (/CerberusQA/ExecutionDetail.jsp?id_tc=19665965).

Thanks!
