### ISSUE TITLE
Report : the statistics don't show any

### ISSUE THREAD

**Issue by BenjaminFr** [vertigo17/Cerberus#531]
On report MADIBA_RUN for example

The statistics do not show any. Can you please correct? Thank you

![25](https://cloud.githubusercontent.com/assets/11309774/6869573/8253a282-d495-11e4-9e0e-1da33ed703ab.jpg)

**Comment by afnogueira** [comment]
@BenjaminFr please confirm if the bug is fixed.

**Comment by bcivel** [comment]
Fixed, Thanks
