### ISSUE TITLE
"callSoap" action always throws a CerberusException

### ISSUE THREAD

**Issue by cjmachado** [vertigo17/Cerberus#533]
"callSoap" action does not work anymore. Running a test case with this action always reports the following error message: Failed to call the SOAP 'OPNAME'! Caused by : %DESCRIPTION%

where OPNAME is the name of the WS operation the test case is trying to call. Please see image below for an example of a failed execution: /Cerberus/ExecutionDetail.jsp?id_tc=19599126.

Message in logs is: 

[#|2015-03-31T16:30:17.423+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=18;_ThreadName=httpSSLWorkerThread-38093-2;|2015-03-31 16:30:17 ERROR SoapService:40 - org.cerberus.exception.CerberusException

![bug_callsoap](https://cloud.githubusercontent.com/assets/7592715/6921286/c47e7fb4-d7bb-11e4-8b43-5f5ef49c4117.png)

**Comment by cjmachado** [comment]
Just tested this feature and the action is working correctly, meaning that it calls the web service, saves the response and it's able to gather the data requested by the test case.
The problem is that the test cases are always resulting in FA, even if there isn't any error or data missing during the execution.

Example of a failed execution: CerberusQA/ExecutionDetail.jsp?id_tc=19665964

**Comment by afnogueira** [comment]
@cjmachado please confirm if the bug is fixed.

**Comment by cjmachado** [comment]
Tested and it works (/CerberusQA/ExecutionDetail.jsp?id_tc=19666009).
Thanks!
