### ISSUE TITLE
Item order in  Application field

### ISSUE THREAD

**Issue by chavez-prest** [vertigo17/Cerberus#535]
Cerberus Version : 1.1.2-SNAPSHOT

Can you put in alphabetical order the Application field for the creation of a test-case please?

**Comment by afnogueira** [comment]
@chavez-prest please confirm if the issue is solved.

**Comment by chavez-prest** [comment]
@afnogueira : No the Application field for the creation of a test-case still NOT appear in alphabetical order

**Comment by afnogueira** [comment]
@chavez-prest Just checking, you're referring to this field, right?
![2015-04-15 16_15_44-testcase creation](https://cloud.githubusercontent.com/assets/11045914/7162135/d260ebdc-e38a-11e4-9964-084ee315fc3e.png)

**Comment by chavez-prest** [comment]
@afnogueira Yes that's the right field

**Comment by afnogueira** [comment]
@chavez-prest  I have commited code that modifies how the data is sorted, i.e., the data for this field should be alphabetically sorted. Have you updated the source code? 
Can you post an image or list with the unsorted data? Thanks.

**Comment by chavez-prest** [comment]
@afnogueira How do you update the source code?
This is the screenshot of what I have :
![2015_04_16_08_43_39_testcase_creation](https://cloud.githubusercontent.com/assets/11767864/7175434/e0e6a630-e414-11e4-873f-761a9f96b378.png)

**Comment by chavez-prest** [comment]
@afnogueira 
Other exemple : 
![2015_04_16_08_46_26_](https://cloud.githubusercontent.com/assets/11767864/7175455/23a72300-e415-11e4-8503-eda5a88a0a7d.png)

**Comment by afnogueira** [comment]
@chavez-prest   Oh, I misunderstood. I thought you were using the github version, which is the one I'm changing. You're actually using the deployed version, so you may check the new updates only after the new version of cerberus is deployed to the server (192.168.134.35). As soon as that happens, I'll let you know. Thanks.

**Comment by chavez-prest** [comment]
@afnogueira Ok thank you!

**Comment by afnogueira** [comment]
@chavez-prest the fix for this issue is now deployed in the server. Please confirm if the issue is solved, and if yes, close the issue. Thank you.

**Comment by chavez-prest** [comment]
@afnogueira It's Ok now! I close the issue. Thank you.
