### ISSUE TITLE
Execution Report By Tag : Organization of test cases

### ISSUE THREAD

**Issue by BenjaminFr** [vertigo17/Cerberus#536]
On "Execution Report By Tag"

See for exemple "new_PDP" tag

Can we group the test cases by Stream and rank them in ascending order please ? Thanks

**Comment by afnogueira** [comment]
@BenjaminFr please clarify: 

* What do you mean by Stream?  Is it the browser? 
* Do you want to sort test cases by the test case ID?  

Thank you.

**Comment by BenjaminFr** [comment]
On a tag
The stream ranking is ok
It would just classify test cases in ascending order. It's possible ?
