### ISSUE TITLE
Block NewChain button on Environment.jsp with more options

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#538]
On Environment.jsp page, button NewChain is available whenever SYSTEM+COUNTRY+ENVIRONMENT is active = 'Y'.

I would also like to filter it and button could be available only if Chain column is blank or upper('Y').
This means that the NewChain button would only be active if, on countryenvparam table, column upper(`active`) is set to 'Y' and column upper(`chain`) is set to ('Y' or blank space).

**Comment by afnogueira** [comment]
@gmoita please confirm if the issue is solved

**Comment by gmoita** [comment]
I've tested it and it is ok.
