### ISSUE TITLE
Add an option to include a clear cache event to a test case

### ISSUE THREAD

**Issue by gpelissier** [vertigo17/Cerberus#542]
Many test cases require to clear the cache before testing.
This is something most common users won't think about by themselves, so programers have to add it afterwards.

Could there be an option (a checkbox ?) to add a "clear cache" instruction before running the test ?
So it would be a simple way to activate or not for the users who actually know when this is mandatory.

**Comment by cjmachado** [comment]
Could you specify which cache are you trying to clear? 
Is it the browser's cache? 
Or is it something specific to your website?

**Comment by gpelissier** [comment]
I reckon the most useful/easy to implement would be the browser's.
(say, I want to test the login page and my browser has to forget I already visited the page to avoid auto connect, for example, same for my basket, and so on)

**Comment by cjmachado** [comment]
The selenium server creates, by default, a new clean profile every time a test case is launched (at least that's the default behaviour when running with firefox), meaning that the browser always starts without any cache. 
On the other hand, it's possible to enable the cache when launching the selenium server, by passing some command-line options (run 'java -jar selenium-server-standalone-2.44.0.jar -h' to view all the parameters):
  -browserSessionReuse: stops re-initialization and spawning of the
    browser between tests
  -ensureCleanSession: If the browser does not have user profiles,
    make sure every new session has no artifacts from previous
    sessions.  For example, enabling this option will cause all user
    cookies to be archived before launching IE, and restored after IE
    is closed.

**Comment by cjmachado** [comment]
Is it information clear to you? Can I close this issue?

**Comment by gpelissier** [comment]
Ok then, fine to me !
