### ISSUE TITLE
No test cases selectable on Manual test execution

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#546]
Cerberus Version : 1.1.2-SNAPSHOT

When trying to register the manual execution of a test case, selecting the correct parameters (application name, country, environment), no test case is shown to be selected and registered.
Test is active, not automated.
Test case is active, group=MANUAL, status=WORKING, tcActive=Y, no data on FromBuild/Rev and ToBuild/Rev

**Comment by bcivel** [comment]
Beware, this way to execute testcase is deprecated and this page should be removed in a next release.
Now, run test manually is the same way that run automatic tests : 
> run test one by one : Using the RunTest.jsp (With option ManualExecution)
> run several test : Using RunMultipleTests page (With option ManualExecution)

Could that fit with your need or do you need more precision?

**Comment by gmoita** [comment]
Yes, it is working as you say, so no issue.
