### ISSUE TITLE
not saving actions with \" character combination

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#552]
Not quite sure if it's a bug or a safety feature but when trying to save a VerifyElementPresent with the following text:

xpath=//*[contains(@content, \"%TEXT%\") and @name='description']

the saved field is:

xpath=//*[contains(@content, \

So, as far I know, single and double quotes have to into every property variation instead of using them in the action one single time.

**Comment by bcivel** [comment]
Corrected with the last commit

**Comment by bcivel** [comment]
corrected
