### ISSUE TITLE
ReportingExecutionByTag is not sorted

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#553]
The report of a tag execution with several countries is not sorted by countries.
Since the header does not freeze, when we try to see the results below, we don't know the order of the countries.
![bug_reportexecutionbytag-not-sorted](https://cloud.githubusercontent.com/assets/5640464/8303163/da3f9882-1993-11e5-9bea-2bd305d1dc9f.jpg)

**Comment by afnogueira** [comment]
related issue #547

**Comment by bcivel** [comment]
In old page, it was sorted by execution date.
In new reporting page, it's sorted by env / country / browser
fixed by #560
