### ISSUE TITLE
Been able to test mobile version from Firefox with a specific display

### ISSUE THREAD

**Issue by MichaelWil** [vertigo17/Cerberus#557]
Hi,

Currently when tests that are concerning the mobile are running from Cerberus, nothing specific is done. That is to say that firefox is used full screen (just like it is for mainsite).
It will be more close to the real situation if the emulation of mobile site can be used to do these tests.
Expected behavior : when you are in the run multiples tests part : 
1- in the left column at the bottom a specific menu will be add "Choose the size of the display"
2- a drop down menu will be set with the following choices : 320*480 - 360*640 (standard mobile display) - 768*1024 - 800*1280 - 980*1280 - 1280*600 - 1920*900 - full screen.
3- When nothing is selected the default choice should be full screen like today.

Thanks.

Michael

**Comment by bcivel** [comment]
Done
