### ISSUE TITLE
Unwanted returns to the test case selection screen

### ISSUE THREAD

**Issue by gpelissier** [vertigo17/Cerberus#561]
Cerberus Version : 1.1.3-SNAPSHOT

Hi, 
I'm trying to create and edit new tests / test cases in La Redoute today (project WMS)

Every time I update a test case, either by drag&drop of a used step or by a click on "save changes" Cerberus goes back to the test case selection screen, so I have to select it all over again. Really annoying.

Regards,

**Comment by gpelissier** [comment]
Looks like it only happens on newly created tests though.

**Comment by bcivel** [comment]
Charset encoding issue. Corrected to use UTF-8 encoding
