### ISSUE TITLE
Better error message when test name is greater than 45 characters

### ISSUE THREAD

**Issue by gpelissier** [vertigo17/Cerberus#562]
Cerberus Version : 1.1.3-SNAPSHOT

Hi, in the Test>Create Test screen, when I want to save my new test Cerberus sends me to http://192.168.134.35/Cerberus/CreateTest which only appear to be a white screen.
If I check in the test list, mine wasn't created.

**Comment by corentindms** [comment]
It's probably the length of the test name which is greater than 45 characters.
