### ISSUE TITLE
Run Multiple Tests > Manual Execution > Restart a test - A parameter is missing

### ISSUE THREAD

**Issue by BenjaminFr** [vertigo17/Cerberus#563]
In Run Multiple test
For a test already executed manually
Click on the number of execution to restart the test manually ("Run the same test Case again")
At the page that appears is missing a parameter (the browser) which eprevents updating the execution report. See attachment
![1](https://cloud.githubusercontent.com/assets/11309774/8984301/f0e4528a-36d0-11e5-8659-c6818c6add65.png)

You can add this setting please ? Thank You

**Comment by afnogueira** [comment]
This issue is associated with issue #516.

**Comment by afnogueira** [comment]
@BenjaminFr - the solution was commited  in the QA environment. You can check it now in QA, or you can wait till it is available in production.

**Comment by bcivel** [comment]
Works
