### ISSUE TITLE
Manage user autorities to systems in a polynomial way

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#568]
We desire to be able to manage user access to systems on a different way (graphically), as today it is already done like that on the database.
We would like to be able to give different autorities by system.
Example: I want a user with TestAdmin to system A and TestRO to system B; currently I can only do it by direct database management.

**Comment by vertigo17** [comment]
The feature to manage authorities by System do not exist.
I wonder how you do that on the database as the feature do not exist.
I am not sure this is the way forward as it will add a lot of administration effort to maintain.
The increase in administration for me is not worth the security improvement.
BTW, if a user take the TestAdmin role he should be aware of the risk he takes to update a working test no matter the system.

**Comment by gmoita** [comment]
In terms of database, that exists today, it is just the graphical management that does not allow to do that.
I understand your point of view, but how can I give different accesses to systems?
If I want to give TestAdmin access to a system but don't want to give that access level to other systems, I can't.

**Comment by gmoita** [comment]
My previous comment was not correct, as the database is not fully capable of doing that.
But I still have the problem and would like not to have it :)

**Comment by vertigo17** [comment]
So we agree that the feature do not exist at all (even doing it from the database) and it is not only a matter of GUI ?

**Comment by gmoita** [comment]
Yes, it is correct.
This issue is an enhancement request.
