### ISSUE TITLE
Test case update of UseStep information saves test case immediately

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#570]
When we change a step of a test case that is flagged as UseStep and the information from the copied test is changed (using the drop down list available), the test case is automatically saved.
This is an abnormal behaviour and causes some problems, even if the UseStep information selected different by mistake.

**Comment by afnogueira** [comment]
@gmoita Please check if the issue is solved.

**Comment by gmoita** [comment]
For me it is ok, as we can see the result of the change by clicking on the "reload" button and cancel the changes when we want, without saving it.
