### ISSUE TITLE
The Test field should allow more than 45 chars

### ISSUE THREAD

**Issue by DanielOlival** [vertigo17/Cerberus#571]
Cerberus Version : 1.1.3-SNAPSHOT

Currently the Test field only allows 45 chars maximum to be defined, forcing the test to have abbreviations to fit the limit.

**Comment by vertigo17** [comment]
Test with Testcase is part of the key.
In my view 45 caracters is already pretty big.
Making it even bigger will introduce risk in terms gui display and report as any report at a test level will take a big part of the screen to display the complete content.
Not to mention the database size impact.

Abreviation or standardisation is for me the right solution to key it synthetic.
You could also use the description or function field if more information is required.

Anyway, we will discuss with Benoit what is the best way to proceed.

**Comment by bcivel** [comment]
We should try to display everywhere we have the test name, the test description (256 characters), the same way we do with the testcase number and testcase description.

**Comment by vertigo17** [comment]
Daniel, please use Description field and specify where you want it to be displayed.

**Comment by DanielOlival** [comment]
Hi Benoit,

Sorry for the delay. I was reviewing my e-mails and noticed i had missed
this one.
We've opted to use abreviations

Best Regards,

**Comment by gmoita** [comment]
Confirmed with Daniel Olival that the issue can be closed.
