### ISSUE TITLE
UseStep can be set as Library Step

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#572]
Currently, a step on a testcase that is set with useStep='Y' can also be set with inLibrary='Y'.

I believe it makes no sense that a step that uses another can be set as a step library.
In this case, initial step library can and should be used on both steps where it is required.
If this is used like it is now, is leads to step actions not being shown on test case page detail.

Example:
- TestLibrary 0001A step 1 is set as step library (without useStep)
- Test 0001A step 1 has actions defined on the testcase
- Test 0001A step 2 is set as useStep, to use TestLibrary 0001A step 1; at the same time, it is set as Library

**Comment by afnogueira** [comment]
@gmoita Please check if the issue is solved.

**Comment by gmoita** [comment]
Confirm that was not able to set UseStep at the same time as Library step.
