### ISSUE TITLE
Cannot view execution report for tests that do not require a browser to run

### ISSUE THREAD

**Issue by cjmachado** [vertigo17/Cerberus#573]
Currently there are two options to view an execution report:
- Either by accessing the ExecutionReportByTag page and specifying a tag OR
- By accessing the ExecutionStatus page and specify the search filters

On both pages, the user must specify/check the browser used to run the test cases.
We are now running tests that do not require a browser to run (specifically, we are testing WebServices). On the ExecutionReportByTag page, it is only possible to view the pie chart. On the ExecutionStatus page, no execution is shown.
As a temporary workaround, we are currently updating the testcaseexecution table directly on the database to fill the Browser fields with valid values.

**Comment by afnogueira** [comment]
This issue is related to issue #560

**Comment by bcivel** [comment]
Fixed with the issue #560
