### ISSUE TITLE
Test Data Screen - Error message when there is not item found

### ISSUE THREAD

**Issue by amarlot** [vertigo17/Cerberus#578]
Hi Team,

When you search something in data cerberus which is not found, we got an error message.
Could it be possible to have nothing in the list when there is nothing found.
This pop up is displayed each time you remove one letter until there is a match.

Thanks,
alex

![image](https://cloud.githubusercontent.com/assets/10206313/9731232/03110cfe-561c-11e5-8357-ea2851fcfbaf.png)

**Comment by bcivel** [comment]
works
