### ISSUE TITLE
RunTestsTriggerBatchExecution.jsp > Displayed client side error when Tag is not set up

### ISSUE THREAD

**Issue by amarlot** [vertigo17/Cerberus#579]
Hi Team,

Currently in the screen RunTestsTriggerBatchExecution.jsp, if you forgot to enter a tag model, you get an error on next page but it's too late.
If you go back on the previous page all the set up is empty:(

Could you display a client side message to ensure the tag is mandatory. (Or don't erase config when we go back to previous page).

Thanks,
Alex

![image](https://cloud.githubusercontent.com/assets/10206313/9738059/09b1492e-564a-11e5-987b-66498ca22bfe.png)

**Comment by amarlot** [comment]
Hi Team,

Or maybe it's better to create a tag name automatically if it's empty with user _+ year + month+ day+ minutes

like amarlot_201509091139

I don't know what is better.
Alex

**Comment by bcivel** [comment]
Won't fix that page as the new run page is going to replace this one

**Comment by bcivel** [comment]
@amarlot ,I close this issue as new run page is doing what you expect. We will soon remove the beta status.
Thanks for your contribution
Benoit
