### ISSUE TITLE
ReportingExecutionByTag.jsp : Chrome : Not able to click

### ISSUE THREAD

**Issue by amarlot** [vertigo17/Cerberus#580]
Hi Team,

If you go there it's not possible to click on a country for example as the div and the graph are over the checkbox.

Could you fix it ?
Thanks,
Alex

![image](https://cloud.githubusercontent.com/assets/10206313/9758576/ccf8976e-56e7-11e5-96b8-8249a74d238c.png)

**Comment by afnogueira** [comment]
Hello @amarlot,
The ReportingExecutionByTag.jsp page is being refactored in scope of the issue #560. This issue will be fixed when the new version of the page is deployed to production. For now, can you try with another browser, e.g., Firefox? Is the same problem present?

**Comment by amarlot** [comment]
Confirm it's ok on Firefox.

**Comment by bcivel** [comment]
fixed
