### ISSUE TITLE
verifyElementVisible possibly not working

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#582]
Found the following situation:
- 3 select fields with the same structure and diferent data-cerberus (modify basket product on mobile)
- verifyElementVisible works for the first one 
- verifyElementVisible does not work for the others, even if it is in the first control to be executed
- verifyElementPresent works

I'm stuck in this problem and couldn't find any explanation for this behaviour. 
Test case where found: /Cerberus/ExecutionDetail.jsp?id_tc=23956450

**Comment by ruirpr** [comment]
Cerberus help says that verifyElementVisible verify if the element is visible, exists and has text in it. 
So i tried the xpath=//select[@id='filterSize']/option[1] and it works! Using only the xpath=//select[@id='filterSize'] doens't work.
But i dont understand why it works for the first select using data-cerberus.

**Comment by ruirpr** [comment]
Finally found the problem. Both failing <select> have the class:

    .selectText{
        opacity:0;}

This hides the text selected from the dropdown. The text shown in the dropdown is a label over the select. The solution is to change opacity to 1 using calculateProperty with 

document.getElementById('filterQuantity').style = 'opacity:1'; return 'done'; 
    
So, it’s not a Cerberus bug.

**Comment by afnogueira** [comment]
@ruirpr thank you for your feedback. I'm going to close the issue.
