### ISSUE TITLE
Action not working with data-cerberus 

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#583]
When aplying an action in a button inside a form, using data-cerberus, the test fails to do the action. Using xpath with the button class or id name works (and fails using xpath with the data-cerberus). 
This behaviour can be checked here Cerberus/ExecutionDetail.jsp?id_tc=24027162 (TC already changed to xpath)

Maybe related to #582 ?

**Comment by ruirpr** [comment]
Indicated TC changed back to data-cerberus click due to work in preprod environment.

**Comment by bcivel** [comment]
Not a Cerberus Issue. Due to 2 several field with the same data-cerberus

![capture](https://cloud.githubusercontent.com/assets/5376184/9962162/a91712e6-5e24-11e5-8cce-79977d90ed3f.JPG)
