### ISSUE TITLE
RunMultipleTests filters not loading

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#584]
Cerberus Version : 1.1.3-SNAPSHOT

The current version on QA, is not loading the filters for page.
On the logs, I see the following message:
[#|2015-09-15T10:48:29.777+0200|INFO|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=113;_ThreadName=Thread-2;|2015-09-15 10:48:29 ERROR ApplicationDAO:40 - Execute query : SELECT SQL_CALC_FOUND_ROWS * FROM application  where 1=1  and (`System`='VCCRM' ) order by `sort` asc limit 0 , 100000
|#]

**Comment by afnogueira** [comment]
@gmoita 
I have commited a fix for this issue. I forgot to associate the issue to the commit but you can check the modifications [here] (https://github.com/vertigo17/Cerberus/commit/1e958e536ff04a77329e1b73d528867ac09208f4)

Please check if everything is working as expected.

**Comment by gmoita** [comment]
Confirm that filters are visible again, although it is showing "NoDoc!!" errors.

**Comment by afnogueira** [comment]
@gmoita I have committed  the fix for the NoDoc!!" errors. 
Can you please check if everything is ok? 

Thank you.

**Comment by afnogueira** [comment]
@gmoita I assume that everything is OK. I will close the issue. If you find some problem, please re-open it. Thank you.
