### ISSUE TITLE
Cerberus cannot handle keypress on a system window

### ISSUE THREAD

**Issue by RobertoAbraul** [vertigo17/Cerberus#586]
Cerberus cannot handle key press "enter" on a system window.

Please see attachment.
![systemwindow](https://cloud.githubusercontent.com/assets/14328346/9930097/273d05d8-5d29-11e5-98bd-f2666723a806.PNG)

**Comment by bcivel** [comment]
Duplicate ticket with #574 
Will be possible in the next release
