### ISSUE TITLE
Currently in the rapport there's no way to check if all tests were ran

### ISSUE THREAD

**Issue by MichaelWil** [vertigo17/Cerberus#587]
Hi,

Sometimes (for a reason not linked to Cerberus) all the tests are not launched.
But as the number keeps on increasing almost each day it's almost impossible to be sure than 100% of the tests ran or not.
So it'll be very usefull to have displayed the report between the number of test in the whole campaign and the number of tests that did ran.
For example : 1589/1600 will mean that 11 tests didn't run (1600-1589).

Thanks.

**Comment by bcivel** [comment]
Not possible to know it in advance as you execute tests from bat or shell script, and your tests are submitted one by one.
As soon as you switch to run multiple script, you'll have this kind of information
