### ISSUE TITLE
Test case save saves wrong information

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#588]
Cerberus Version : 1.1.3-SNAPSHOT

On QA, when saving a test case (either by Save As or Save buttons), if an action has special characters (like ampersand "&" and apostrophe "'"), the information on the database is saved with the corresponding converted "xml" characters (like the "&amp;" and "&#39;")

On some cases the ampersand replacement works ok (if on a URL, for example and not wrapped on apostrophe), but if the ampersand is wrapped on apostrophe, then it fails.
Example: Test case "PAGE VCConfigZipCodesManagement" 0007B was duplicated to 0007C (on QA env); 0007B works fine; 0007C fails.

**Comment by bcivel** [comment]
Solved with my last commit

**Comment by gmoita** [comment]
Confirmed save is now correct; can be closed.
