### ISSUE TITLE
In the TC execution data table, the value for Environment is set to "" if the user enters manual configurations in the RunTests.jsp page

### ISSUE THREAD

**Issue by afnogueira** [vertigo17/Cerberus#596]
In the RunTests.jsp page (Fig. 1) if we:

* Choose the environment "Manual"
* Define a tag (e.g., TAG_XPTO) in order to view the execution in the page "Report by tag".
* Run the test case

**Fig.1**
![1](https://cloud.githubusercontent.com/assets/11045914/10098458/59350b16-6379-11e5-82d4-15def8936be8.png)

In this scenario, in the table "testcaseexecution", the environment value for the test case execution will be an empty string.

**Problem:** in the report by tag page, the page creates a checkbox for the empty value (Fig. 2), which in turn generates a bug that impedes the generation of the charts, because those charts use the information displayed in the checkbox filters.

**Fig.2**
![report](https://cloud.githubusercontent.com/assets/11045914/10098417/0f18c9a0-6379-11e5-86c2-94a53b53af04.png)

Related to issue: #560 

I don't if this problem is already being solved in the new refactored version of the page ReportingExecutionByTag.jsp. Nevertheless, we should think if it makes sense to save an empty value when the the test case is executed in the manual environment.

**Comment by corentindms** [comment]
It seems ok on the new ReportingExucitonByTag version, however the environment seems to be set as the value selected when Automatic is checked

**Comment by vertigo17** [comment]
Today, if we run a test in manual mode, we force the environment at empty string.
We could change that to NONE so that we avoid the empty value.

**Comment by bcivel** [comment]
Set env to manual in case of execution on custom environment
