### ISSUE TITLE
Manual execution doesn't run when you set a tag with spaces

### ISSUE THREAD

**Issue by corentindms** [vertigo17/Cerberus#597]
When you want to run a test manually and you set a tag with spaces in it, the manual execution screen is not loading properly (white screen and you can't do nothing) and the tag truncated at the first space.

Automatic execution with a tag containing space does work properly

**Comment by afnogueira** [comment]
I don't have problems in defining a tag with spaces. Please check figures above:
Run Tests page:

![1](https://cloud.githubusercontent.com/assets/11045914/10249069/412f5916-691b-11e5-84dc-9ac42bff07ea.png)

ExecutionDetail page:
![2](https://cloud.githubusercontent.com/assets/11045914/10249080/4ea2af9e-691b-11e5-82ef-b6a8aa74bede.png)

Report by tag:
![3](https://cloud.githubusercontent.com/assets/11045914/10249082/50de1d7a-691b-11e5-8f64-d90cea9394d8.png)

Maybe I didn't understand the issue, can you please post an example of the tag that originated the issue?

**Comment by corentindms** [comment]
It's not when setting the environnement manually but when you select Manual Execution in the bottom right select. Can't add a screenshot for the moment, will do as soon as I can
