### ISSUE TITLE
Documentation data is not immediately available after the execution of the database version upgrade

### ISSUE THREAD

**Issue by afnogueira** [vertigo17/Cerberus#598]
I have created a set of new translations that should be displayed in the GUI, however they are not immediately available after the execution of the database's version upgrade.

When I perform login, I'm redirected to the DatabaseMaintenance page (as expected) and I execute the new SQL instructions. When I open the page that requires the new documentation data, I found that those are not available yet. 

In order to see the new documentation I have to logout and login again.

**Comment by corentindms** [comment]
The documentation is loaded in the sessionStorage of the browser to provide quick access to it.
The sessionStorage is cleared and reloaded in two cases : 
- When you login
- When you change language

A solution would be to clear the sessionStorage each time you update the database, even if the documentation is not impacted.

**Comment by afnogueira** [comment]
Thank you for clarifying how it works. You can decide the best approach. For me, it is only important not to see the "warnings" related to the lack of documentation when in reality the data is available in the database.
