### ISSUE TITLE
clickAndWait is not working anymore

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#600]
Cerberus Version : 1.1.3-SNAPSHOT

clickAndWait action is not working anymore, even if the element is present.
examples:
http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=24676035 (with clickAndWait result FA)
http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=24676075 (with click + wait result OK)

**Comment by bcivel** [comment]
Still works but will be deprecated in a next release.
