### ISSUE TITLE
Homepage display more than 10 Application.

### ISSUE THREAD

**Issue by vertigo17** [vertigo17/Cerberus#601]
In the homepage, when selecting a System that has more than 10 applications, the application list do not consider the limit and display the full list.
For VCBAT, 69 applications are displayed althought the table specify 10 and pagination display control as if the table contain only 10. 
Cerberus Version : 1.1.3-SNAPSHOT

**Comment by afnogueira** [comment]
@vertigo17 Please check if it is working as expected. Thank you.

**Comment by vertigo17** [comment]
It is thank you.
