### ISSUE TITLE
switchToWindow is not working

### ISSUE THREAD

**Issue by cjmachado** [vertigo17/Cerberus#603]
Running a test case with "switchToWindow" action fails when Cerberus tries to execute it. Example test case is Cerberus - 9608A. Error message is: Failed to switch to window because could not find element 'Index 2 dummy page' .

No messages were found in log files.

**Comment by bcivel** [comment]
Corrected with my last commit

**Comment by cjmachado** [comment]
Shouldn't this be labelled as a bug?

**Comment by bcivel** [comment]
@cjmachado you're right, it's was a bug.
Fixed now
