### ISSUE TITLE
Not possible to perform actions on "open file" dialogs

### ISSUE THREAD

**Issue by cjmachado** [vertigo17/Cerberus#604]
Related to issue #586 (which is currently closed). 

We currently have a few cases that upload a file to the server. We need to automate the "open file" dialog. We tried to perform a "keypress" action for that dialog but it fails to execute with the following message: Failed to press key because could not find element 'id='
Cerberus is showing this message because the action does not have any object defined, but there's no way to specify it.

Example test case which uses an "open file" dialog: Vendor Integration - 0026A (from XTPI system).

**Comment by bcivel** [comment]
@cjmachado #586 has been closed a bit quiclky, you're right. The dev is done and working but the documentation not up to date. Will do it soon

**Comment by cjmachado** [comment]
OK. Thanks.

**Comment by bcivel** [comment]
done by @afnogueira
