### ISSUE TITLE
Improve display of properties when use getfromDataLib : Display all data requested in the SQL Request

### ISSUE THREAD

**Issue by amarlot** [vertigo17/Cerberus#605]
Hi team,

When you get data from DataLib and you return several column like productId, color, size, ...
Would it be possible to display all atributs requested in the SQL Request with the name (mapped name) and the value like:
ProductId:1215456
Color : Red
Size : XXL
...

![image](https://cloud.githubusercontent.com/assets/10206313/10308306/159ecb16-6c35-11e5-90e8-fd82aae353d2.png)

Thanks,
Alex

**Comment by afnogueira** [comment]
@amarlot Next developments may include your request. I will analyse its feasibility, and I will keep you updated.

**Comment by vertigo17** [comment]
Feature has been added with the following message. as output :
{=324493887, COLOR=Bleu moyen, SIZE=38/40}

![selection_074](https://cloud.githubusercontent.com/assets/5342048/15455282/c101f40a-204f-11e6-9f06-107d1cc79ba7.jpg)

**Comment by amarlot** [comment]
Thanks Benoit. It’s perfect ☺

Alexandre Marlot
Tel direct : + 33 3 20 69 79 94

De : Benoit DUMONT [mailto:notifications@github.com]
Envoyé : dimanche 22 mai 2016 19:03
À : vertigo17/Cerberus <Cerberus@noreply.github.com>
Cc : MARLOT Alexandre <amarlot-prest@redoute.fr>; Mention <mention@noreply.github.com>
Objet : Re: [vertigo17/Cerberus] Improve display of properties when use getfromDataLib : Display all data requested in the SQL Request (#605)


Feature has been added with the following message. as output :
{=324493887, COLOR=Bleu moyen, SIZE=38/40}

[selection_074]<https://cloud.githubusercontent.com/assets/5342048/15455282/c101f40a-204f-11e6-9f06-107d1cc79ba7.jpg>

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub<https://github.com/vertigo17/Cerberus/issues/605#issuecomment-220843449>

Les informations contenues dans ce message ainsi que dans les pièces jointes sont strictement confidentielles et réservées à l'usage exclusif de ses destinataires. Si vous prenez connaissance de ce message sans en être le (la) destinataire, vous êtes prié(e) d'en aviser immédiatement l'émetteur et de le détruire sous toutes ses formes. Toute diffusion ou publication, totale ou partielle, est interdite sauf autorisation expresse de l'émetteur. Les meilleurs efforts sont faits pour maintenir cette transmission exempte de tout virus mais l'intégrité de ce message n'est pas assurée sur Internet : il a pu être altéré ou falsifié. Les points de vue ou avis émanent de son auteur et ne représentent pas nécessairement ceux de la Société. Son contenu ne peut engager la responsabilité de La Redoute et de ses filiales. This message and any attachments are strictly confidential and intended solely for the addressees. If you have received this message in error please delete it and notify the sender immediately. Any dissemination or disclosure, either whole or partial, is prohibited except formal approval of the sender. Best efforts are made in order to keep this message free of virus, but integrity of this message is not guaranteed through the Internet : it could have been altered or falsified. The views or opinions presented here are solely of the author and do not necessarily represent those of the Enterprise. Its content cannot bind La Redoute and its subsidiaries.
