### ISSUE TITLE
Step model is not duplicated when you duplicate TestCase

### ISSUE THREAD

**Issue by amarlot** [vertigo17/Cerberus#609]
Cerberus Version : 1.1.3-SNAPSHOT

Hi Team,

When you duplicate a TestCase which contains some Step Model, in the new Test Case, the step model is not duplicated !

Could you fix it ?

Thanks,
Alex

Original :
![image](https://cloud.githubusercontent.com/assets/10206313/10394492/eb45f708-6e97-11e5-830f-f0c687329dfd.png)

Duplicated TC : 
![image](https://cloud.githubusercontent.com/assets/10206313/10394499/fcf4fa30-6e97-11e5-9422-1d192d571cdb.png)

**Comment by afnogueira** [comment]
@amarlot I will check it. This is related to issue #569 .
Please note that when you select a useStep, it will not be saved automatically (this behaviour was causing other problems). 
So, now you need to select the step, click the button load, and then save the test case.

**Comment by afnogueira** [comment]
@amarlot  Can you please check if this issue is fixed?
