### ISSUE TITLE
User is not redirected to ChangePassword page after first login

### ISSUE THREAD

**Issue by cjmachado** [vertigo17/Cerberus#610]
Steps to reproduce:
1. Login to Cerberus;
2. Go to Administration -> User Management;
3. Select an user and change the "Request Password" from 'N' to 'Y' (you should already know the user's password).
4. Logout and login again with the user selected in the previous point;
5. After login, user is redirected to HomePage but it is expected that Cerberus would redirect to ChangePassword;
6. Navigating through any of the links available in the HomePage will redirect the user to ChangePassword page;

**Comment by afnogueira** [comment]
@cjmachado Please check if this issue is solved. Thank you.
