### ISSUE TITLE
When you save a step with the same number as another step, it gets overwritten

### ISSUE THREAD

**Issue by corentindms** [vertigo17/Cerberus#611]
When in a test case you have 2 steps numbered 1 and 2 : 
![sans titre](https://cloud.githubusercontent.com/assets/9135175/10430003/e65dd726-70fc-11e5-9be5-0c89860c662a.png)

If you change the number of the Step by setting the first step in number 2 : 
![2015_10_12_16_19_36_testcase](https://cloud.githubusercontent.com/assets/9135175/10430030/240e3eda-70fd-11e5-997c-52d7096b3f3d.png)

And save the changes, the step 2 is overwritten : 
![image](https://cloud.githubusercontent.com/assets/9135175/10430056/4bfa3886-70fd-11e5-858c-ece1e16b4179.png)

**Comment by afnogueira** [comment]
This will be solved while converting the page TestCase.jsp.

**Comment by afnogueira** [comment]
@corentindms  Can you check if the issue is fixed? Thank you.

**Comment by corentindms** [comment]
This bug is fixed. Thank you.
