### ISSUE TITLE
Not possible to run same test when no group is selected 

### ISSUE THREAD

**Issue by thomas-aw** [vertigo17/Cerberus#614]
If you don't select any group, in test case info, in test case execution detail the link "Run the same Test Case again" is not displayed

**Comment by vertigo17** [comment]
A testcase can only be executed if it is either AUTOMATED or MANUAL
In order for the link to appear, group must get one of the 2 values.
What is strange is that if a previous execution was done it means that the testcase was either AUTOMATED or MANUAL at that time and for one reason someone removed the group information by mistake.
Anyway even if not directly related, I fixed a small issue on the same contextual link in TestCase page that was not correct.
I let you confirm that it is clear and close the ticket.

**Comment by thomas-aw** [comment]
It was to highlight the possibility to save a test case without group. It would be good to require a group during test case creation :)

**Comment by vertigo17** [comment]
Thomas, it should now be fixed in QA.
Please confirm and close the issue.
