### ISSUE TITLE
hard failure while setting wrong step numbers

### ISSUE THREAD

**Issue by NotoriousBig** [vertigo17/Cerberus#617]
Hello, 

I had a failure while  setting wrong step numbers

![error - mozilla firefox](https://cloud.githubusercontent.com/assets/13114629/10612913/380003ae-7753-11e5-9dc2-2eb9fdb0881b.jpg)

Cerberus Version : 1.1.3-SNAPSHOT

Sébastien B.

**Comment by afnogueira** [comment]
@NotoriousBig  Issue was related to issue #611. Should be fixed now.
