### ISSUE TITLE
Re-execution issue trough Reporting Execution by tag

### ISSUE THREAD

**Issue by thomas-aw** [vertigo17/Cerberus#620]
To replicate  : 
- Go on a reporting execution
- Click on a test to run it manually
- Set the test case KO
- Go back on the reporting execution
- Click on the KO test case
- Click on Run the same test case again
- Go back on the reporting execution
- Our first execution is still KO instead of PE and there is a new column with browser undefined and with the new execution PE

**Comment by corentindms** [comment]
The bug was happening when the test case was in group "MANUAL"
