### ISSUE TITLE
Bug ID in test case execution list

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#622]
Is it possible to show the Bug ID for each test case in Report Execution by Tag, like it used to be? 
Thanks!

**Comment by corentindms** [comment]
I propose you to display the bug ID in a tooltip, maybe on the mouse over the testcase number as it is related to the Test Case.
Do you have other information that could be useful to display too ?

**Comment by ruirpr** [comment]
From a user point of view a tooltip is not very pratical. The ideia was to identify tests with bugs as quickly as possible but the tooltip is better than nothing.
