### ISSUE TITLE
verifyElementNotVisible fails when elemement is not present

### ISSUE THREAD

**Issue by spinto-redoute-pt** [vertigo17/Cerberus#623]
The verifyElementNotVisibl control fails with FA if the element is not present.
The controls should pass with OK because if the element is not present is not visible either.
![elementnotvisible](https://cloud.githubusercontent.com/assets/15423126/10843034/20135db6-7eee-11e5-8e2f-dc0bdc1515d8.png)

**Comment by afnogueira** [comment]
@vertigo17 @bcivel @gmoita @cjmachado What is your opinion? Should this action fail if the element is not present when we are validating the visibility?

**Comment by corentindms** [comment]
The point of the action verifyElementNotVisible is to verify if the element is present, but not visible on the screen. There is cases when you could want to have this element present on the page (in the HTML/the DOM) but not visible on the page (eg : with a display none css attribute).
In my point of view, the behavior of this control make sense.

There is other actions that could do the job that you want depending on the control you want to perform : 
verifyElementPresent/NotPresent ===> Verify if the element is/is not present at all (not depending of the visibility of the element)
verifyElementVisible/NotVisible ===> Verify if the element is present and is/ is not visible

**Comment by bcivel** [comment]
verifyElementNotVisible implicitly mean the element should be present and not visible.
As @corentindms said, the behavior of the current control seems correct.

**Comment by afnogueira** [comment]
@spinto-redoute-pt I'm going to close this issue. The **verifyElementNotVisible** is working as expected. 
You may want to consider other type of control verification for validating the visibility/presence of your HTML element. If you have any question, please let us know. Thank you.

**Comment by spinto-redoute-pt** [comment]
I don’t’ agree with you. In my option controls should do what they say and nothing more. If a controls is verifyElementNotVisible, it should only check if an element is not visible. Obviously, if the element is not present, is not visible.
If you want to check if an element is present but no visible you can check it adding a verifyElementPresent followed by a verifyElementNotVisible.
However if verifyElementNotVisible checks if an element is present, I can’t check the following scenario: when the user does an action it may be displayed an error message if the action fails or may be redirected to another page if the action succeeds. The error message is already present, but not visible. I want to check if there wasn’t any error. I can’t use verifyElementNotPresent because the element is present but not visible. I can’t use verifyElementNotVisible because if the action succeed the user will be redirected to another page and the element will not be present.
If the verifyElementNotVisible didn’t check if the element is present or not. Both situations would be possible.

**Comment by bcivel** [comment]
@spinto-redoute-pt Even if I not totally agreed with you initially, I finally implemented the rule as you described, has it is the same way that selenium works (meaning if element is not present, then it is not visible by the way).
