### ISSUE TITLE
Not possible to filter by AUTOMATED group in Execution Status page

### ISSUE THREAD

**Issue by cjmachado** [vertigo17/Cerberus#625]
The Execution Status page allows the user to specify several filters to narrow the search but the Group filter is missing the AUTOMATED group.

![automated_group](https://cloud.githubusercontent.com/assets/7592715/10907328/043e103c-8221-11e5-9689-c83fc298f51e.png)

**Comment by corentindms** [comment]
Should be fixed with my last commit

**Comment by afnogueira** [comment]
@cjmachado I verified that the Group filter is displaying the AUTOMATED option. Thus, I will close this issue.
