### ISSUE TITLE
Cannot add revision definition

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#626]
Cerberus Version : 1.1.3-SNAPSHOT

When trying to add revision definition, after filling all the information and click on save button, application is not responding; on the logs, we have:
[#|2015-11-03T14:08:34.535+0100|INFO|sun-appserver2.1|javax.enterprise.system.container.web|_ThreadID=30;_ThreadName=httpSSLWorkerThread-38093-4;|Unable to find a <servlet-name> element which map: /CerberusRegression/CreateBuildRevisionInvariant1|#]

**Comment by afnogueira** [comment]
All servlets required by the page BuildRevDefinition.jsp (create, delete, and update) are now included in the web.xml file. I will close the issue.
