### ISSUE TITLE
Record my Robot Prefrences not working

### ISSUE THREAD

**Issue by spinto-redoute-pt** [vertigo17/Cerberus#628]
In the run tests page, when I change the robot settings and click "Record my Robot Preferences", the preferences aren't saved. The next time I open the page it has the previous settings.
Steps to reproduce:
1) Open Run test page;
2) Change  Selenium Server IP
3) Click "Record my Robot Preferences"
4) Close the page
5) Reopen Run test page
The Selenium Server IP has changed to previous value

**Comment by corentindms** [comment]
The RunTests page is currently being reworked, this issue will be solved in the next version of the page

**Comment by afnogueira** [comment]
@spinto-redoute-pt  can you confirm that this issue is fixed?

**Comment by fabiogasparferreira** [comment]
This issue is causing @spinto-redoute-pt to be angry with me, since I already had his IP address

**Comment by spinto-redoute-pt** [comment]
Hi Filipa,
it's working fine on QA.
I'm looking forward to have this correction on production.

Thanks
