### ISSUE TITLE
Statistics implementation

### ISSUE THREAD

**Issue by mbessa** [vertigo17/Cerberus#630]
Hello,
To help us analyze and detect issues on one Front, it is possible to implement some statistics related with campaign execution Tag, per Front?

Example:

Status          Server IP       ExecCount
FA              172.25.71.213   18
FA              172.26.71.216   20
KO              172.25.71.213   96
KO              172.26.71.216   104
NA              172.25.71.213   11
NA              172.26.71.216   9
OK              172.25.71.213   1279
OK              172.26.71.216   1277
PE              172.25.71.213   6
PE              172.26.71.216   3

Server IP                 OK      KO      FA      NA      PE             |       Total
172.26.71.216   45.31%  3.40%   0.64%   0.39%   0.21%   |       49.95%
172.26.71.216   45.24%  3.68%   0.71%   0.32%   0.11%   |       50.05%

With this statistics it will be easier to detect Fronts with strange behavior while running a campaign.
If you need more details, please let us know.

Antoine sugested that this could be implemented in: http://......./Cerberus/ExecutionDetailList.jsp
But it will be also usefull in: http://...../Cerberus/ReportingExecutionByTag.jsp

Thanks in advance.
MB

Cerberus Version : 1.1.3-SNAPSHOT

**Comment by vertigo17** [comment]
@mbessa, the difficulty on that is that the Front IP s very specific to the application tested.
Front IP is not a standard TestExecution data but a specific property. Can you confirm you get it from serverName property in the test ?
Not impossible to implement but it may be quite complex to do.

**Comment by mbessa** [comment]
Hi,
Yes you are correct, at this point I think is specific for Theseus. It is inserted in Pre-testing and it is the serverName property.
Thanks

**Comment by bcivel** [comment]
@mbessa Not really pertinent to do that specific report as it make sense only in this context. To have this king of reporting, is it possible fro you to try designing a kibana report with the execution information?
All the execution information are available in the server log.

I close the issue but don't hesitate to react on it or reopen if you wanna discuss it
