### ISSUE TITLE
Wait action take 3 hours to execute

### ISSUE THREAD

**Issue by afnogueira** [vertigo17/Cerberus#632]
Some tests are taking excessive time to finish. For some test cases, wait actions are taking approximately 3 hours. 
Check the figure below taken from the execution detail ExecutionDetail.jsp?id_tc=25730466.
![2015-11-10 16_16_08-execution detail](https://cloud.githubusercontent.com/assets/11045914/11068668/564ae45a-87ca-11e5-9406-8e84dd63d383.png)

**Comment by afnogueira** [comment]
Maybe related to this: https://code.google.com/p/selenium/issues/detail?id=3951
A workaround is available in :http://matejtymes.blogspot.co.uk/2014/10/webdriver-fix-for-unreachablebrowserexc.html

**Comment by bcivel** [comment]
Can't be solved by us as it come from selenium.
I propose that you use https://github.com/vertigo17/Cerberus/blob/master/tools/selenium/bin/kill-firefox-zombieprocess to kill process after 20 minutes.
