### ISSUE TITLE
Unable to create the first test case in a recently created test

### ISSUE THREAD

**Issue by afnogueira** [vertigo17/Cerberus#635]
Users have some issues when they need to create test cases in a recently created test.

In the "Add test case" page, some dropwdown components are not loaded with the data (check figure below):
![2015-11-12_1413_001](https://cloud.githubusercontent.com/assets/11045914/11121033/7a09418e-894b-11e5-9d54-dac629c2df06.png)

If we open firebug, we can see that there are issues accessing some servlets (figure below). 
![2015-11-12_1413](https://cloud.githubusercontent.com/assets/11045914/11121039/83756220-894b-11e5-9783-17c5777e3a90.png)

**Comment by corentindms** [comment]
This should be fixed, it was a problem of rights definition in the web.xml file for those servlets

**Comment by afnogueira** [comment]
@corentindms  
It seems to be fixed in QA, I will close the issue after confirming the correct behaviour in PROD. 
Thank you.

**Comment by afnogueira** [comment]
@corentindms it seems to be fixed in PROD. I will close the issue.
