### ISSUE TITLE
How to add testcases to battery?

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#636]
I see no way to add testcases to a battery. There is a window with Tests an Projects but nothing happens when clicking. 

![fireshot screen capture 059 - test battery - 192_168_134_35_cerberus_testbattery_jsp](https://cloud.githubusercontent.com/assets/1914659/11203535/98bb95d8-8cec-11e5-8363-18cd01c769f1.jpg)

**Comment by corentindms** [comment]
This should be fixed in QA now

**Comment by gmoita** [comment]
Deployed in PROD and working ok.
