### ISSUE TITLE
Don't allow the deletion of a Test Case that has steps used by other TCs

### ISSUE THREAD

**Issue by afnogueira** [vertigo17/Cerberus#637]
In the test case list, we should not allow the deletion of a TC, when it defines steps that are imported by other TCs. The consequence of allowing this type of operation is serious because a great number of test cases can be compromised if, for instance, a test case is deleted by mistake.

**Comment by corentindms** [comment]
Should be fixed now. The delete button is still displayed but an error message is displayed when you try to delete the test case indicating why you couldn't delete it which I find clearer for the user.
