### ISSUE TITLE
Discussion thread for properties with NotInUse nature

### ISSUE THREAD

**Issue by afnogueira** [vertigo17/Cerberus#638]
**Goal:**
Allow test cases to select test data that is not currently being used by other test cases.

**Scope:**
* The definition of the nature notInUse is defined at property-level. 
* Type of properties: only getFromDataLib properties should use this type of nature. 

**Operation mode:**
During the test case execution, it tries to calculate and access a property that has nature notInUse, and it finds that the property is being used by another test case. How should that test case proceed?
* Stop the execution doesn't seem correct
* Select the next best value. For me, the difficulty is on answering this question: How can we decide which is the next best value?

  * STATIC -> does not seem feasible, because if the property is static, the data available is always the same.
  * SQL -> we can store a set of rows returned by the SQL instruction and then get another value. 
  * SOAP -> we can retry the xPath expression and try to obtain a different value from the SOAP response.

For SQL and SOAP, the SQL query and the xPath expressions may be so specific that they do not allow us to retrieve alternative values. Therefore, we don't have an alternative value to provide to the test case.
 

**Other questions:**
* [Key question] What is the best approach to store and share data among test cases without impacting the performance of the whole testing process?
*  [Key question] How can we ensure that the data that we want to use in an exclusive manner is not being used by other properties that don't have notInUse nature and that aren't from type 'getFromDataLib'?

* Shouldn't the test cases be part of the equation when discussing the availability of test data? Because the motivation for this feature is the fact that, there are test cases that shouldn't be executed at same time.

I have opened this issue so we can specify how a property with nature NotInUse should be implemented. Please let me know your comments and suggestions regarding the best approach for implementing this feature. Thank you.

**Comment by vertigo17** [comment]
When the property return a list of values (should be the case for SQL at least - not sure about SOAP) and nature is notinuse, the value that will be used at the end should exclude the values that are already in use in past executions.
If no answers are avaliable after that exclution, execution should return FA.

1/We should store the list of possible answer (values) from property in memory (possibly by defining a parameter to limit the nb of occurences in case no limit criteria are defined in the SQL). We then need to retreive the properties from past execution by DAO from the Cerberus database with the exact same PROPERTY in the same COUNTRY and same ENVIRONMENT and datcre > today + parameter cerberus_notinuse_timeout. 
2/ We should not care on the nature and type of the past execution properties. Only COUNTRY, ENVIRONMENT, PROPERTY and timestamp of execution creation and STATUS <> PE. 
3/No the purpose is for example to test actions that impact session management on the same customer. This is needed accross testcases and could even be accross different applications.

Don't forget that feature is activated only when PROPERTY has NOTINUSE nature.
