### ISSUE TITLE
Filter results by Application

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#639]
Is it possible to add a checkbox filter to the 2Execution Report by Tag" list section to choose the application? 
For example, in this report with two applications http://192.168.134.35/Cerberus/ReportingExecutionByTag.jsp?Tag=WEB_THESEUS_ALL_UAT_2015112506 being possible to filter by "THES_RDT_MOB" and "THES_RDT"

Thank you!

**Comment by bcivel** [comment]
Done with #844.
You can now filters on several values in columns
