### ISSUE TITLE
BuildRevision 

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#640]
Cerberus Version : 1.1.3-SNAPSHOT

When trying to change build revision content, I'm not allowed to do it, with the following error:
![build_revision](https://cloud.githubusercontent.com/assets/5640464/11397109/d4664cd0-936e-11e5-8cbb-72681baf2ef9.jpg)

Has any configuration been done that voids this operation (that was possible last week)?

**Comment by gmoita** [comment]
I'll update the database directly, while this is not solved.

**Comment by vertigo17** [comment]
This is normal as when the build/revision has been deployed at least on an environment, it cannot be modified anymore.
This is to prevent that we modify the content of a release between 2 different deploy on 2 different environment.

**Comment by gmoita** [comment]
Hi.
I understand or point of view, but this was not the case, as there were no revision deployed anywhere.
Also, as we are working today with continuous integration with the development team, I'll have to find a way to workaround this.

**Comment by vertigo17** [comment]
At the time of the attempt of modification there were at least a deploy on QA for UF country.
The deploy has been done by it100001 the 2015-11-19 15:43:41.
The same revision was also deployed the 25th on all countries in UAT.

You can check the various deploy done on that particular case with : 
select * from countryenvparam_log where Build='CRM' and Revision='R06100';

The only workaround is to create a new revision on top of the existing one in case you want to modify it.

**Comment by gmoita** [comment]
Hi.
That is clear for me and I will check in the future, if I have any problem related to it.
Removing issue and mark it as question.
