### ISSUE TITLE
Refresh Page Test Coverage Per Application

### ISSUE THREAD

**Issue by pfoucrayredoute** [vertigo17/Cerberus#642]
Cerberus Version : 1.1.3-SNAPSHOT

Sur la page "192.168.134.35/Cerberus/TestPerApplication.jsp?Application=$$$NOM-APP$$$".

--> Si on change de "system" via dropdownlist droite header,
--> seules les "library" se rafraîchissent.

**Comment by pfoucrayredoute** [comment]
screen shot du bug ci-dessus
![refresh page test coverage per application](https://cloud.githubusercontent.com/assets/16115517/11527871/bac26ed8-98e3-11e5-84e5-3ca68fa46be1.png)

**Comment by corentindms** [comment]
This problem is related to the URL, when you click on an Application in the Homepage, the URL is set with the application name. If you clear the URL, it works fine.
It also works fine when you access the page from the menu.

**Comment by pfoucrayredoute** [comment]
Thx !
