### ISSUE TITLE
Refresh Page Execution reporting by tag

### ISSUE THREAD

**Issue by pfoucrayredoute** [vertigo17/Cerberus#643]
Cerberus Version : 1.1.3-SNAPSHOT

Sur la page "http://192.168.134.35/Cerberus/ReportingExecutionByTag.jsp?Tag=$$$NOM-TAG$$$"

--> Si on utilise les filtres par "status"
--> L'animation de "raffraîchissement" des données ne se termine jamais (curseur souris on mouse over area = loading... Cf Pj)
--> seul ce cas à été testé. Valable pour autres filtres ?

![refresh page execution reporting by tag](https://cloud.githubusercontent.com/assets/16115517/11527788/3370f4ea-98e3-11e5-8334-9eb7e0fad9f2.png)

**Comment by afnogueira** [comment]
@pfoucrayredoute This is solved in QA. After Cerberus deploy in PROD, you can confirm if it this issue is solved.

**Comment by bcivel** [comment]
Done
