### ISSUE TITLE
Increase Country field size

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#645]
Hi.

With the current process of dealing with several countries and several particular situations for the same country, we would like to define country codes with 5 char, instead of only 2 char.

What is the impact of this change?
Can it be done in a short term?

**Comment by vertigo17** [comment]
There is indeed quite a few table that have the country as a column.
The change is not very complex in terms of coding and the script to resize the tables quite independant from 1 table to another.
Only the main execution tables will take some time to be rebuild with new size but this is not the biggest.
Keep in mind that countries are used in columns on some report and in case we make it too big, it will take a lot of space (although 5 seems reasonable).
You can open the ticket and will try to make it until the end of the year.

**Comment by vertigo17** [comment]
Country can now go to 45 caracters. Please reopen if necessary.

**Comment by gmoita** [comment]
Working fine for my needs.
