### ISSUE TITLE
TCList - unsorted after refresh

### ISSUE THREAD

**Issue by pfoucrayredoute** [vertigo17/Cerberus#648]
Cerberus Version : 1.1.3-SNAPSHOT

After refreshing (f5) this page, I get lines several times, sorting order not respected...
need to reload the test to correct the mis-display

see screenshot
![tclist unsorted after refresh](https://cloud.githubusercontent.com/assets/16115517/11653294/75c1a768-9d9d-11e5-8548-0501b1ca7e76.png)

**Comment by bcivel** [comment]
@pfoucrayredoute . We could not reproduce the bug. Could you confirm it happen again?
Could you provide a scenario to reproduce?
Thanks

**Comment by pfoucrayredoute** [comment]
Indeed, I can't make it happen again.
I'll let you know next time if this shows up and give more details.

Thx for checking
