### ISSUE TITLE
It's no more possible to use calculateProperty with object only

### ISSUE THREAD

**Issue by bcivel** [vertigo17/Cerberus#649]
Target behavior is to have the following implementation : 
{"action":"calculateProperty", "object":"%TOTO%", "property":null}

That does not work anymore as we raise the following messageEvent
MessageEventEnum.PROPERTY_FAILED_UNKNOWNPROPERTY

**Comment by vertigo17** [comment]
Considering that the action is calculateproperty, i would expect to put TOTO (a property name) in value and not %TOTO% (that in fact should be replaced by the value of TOTO before being used by the action ie : calculateproperty).

**Comment by bcivel** [comment]
Agreed
