### ISSUE TITLE
Test Cases / Step Libraries / Titles not synced

### ISSUE THREAD

**Issue by pfoucray** [vertigo17/Cerberus#660]
Cerberus Version : 1.1.3-SNAPSHOT

When you use an existing step library for a test case.
If you change the title of the library (from source of course), the title of synced steps won't update.

You can further notice that you can't edit any action / Control in the "attached children's", but you can edit their title independantly.

Don't know if it's a bug or if it's wanted (can be usefull in some cases ?)

Thing is you have to update "manualy" the title everywhere if you upgrade you librarie's title !

Thx,
Keep up the good work :)

**Comment by bcivel** [comment]
It was a feature and not a bug as this is possible to use the step with different property, it can be useful to modify the description of a step.
