### ISSUE TITLE
Release name on build revision content not enough

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#662]
Cerberus Version : 1.1.3-SNAPSHOT

With the upgrade of the application name to 200 characters, development team is creating releases with the same name as the application, followed by 7 digits.
To accomplish that, I would like that is is also possible to input more 200 characters on the release name.

**Comment by vertigo17** [comment]
This is an easy change that can be done but the notifications will become really ugly if we start to put 200 caracters release name on 200 caracters applications.
Are you sure this is a good idea ?

**Comment by gmoita** [comment]
I understand your point of view.
The only issue is that release naming is really becoming big, as application was set to 200 char.
Can it be set as someting like 100 and we ser how the communication is sent?

**Comment by vertigo17** [comment]
I also increase the release size to 200 char but would advice that you put only the 7 digit on the release field.
