### ISSUE TITLE
Add column 'repositoryUrl' in the buildrevisionparameter table

### ISSUE THREAD

**Issue by bcivel** [vertigo17/Cerberus#664]
In order to retrieve some package that are no more in jenkins, we'd like to retrieve them directly from a repository (nexus for example).
The topic is to add a column repositoryUrl, that can be fed by Jenkins when package is pushed in nexus (calling the servlet NewRelease).
When deploying application from cerberus, it should call Jenkins passing through this parameter.

**Comment by cjmachado** [comment]
+1.

Don't forget (you probably already know) that Nexus has the "Releases" and the "Snapshots" repositories, so both Cerberus/Jenkins must be aware of this info, for each build.

Thanks!

**Comment by bcivel** [comment]
Done
