### ISSUE TITLE
Control "verifyRegexInElement" : Status after execution PE --> KO

### ISSUE THREAD

**Issue by pfoucray** [vertigo17/Cerberus#665]
Cerberus Version : 1.1.3-SNAPSHOT

When Element not found, Cerberus just doesn't end the control, so TC goes to PE.
Woudl be nice to get KO, so that we choose Fatal Y/N and TC can end.

Cheers,
PF

**Comment by bcivel** [comment]
I add a check to ensure the element is found before controling the regex.
It solve the issue

**Comment by pfoucray** [comment]
Yeah nice ! cheers !
