### ISSUE TITLE
Increase test name capacity

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#667]
Cerberus Version : 1.1.3-SNAPSHOT

After the changes to the application name length, users are requesting to create tests with the application name and the page or the service, as already existed.
To do that, test column needs to support more characters than today (like 200).
Please consider this request and confirm if possible to do it and the impact.
For sure, database changes will be big.

**Comment by bcivel** [comment]
Maybe I can advise you to find another naming convention.
It's not a good idea to extend this field in all tables, and we should target to be more concise on this field (and you can be verbose on the test description).
If you agree with that, I let you close this issue and maybe open a new one with the page where you want to see the test description.

**Comment by gmoita** [comment]
Hi.
Architects have defined a large name for the application names and the development rules state that the test name should have the application name and the page name.
It is not possible to ensure that final part of the application name is unique.
If it is not possible to have this, then I'll have to find a workaround that could not be easily manageable.

**Comment by vertigo17** [comment]
You can still put the application name + page name inside the description.
Then, you let Cerberus propose the increment on testcase field.
This way, the day where you decide to change the convention, there no impact on database, Just a simple description update on the corresponding testcase.
