### ISSUE TITLE
Missing Environment / Not loading in TC execution

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#668]
When executing a test case the dropdown with **Environment **is empty or not fully loaded.
Example empty dropdown: http://192.168.134.35/CerberusRegression/RunTests.jsp?Test=PAGE%20VCItemMgt%20ColorDictionary&TestCase=0001A&MySystem=&Country=IT&Environment=UAT&browser=firefox&Tag=VCGUI16_R06_UAT_2016020418

**Comment by bcivel** [comment]
Hello.
I found the issue but there is a bit of work to correct.
If urgent, temporarly, you could set maintenancestr and maintenanceend (in countryenvparam) to 00:00:00, it will solve your problem.
I'll correct it ASAP.

**Comment by gmoita** [comment]
I've tested the temporary solution and we are able to execute the test cases.
Waiting for the final solution.

**Comment by bcivel** [comment]
corrected
