### ISSUE TITLE
messing up parameters when creating multiple campaign

### ISSUE THREAD

**Issue by NotoriousBig** [vertigo17/Cerberus#671]
Hello, 

Parameters are messing up when creating campaigns one after the other. I even could register a browser named 'DEV'. Check picture below :

![test campaign - mozilla firefox](https://cloud.githubusercontent.com/assets/13114629/13149898/9b5805ea-d663-11e5-816d-a834523d02e2.jpg)

**Comment by vertigo17** [comment]
We will fix that with #699
