### ISSUE TITLE
Add a column in the current preview report

### ISSUE THREAD

**Issue by MichaelWil** [vertigo17/Cerberus#672]
Hi,

Currently, and in a sustainable manner, we have some tests that are present in preview while they can't be ran in preprod (mainly linked to the payment).
The idea of this issue is to be able (in the preview report) to clearly identify the tests that won't be ran in preprod to be able to give this information to Cstech to underline the fact that if this bug is present in preprod we won't be able to detect it.
THe mean to acheive this target is to add a column in which the information related to the field "Priority" of each tc is displayed.
This field could be displayed between "Application" and the first column with the result.
Like the other element i'd like to be able to sort this field.

For the moment this field will have to status :
1- empty : no particular is givento this test
2- "0" : this tests isn't present in preprod.

If it's not completely clear, feel free to come back to me.

Thanks

**Comment by gmoita** [comment]
Hi.
I would give a different suggestion, which would only need to show values already present on the database.
Why not use the information related to ActiveQA, ActiveUAT and ActiveProd?
In this case, if the test case is set to ActiveUAT and not ActiveProd it will run on Preview and not on PreProd.
In this case, showing the information from the test case is enough?

**Comment by MichaelWil** [comment]
Hi Guilherme,

THanks for your suggestion. Maybe my request wasn't clear enough but the final aim is to be able to identify the tests that are only running in preview. So no matter of the indicator you choose to display.
But if you choose to display the notion of "Active" you'll have to display the 2 informations "ActiveUAT" + "ActiveProd" and to compare them to see which are run in one and not in another.
Am i right ?
Beside that i don't know the difference you make between displaying the information you refer to and the one i talked while there are all on the same line in the "Test Information" of each test.
But maybe i misunderstood what you said.

**Comment by gmoita** [comment]
For me, I believe that if we just display the info from the database it would be easier to show, without having to calculate anything, but for me it is transparent...

**Comment by MichaelWil** [comment]
Hi,
For no matter where the information comes from or what precise field is displayed my only need is to beeing able to identify clearly in the preview report the tests that are only ran in preview.
Can you handle with that ?
If yes when do you think it can be done ?

Thanks a lot !
