### ISSUE TITLE
FA step without FA Action/Control

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#678]
There are some test cases displays FA steps missing the FA Acton or Control. 
For example in http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=29749667 the Step5 is FA but the control 4-1 is not displayed:

![nofacontrol](https://cloud.githubusercontent.com/assets/1914659/13495177/16065746-e141-11e5-82a3-09eb4a29c85a.jpg)

**Comment by ruirpr** [comment]
Another critical example, the user dont know where the NA is: 
![nofacontrol_1](https://cloud.githubusercontent.com/assets/1914659/13502133/9f1bbb00-e161-11e5-96a4-da7208438f10.jpg)

**Comment by ruirpr** [comment]
This needs to be fixed ASAP.

**Comment by vertigo17** [comment]
Can you check if you can still reproduce. If you can, please provide the reference of the testcase.

**Comment by ruirpr** [comment]
It seems that this issue is no longer present. Will be reopened if needed. Thanks!
