### ISSUE TITLE
Test result OK with KO control

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#679]
Noticed that this execution result is OK having a control KO result:
http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=29754179

![screen shot 2016-03-03 at 17 13 12](https://cloud.githubusercontent.com/assets/1914659/13502555/5ba18d80-e163-11e5-84b1-1adeb59b40e1.png)

**Comment by vertigo17** [comment]
It seems that the testcase has been modified in order to solve the issue.
Can you duplicate the test and give us the id so that we can reproduce the issue systemically ?

**Comment by ruirpr** [comment]
Duplicated but no longer can replicate the issue: 
http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=30410192
