### ISSUE TITLE
TestCaseStepExecutionDAO - Unable to execute query

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#680]
Cerberus Version : 1.1.4-SNAPSHOT

After the last deploy, we are getting several messages on the server logs with:
[#|2016-03-05T00:49:22.888+0100|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=2742;_ThreadName=httpSSLWorkerThread-38093-7;|2016-03-05 00:49:22 ERROR TestCaseStepExecutionDAO:40 - Unable to execute query : java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp

Don't know if it is related to issue #676

**Comment by vertigo17** [comment]
duplicate from #684
@gmoita until we fix it there is a workaround on #684.
