### ISSUE TITLE
Impossible to create new account

### ISSUE THREAD

**Issue by MichaelWil** [vertigo17/Cerberus#685]
Hi,

When i create a new account the "Add new user" is displayed. I filled in all values required.
When i validate the layer disapear without any message.

When i try to do a research using the search engine typing the name i just used in the layer, i get a "processing" message which stay displayed while i get the message "No matching records found".

And finally when i try to make a manual research displaying all open accounts i can't find it.

So it seems it wasn't created at all.

Can you please check and come back to me when it's fixed telling when the next update is planned ?

Thanks and regards.

Michael

**Comment by bcivel** [comment]
After investigation, we are able to create account.
Looks like coming from an instability.
