### ISSUE TITLE
The waitForPage action does not exist

### ISSUE THREAD

**Issue by abourdon** [vertigo17/Cerberus#687]
Although present in the action combolist, the waitForPage action does not exist as we can see bellow:

<img width="920" alt="capture d ecran 2016-03-15 a 22 06 27" src="https://cloud.githubusercontent.com/assets/1511715/13794088/737d4534-eafa-11e5-9929-133362da0b21.png">

**Comment by vertigo17** [comment]
I checked all Actions and we have the same issue with 
store
removeSelection
waitForPage

I will clean the actions from the GUI to avoid confusion.

**Comment by vertigo17** [comment]
Should be fixed now. I removed acces to the action. It was not used as we usually wait for a field using wait action.
