### ISSUE TITLE
Hide/Show Mobile keyboard

### ISSUE THREAD

**Issue by ffazendeiro** [vertigo17/Cerberus#706]
After inserting a text on a TextBox on mobile Applications often the keybord stays visible and it is not possible to click/select any element that is behind. 
Would it be possible to implement an action that would hide/shown the device keyboard?

**Comment by abourdon** [comment]
The _hideKeyboard_ action has been added to Cerberus to hide keyboard but beware, this action is **only available on APK applications** (Android devices). Indeed, Appium is not ready yet to correctly handle this action on IPA applications (IOS devices).
We will be able to set it up as soon as a next Appium version supports it.

**Comment by abourdon** [comment]
The _hideKeyboard_ action is now compatible with IOS devices by clicking on the _return_ button instead of tapping outside keyboard as we can do with Android decices
