### ISSUE TITLE
java NullPointerException when application does not exist

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#714]
When using NewRelease servlet, if the application on the URL does not exist on the database, error java NullPointerException is shown.
Previously it showed "Error - Application does not exist  : " plus the application name
Although it is not critical, it is a regression and we don't know the real cause of the problem.

**Comment by gmoita** [comment]
I've just inserted new releases using NewRelease and I've got message "Warning - Release entry already exist. Updating the existing entry".
However, I'm pretty sure (and someone seen it also) that the release does not existed before.
I've deleted the entries, verified no data on the database related to the release and repeated the operation; result is the same.

**Comment by vertigo17** [comment]
This is a similar issue than yesterday.
I will fix this.
