### ISSUE TITLE
Implement KeyPress for Mobile App

### ISSUE THREAD

**Issue by ffazendeiro** [vertigo17/Cerberus#718]
It would be very useful to have the keypress action available for Mobile applications (Android, IOS).
This keypress (Enter, Back key, Search key) could be implementing using the keyboard device or use the action on an element.

**Comment by abourdon** [comment]
Hi,

Is that your request is to be able to type something on input texts thanks to keyboard? If yes, you already can do this one by using the click & type actions. If not, could you please be more concrete on your need? What do you want to do exactly? 

Regards,
Aurélien

**Comment by ffazendeiro** [comment]
Hi,
The main goal of this improvement was to be able to click/select special keys on the keyboards.
The click & type actions allows us to write on text box but the "Keypress" action is not available for APK and we need to use it to implement some tests.
The more important are the "Enter" and the "Search" (available on search elements) keys on the keyboard.
![android_keyboard](https://cloud.githubusercontent.com/assets/17747042/14792513/7b4eedac-0b12-11e6-8d0b-2466b2cc85e4.png)

Thanks.
Best Regards.

**Comment by abourdon** [comment]
Hi,

Thanks for your explanation ;-)

You can now use the _keyPress_ action by giving either _ENTER_ or _SEARCH_ action's object in order to tap on the associated keyboard keys.

Let me know if this enhancement is compatible with your devices.

Regards,
Aurélien
