### ISSUE TITLE
Not able to request deploys to multiple servers anymore

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#724]
Cerberus Version : 1.1.4-SNAPSHOT

Since the last deploy, we are not able anymore of submitting requests to multiple servers.
Server (Jenkins Agent) shown is always the same.
This is voiding us from using the fast process from Cerberus to Jenkins requests to automate the deploy.
This is critical.
![deploy_not_possible](https://cloud.githubusercontent.com/assets/5640464/14591862/462cc08e-0510-11e6-87ca-f79941209a20.jpg)

**Comment by vertigo17** [comment]
Did you check the configuration of the deploytype of the corresponding env ?
What do you expect to see on that particular exempla ?
