### ISSUE TITLE
doNothing doesn't work.

### ISSUE THREAD

**Issue by bcivel** [vertigo17/Cerberus#725]

**Comment by bcivel** [comment]
![donothing](https://cloud.githubusercontent.com/assets/5376184/14596478/100d5bb2-0547-11e6-83d8-6d64f934e492.png)

**Comment by vertigo17** [comment]
Be carefull as Guilherme did a rollback.
I suppose we deployed database change but we still have the old application.
Fix should be to redeploy the new version.

**Comment by abourdon** [comment]
I agree it works with my local version.
