### ISSUE TITLE
NewChain is available for all systems-environments-countries

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#726]
Cerberus Version : 1.1.4-SNAPSHOT

When trying to send information related to NewChain, all systems-environments-countries are available for selection, which is a regression.
Previously there was a restriction where only the countryenvparam data with `Chain` <> 'N' where possible to use.
This is still needed.
![newchain available for all systems-environments-countries that are active](https://cloud.githubusercontent.com/assets/5640464/14601475/079dc33c-055a-11e6-8bf1-47e506dd4efc.jpg)

**Comment by vertigo17** [comment]
OK, I will 
-add the possibility to put Y or N into the column on the adhoc screen (tab Chain in edit button)
-the NC button will be displayed only when chain =Y and env is active.
