### ISSUE TITLE
NewRevision deploy request is missing information

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#727]
Cerberus Version : 1.1.4-SNAPSHOT

Current version of Cerberus is missing information on the deploy instructions.
As can be seen, revision content is filled with 7 different applications to be deployed.
![newrevision_content](https://cloud.githubusercontent.com/assets/5640464/14636526/e7dec242-0623-11e6-8f57-b7fb87ceac7a.jpg)

However, when we select the Installation instructions to deploy, only 4 applications are available (as seen below).
![newrevision_instructions](https://cloud.githubusercontent.com/assets/5640464/14636576/2c79c064-0624-11e6-824e-62c3b2b56877.jpg)

This is critical now.

Can you also change the layout (even later) to accomodate the complete name of the application?
It can be by the increase of the height of the box of the application name (just a suggestion).

**Comment by vertigo17** [comment]
for system : vendororderlifecycle, country : BE, environment : PROD, the deploytype SERVICE has no JenkinAgent.
If you add it it will temporary fix the issue.

On top of that I will have to fix a GUI issue as it do not support that one JenkinsAgent is not defined.

**Comment by gmoita** [comment]
Hi.
Strange, as I really thought it was all well configured.
Added already and it is working.
If you can still show the applications even without the JenkinsAgent it would be very good (back to previous way of working, and we can configure any missing data).

**Comment by vertigo17** [comment]
I already comit the change and you can check in QA.
I pointing the comit to the wrong ticket but it is there -> 3644db13a59be49b2da3c27a4b65120772cf76ca
