### ISSUE TITLE
Not able to deploy a in a new country/environment

### ISSUE THREAD

**Issue by NotoriousBig** [vertigo17/Cerberus#733]
Hello, 

I'm not able to deploy in a build/revision on a brand new country/country env.
This only appens when the country/environment is empty and don't already have a build/revision 
The 'installation instruction' tab is empty also and I can't deploy anything.

![environment - mozilla firefox](https://cloud.githubusercontent.com/assets/13114629/14715700/1199ce3e-07ea-11e6-8e58-775c178d8be6.jpg)

Séb

**Comment by vertigo17** [comment]
Clear.
I fix this one.
