### ISSUE TITLE
SOAP message in execution result / Enhancement

### ISSUE THREAD

**Issue by R-Loic** [vertigo17/Cerberus#734]
Hello,
For test cases using SOAP message it would be interesting to see the SOAP message sent in the Execution result. Today, there is only the SOAP response and not the request. (For debugging purposes)
Thanks

Cerberus Version : 1.1.4-SNAPSHOT

**Comment by vertigo17** [comment]
Can you please confirm when there is a need to get the full trace.
That can be a lot of data to save so I would like to have a particular case where this is require.
Is that when getting a property (calculateProperty) of when performing a callSOAP Action ?

**Comment by R-Loic** [comment]
As we said, it would be interesting to get request only when performing a callSOAP.

**Comment by bcivel** [comment]
Done
