### ISSUE TITLE
Random in Testdatalib result

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#736]
It seems that random in testdatalib results its not working properly and selects allways the same result.

**Comment by vertigo17** [comment]
Can you provide more information as I tested it on my side and found not issue.
What is the type of testdatalib you use ?
What testcase for which execution ?

**Comment by gmoita** [comment]
Hi.
Problem is with TestCase.jsp page.
When we change the property to RANDOM, it is saved on the database as RANDOM but always shown as STATIC when the test case is loaded.
