### ISSUE TITLE
Desyncronisation Use-Step / Library

### ISSUE THREAD

**Issue by pfoucray** [vertigo17/Cerberus#741]
Cerberus Version : 1.1.4-SNAPSHOT

Hi,
When you have a TC with several steps as libraries. If you add a new step before one of them that is a library, you are lucky if it doesn't ruins all the Use-Steps in your other TC.

It appears that the library, formerly, say, step n°5, becoming step n°6 in the original TC won't be properly linked to the usesteps, that still refer to step n°5...
Or something like that !

Cheers,
PF

**Comment by bcivel** [comment]
Duplication #644
