### ISSUE TITLE
Timeout not taken into account in some Cerberus actions

### ISSUE THREAD

**Issue by MichaelWil** [vertigo17/Cerberus#745]
Hi,

For some tests mainly for BE website, it happens that the load of the hp is very long.
If you take a look to that execution (http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=31690654), you'll see that the load of the hp last 1:37.
It is a bug as a timeout is supposed to be taken into account when an action last more than 45 sec.

Can you please fix that and change the BE timeout only to lower it to 15 or 20 sec.

Thanks

**Comment by vertigo17** [comment]
Timeout is set either :
At execution level (in the run page)
At system level (for all THESEUS Application)
At global level.

Can you test that when specifying at execution level it still do not work ?
This ticket is linked with #651
