### ISSUE TITLE
Move service engine dedicated classes to a more relevant package

### ISSUE THREAD

**Issue by abourdon** [vertigo17/Cerberus#746]
Thanks to #705, the new `org.cerberus.service.engine.model` has been created to gather model classes used by the service engine internal process.

Hereafter a list of classes/packages that could be moved to this new package::
- [ ] `org.cerberus.util.answer.Answer`
- [ ] `org.cerberus.util.answer.AnswerItem`
- [ ] `org.cerberus.util.answer.AnswerList`
- [ ] `org.cerberus.service.engine.impl.diff`
- [ ] `org.cerberus.service.engine.impl.input`

Do not hesitate to fill this list if there are additional classes/packages that could be moved to the package.

**Comment by bcivel** [comment]
Hello Aurélien,
These entities are not dedicated to the engine.
Could we think to create a package org.cerberus.model instead?

**Comment by abourdon** [comment]
Hi Benoit,

Yes sure. In that case we could go further and try to gather all of our model classes which are contained into several packages as:
- `org.cerberus.crud.entity`, then we could have `org.cerberus.model.entity`
- `org.cerberus.dto`, then we could have `org.cerberus.model.dto`
- `org.cerberus.enums`, then we could have `org.cerberus.model.enums`
- `org.cerberus.service.engine.model`, then we could have `org.cerberus.model.engine`
- ... maybe more
 
What do you think about that?

**Comment by bcivel** [comment]
I am thinking something like
- `org.cerberus.model.entity`
- `org.cerberus.model.dto`
- `org.cerberus.model.dto.impl`
- `org.cerberus.model.service`
- `org.cerberus.model.service.impl`
- `org.cerberus.model.factory`
- `org.cerberus.model.factory.impl`

Not sure about the following ones :
- `org.cerberus.enums`  >> for me could stay like that, or deplaced into  `org.cerberus.model.entity` ...not really sure.
- `org.cerberus.model.engine` >> Not sure this level is useful for the moment...Maybe if the `org.cerberus.model.entity` contains too many classes and need to be splited only.

**Comment by bcivel** [comment]
Done in a previous commit a5b88515ab19bf1ee4d13c22e47489633b293a4c
