### ISSUE TITLE
error when saving system in test data library

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#749]
"An unexpected problem occurred. Unable to execute Update operation(s)!"
when trying to save System in Test Data Library Entry.

How to reproduce: 
enter test data library and search for C_WEB;
edit and choose Theseus for system;
check if saved;

**Comment by vertigo17** [comment]
I check on my side and not able to reproduce.
I did Open Cerberus prod,
Filtered in c_web and edit the entry 1318
Changed the system to BI and click on save, close the modal and confirm the update.
The screen is refresh with the new value with no problem.
![selection_056](https://cloud.githubusercontent.com/assets/5342048/14959835/a20daa4e-1091-11e6-9fe1-b4cf9eae9c0d.jpg)

**Comment by ruirpr** [comment]
Tried again a few moments later and was able to save properly. So, maybe was a network issue. So, will close this issue for now. Thanks!
