### ISSUE TITLE
Unable to launch Tests for APK type

### ISSUE THREAD

**Issue by j0hnsa** [vertigo17/Cerberus#754]
Hello,

With this most recently deployed version of cerberus, we are currently unable to launch apk tests.
Scenario:

Aplication launches but exception is given and tc fails (see attachment)
![git](https://cloud.githubusercontent.com/assets/16339891/15109534/b6763cac-15d3-11e6-8f56-845c20b2bf58.png)

**Comment by abourdon** [comment]
A quick fix has been developed to let Cerberus launch mobile tests (APK & IPA). This fix needs to be rethought when the next Appium version will be deployed (see #757)
