### ISSUE TITLE
Optional Contrôl / action

### ISSUE THREAD

**Issue by pfoucray** [vertigo17/Cerberus#756]
Cerberus Version : 1.1.4-SNAPSHOT

New Feature //
Would great if it was possible, inside a step of a TC to get a check box making next to every step / action /contrôle to "disable" it temporarily.

--> When you haven't completly implemented a TC but you want still to run it, with some actions / Controls to come, but not ready yet.
So far we can put "do nothing" to action and fatality to N to Contrôle but why not make same with a lil' handy feature, and avoid the "wrong KO" ? ;)

--> When you know there's a bug waiting to be fixed, that prevents you to go further in your testcase's contrôls.
Ex : you check page 1, an element containing a value you need for a contrôle in this page is missing, you'll get a fail (element not found) on the action. while you still want to contôle page 2.

Well you got the picture :)
Keep up the nice work,
Ty
pf

**Comment by bcivel** [comment]
I implemented new action "skipAction" that allow to don't execute action nor linked control (the controlType are overriden into skipControl during the execution).
That's a bit different than what you propose but it allow to fix the problem you have.

<img width="978" alt="capture d ecran 2016-06-10 a 23 40 19" src="https://cloud.githubusercontent.com/assets/5376184/15979518/b36d0a40-2f64-11e6-8d01-70cfc0761479.png">

**Comment by pfoucray** [comment]
nice. this makes the job !

cheers ;)
