### ISSUE TITLE
Expose application configuration

### ISSUE THREAD

**Issue by NotoriousBig** [vertigo17/Cerberus#759]
Hello, 

Today we use Cerberus to trigger jenkins for application deployements. So Cerberus can give some configuration to Jenkins : 'deploy-type', 'environment', 'Jenkins agent'. 
As far as deployement in early env (dev) are not triggered from Cerberus (autodeploy managed in Jenkins), Jenkins have to have the dev configuration. 

We have a specific job to deploy in dev with configuration embeded and normal deploy job with configuration from Cerberus. 

Can you please provide the config 'deploy-type', 'environment', 'Jenkins agent' so Jenkins can request Cerberus on every deploys ?

Sébastien

**Comment by vertigo17** [comment]
Not really clear on what is expected.
Can you be more specific ?
We probably need to discuss on that so I better understand.

**Comment by vertigo17** [comment]
With no feedback, I close the issue.
Open it again when we are clear on the data / format to publish.
