### ISSUE TITLE
Unable to Launch tests for android on CerberusQA

### ISSUE THREAD

**Issue by j0hnsa** [vertigo17/Cerberus#766]
When Lauching a test from CerberusQA tc fails immediately with message:
Oops...
Sorry but an unexpected error occurred.
Error Code : 500

**Comment by abourdon** [comment]
Please check the Appium server status or restart it and try again. Do you have the same behavior?

**Comment by j0hnsa** [comment]
Hello,

Today I was able to launch a couple of tests without problem but now we face the same issue.. Tried to launch again by rebooting my pc, appium, mobile device and by changing the network adapter in use (eth and wlan) without success.. See below the replicated error:
[cerberusqa.zip](https://github.com/vertigo17/Cerberus/files/266473/cerberusqa.zip)

**Comment by abourdon** [comment]
Hi,

I'm able to launch tests without any errors... Could you give me Appium server logs?

Regards,
Aurélien

**Comment by j0hnsa** [comment]
Appium didn't generate any logs on this case, error 500 was shown before any test started... Today we will run a couple of tests in QA and will provide feedback on this issue.. Thanks

**Comment by abourdon** [comment]
Ok. If you could have some Cerberus server logs it would be great. Thanks

**Comment by bcivel** [comment]
@j0hnsa 
Is the error still present? Could you provide more detail or close if it's solve on your side?
Thanks

**Comment by j0hnsa** [comment]
Hello Benoit, this issue is solved. Thanks for the help.
