### ISSUE TITLE
FA / Action TimeOut while action did work

### ISSUE THREAD

**Issue by pfoucray** [vertigo17/Cerberus#769]
Cerberus Version : 1.1.4-SNAPSHOT

Happens to me sometimes, that exectution stops with a fail. Cerberus indicating : "Timeout exceeded when performing the action : 30 seconds"

While The screenshot taken on the fail proves the action did work
(ie : you click on a link to go to some other webpage. Screenshot shows the other page loaded, cerberus indicates that selenium did non click on the button)

Some othertimes, it gives a KO, because page did not load at all. Which is normal behaviour...

FYI : I'm working on very slow website.

Regards,
PF

**Comment by bcivel** [comment]
Hi @pfoucray,

The behavior is when you use the click action, Cerberus will ask selenium to click, and selenium will click and wait for page to load. When the timeout is reached, Cerberus stop and inform that "Timeout exceeded when performing the action : xx seconds".

In your cases, the pages probably never been fully loaded, even if in the screenshot, page seemed to be loaded.
