### ISSUE TITLE
The RunCI servlet sends KO when all tests are OK

### ISSUE THREAD

**Issue by abourdon** [vertigo17/Cerberus#772]
When executing a test case suite with all OK, then the RunCI sends KO.

Indeed, by reading the RunCI servlet, from line 124 (https://github.com/vertigo17/Cerberus/blob/master/source/src/main/java/org/cerberus/servlet/zzpublic/ResultCI.java#L194):

     float resultCal = (nbkop1 * pond1) + (nbkop2 * pond2) + (nbkop3 * pond3) + (nbkop4 * pond4);
     if ((resultCal < 1) && (nbkop1 + nbkop2 + nbkop3 + nbkop4 > 0)) {
          result = "OK";
     } else {
          result = "KO";
     }

We can see that the RunCI servlet waits for at least 1 KO to say OK when the final result is OK.

I would like to remove this behavior, then by deleting the `(nbkop1 + nbkop2 + nbkop3 + nbkop4 > 0)` statement, but I’m wondering why we need it actually? By deleting this statement, then the previous code would be:

     float resultCal = (nbkop1 * pond1) + (nbkop2 * pond2) + (nbkop3 * pond3) + (nbkop4 * pond4);
     String result = resultCal < 1 ? "OK" : "KO";

In addition,

Documentation says if no execution is found for a given tag, then KO is returned. I’m wondering if this behavior is correct. Indeed, if no test is executed, then no error can be found, and then global result seems OK, as other test frameworks do.
Furthermore, current code does not let final result be KO if no execution is found. A possible correction would be:

     float resultCal = (nbkop1 * pond1) + (nbkop2 * pond2) + (nbkop3 * pond3) + (nbkop4 * pond4);
     String result = resultCal < 1 && resultCal > 0 ? "OK" : "KO";

I’m waiting for your feedbacks,
Aurélien

**Comment by vertigo17** [comment]
Just a precision : nbkop1 in fact has nb of execution that are not OK. It includes FA, NA, PE and KO.

For me we can remove the (nbkop1 + nbkop2 + nbkop3 + nbkop4 > 0) rule. You are right, it does not make sense.
A better rule would be to add a control on total nb of execution > 0 but that is missing in the servlet. I think though a DAO method exist on that.

The reason for that additional rule would be to secure that CI do not trigger deploy if the tests on the previous environment were in fact not executed.
For me we should not deploy to the next step if no test has been executed so although not mandatory the additional control would be nice to add.

**Comment by abourdon** [comment]
So `(nbkop1 + nbkop2 + nbkop3 + nbkop4 > 0)` has been removed.

However, I think it would be more conventional to follow other test frameworks when dealing with empty test and say OK when nothing is tested.
At this point, this is the default behavior when Cerberus is running an empty test (with no action or control). Then the result is OK. Otherwise, we would also return KO for an empty test.

Let me know if you agree, then we could remove the FIXME comment and close the issue.

Regards

**Comment by vitoo** [comment]
Hi @abourdon , @vertigo17 
The result CI send OK if the tag doesnt exist

**Comment by vertigo17** [comment]
Let's improve new servlet V001 in json format.
On that one, in case tag doesn't exist, it report an error leaving the result data undefined.
