### ISSUE TITLE
Test execution detail disordered

### ISSUE THREAD

**Issue by mbessa** [vertigo17/Cerberus#774]
This test fail and apparently continues to run, but after a closer look at the timestamps, there is some issue with the execution order in the page.

http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=32466313

**Comment by vertigo17** [comment]
Just to be more specific.
The Pre Testing execution appear after main step. Probably the steps are not sorted by timestamp when it should be.

![selection_073](https://cloud.githubusercontent.com/assets/5342048/15429655/414d416e-1ea2-11e6-83a7-d7b96d0f5b59.jpg)
