### ISSUE TITLE
Unable to get Sub-data value

### ISSUE THREAD

**Issue by ffazendeiro** [vertigo17/Cerberus#775]
The test case cannot obtain any sub-data from an SQL query in Data Library.
For example:
Property PRODUCT is calculated by a getFromDataLib_BETA: P_PA_RDT_AVL_SIZEAVL
And have the following sub-data:
![image](https://cloud.githubusercontent.com/assets/17747042/15431659/c87407a4-1ea2-11e6-910b-37bac7ac2b35.png)
When using the property %PRODUCT(Size)% the test cases immediately stays with status PE and stops executing .

**Comment by vertigo17** [comment]
Can you provide the execution ID ?

**Comment by ffazendeiro** [comment]
Execution: http://192.168.134.197/CerberusQA/ExecutionDetail.jsp?id_tc=32251196
Note that this tests uses a static Data Library for the Login (it is OK) and a SQL Query for the Product (not working). 
Let me know if you need more information.

**Comment by vertigo17** [comment]
Did you try with %PRODUCT(SIZE)% in stead of %PRODUCT(Size)%.
With the new version you have now in the message of the calculation of property the list of subdata calculated :

![selection_074](https://cloud.githubusercontent.com/assets/5342048/15432798/fe13d4ea-1eaf-11e6-9382-a2be7caa563a.jpg)

 {=324493887, COLOR=Bleu moyen, SIZE=38/40}

**Comment by ffazendeiro** [comment]
Hi
you are correct. Did some tests and the issue seem related to the uppercase.
In the previous version, the result data was not shown at the end of the SQL result so we have some sub-data with lower case and it was working properly. Now it seem that all sub-data must be uppercase.
Sorry for any inconvinience.

**Comment by gmoita** [comment]
One question: is it suppose to be, from now on, in UPPERCASE?
Should we update all the SUB-data names to Uppercase or do you intend to revert to a "case-sensitive" approach?
If it is intended to be always in UPPERCASE, then the issue can be closed and we will update data.

**Comment by vertigo17** [comment]
No problem Filipe and this is still a real issue as Cerberus should report that it does not find the subdata. I will fix that.

Anyway the subdata do not need to be upercase, in fact it is case sensitive.

**Comment by vertigo17** [comment]
Checked at the code and finally it is forced to uppercase for the time beeing but I will change that in order to make it case sensitive.

**Comment by gmoita** [comment]
Ok for the time being.
As long as we understand how we need to do things and as long as it is reasonable, we can do it.
We can always update the data names with uppercase, so no major issue, as we will be able to use it.

**Comment by abourdon** [comment]
Hi, 

Some other users are faced to the same issue and it could be great to fix it from the next release.

So, there is an uppercase transformation when getting testdatalib's name value from a SQL request. And then user has to define its testdatalib's name in uppercase also (stop me if I'm wrong)?

@vertigo17 you said testdatalib's names are case sensitives. What do you think to make them case **in**sensitves? Then SQL retrieving would be the same as currently by continuing to use uppercase transformation, and user could not be forced to strictly use the same testdatalib's name. But to be compliant with other data retrieval (SOAP, ...) we have to use the same behavior and make testdatalib's name case insensitives.

Let me know if I'm missing something.

Aurélien

**Comment by abourdon** [comment]
Ok so, according to what we said with @vertigo17, testdatalib's names will be case **sensitive**. Then, "foo" will be different than "Foo". And finally, if a SQL column name is equal to "foo", then testdatalib's name must be equal to "foo" to retrieve its value.
