### ISSUE TITLE
callSoapWithBase_BETA not working

### ISSUE THREAD

**Issue by ffazendeiro** [vertigo17/Cerberus#776]
The new action callSoapWithBase_BETA dosen't seem to be working. The SOAP base is not being build to get the complete URL to use (see log file in attachment).
We test the callSoapWithBase_BETA with the complete "Service Path" and it works. But it would make more sense to have only the relative path. 
Example of an execution: http://192.168.134.35/CerberusQA/ExecutionDetail.jsp?id_tc=32250859
Log error: [LOG.txt](https://github.com/vertigo17/Cerberus/files/275024/LOG.txt)

**Comment by vertigo17** [comment]
callSoapWithBase_BETA has been removed.
We will keep the existing callSoapWithBase pointing to SOAP Library.
