### ISSUE TITLE
Refactor GUI : page Invariant (Public & Private)

### ISSUE THREAD

**Issue by vertigo17** [vertigo17/Cerberus#791]

**Comment by Foudro** [comment]
I'm was wondering,

should we merge the two Invariants pages to have only one, and have something like this : 

![image](https://cloud.githubusercontent.com/assets/9056969/17999957/0d6bacb0-6b7c-11e6-9dc9-f01d798a8a5a.png)

Or should we keep the two pages?

**Comment by vertigo17** [comment]
Yes you can merge
This is a good idea.

**Comment by Foudro** [comment]
I pushed my first try, 
it is accessible via 
http://localhost:8080/Cerberus/Invariant.jsp

And I fixed one thing about the Tables, we wasn't able to make two different table in the same page without breaking the filters. 
I fixed it.

**Comment by Foudro** [comment]
closed
