### ISSUE TITLE
Bug on xpath (shortened) with control verifyregex 

### ISSUE THREAD

**Issue by pfoucray** [vertigo17/Cerberus#795]
Cerberus Version : 1.1.4-SNAPSHOT

I have an Xpath that cannot get saved properly.
I 1st put something probably too long. so cerberus removed extra caracters.
I then wrote a new xpath, shorter, expecting it to work.

And it did work once. Then after saving my TC, cerberus again removed extra caracters.

It clearly looks like a bug.

Here's an execution that shows it worked (step 5, last control)
http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=32852687

see the test, it won't save a longer xpath.
Full length xpath would be : xpath=//span[@class='ng-binding flex' and contains(.,"Votre demande a bien été prise en compte, enregistrement des conditions en cours")]
shorter would be : xpath=//span[@class='ng-binding flex' and contains(.,"Votre demande")]
what it always put is : xpath=//span[@class='ng-binding flex' and contains(.,

regards,
PF

**Comment by bcivel** [comment]
@pfoucray 
Duplicated issue #743, that is already solved in the 1.1.4
Please upgrade Cerberus to 1.1.4
