### ISSUE TITLE
Enhancement Xpath with /text() or not

### ISSUE THREAD

**Issue by R-Loic** [vertigo17/Cerberus#796]
Hello,

It would be interesting to standardize the xpath rules following the actions on cerberus. I mean sometimes we have to put /text() at the end of the expression and sometimes we don't have to. (and it is not indicated to the user) So can you please standardize xpath rules on cerberus ?

Thank you

Cerberus Version : 1.1.4-SNAPSHOT

**Comment by vertigo17** [comment]
Can you be more specific on the different usage that you consider not consistent ?
When we want an element we put the xpath without /text() --> Ex : Control VerifyElementPresent
When we want a value we put /text() or atribute or comment or... --> SOAP data inside datalibrary.

**Comment by R-Loic** [comment]
the following examples : 
- SOAP data inside datalibrary : I need to put /text() at the end
- GetFromXML in properties : I don't have to put /text() 

This is not "user friendly" because there is no indication. I propose that Cerberus don't add automatically /text().

**Comment by vertigo17** [comment]
OK this will be the logic :

When getting a property with either :
- executeSoapFromLib 
- GetFromTestDataLib
- getFromXml
--> Require /text()

On the controls :
- verifyTextInElement
- verifyTextNotInElement
--> Only the element needs to be specified. No need to put /text()
