### ISSUE TITLE
Not able to load test case list

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#797]
Cerberus Version : 1.1.5-SNAPSHOT

When trying to load test case on TestCaseList.jsp, it is not possible.
We get the error "An unexpected problem occurred. java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp" on the page.
On the instance log, we get:
ERROR TestCaseDAO:250 - Unable to execute query : java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp

Example done with:
System: VCCRM
Test to load: PAGE VCCRM CustomerIdentification

**Comment by bcivel** [comment]
fixed
