### ISSUE TITLE
Testcase execution result GUI

### ISSUE THREAD

**Issue by mbessa** [vertigo17/Cerberus#802]
Hello,

In CerberusQA, test execution actions are not visible, only show's the Step header.

http://192.168.134.35/CerberusQA/ExecutionDetail.jsp?id_tc=32934035

Cerberus Version : 1.1.5-SNAPSHOT

**Comment by gmoita** [comment]
We were trying to find the issue and found that testcasestepactionexecution is not being filled at all.
After running a couple of tests, we verified the max timestamp for stepaction execution and it is not being updated.
tabela, min(start), max(start)
'testcasestepactionexecution', '2016-01-01 00:00:02', '2016-06-04 02:05:00'
'testcaseexecution', '2015-10-08 21:40:00', '2016-06-07 20:18:50'

On the execution log, we also see:
[#|2016-06-07T20:18:50.250+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:18:50 INFO  RunTestCase:318 - Execution Requested : UUID=be1cfcf3-21b5-4ca3-b045-d7eaf0fffed7
|#]

[#|2016-06-07T20:18:52.437+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:18:52 INFO  ExecutionStartService:40 - Execution Started : UUID=be1cfcf3-21b5-4ca3-b045-d7eaf0fffed7__ID=32934079
|#]

[#|2016-06-07T20:18:52.453+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:18:52 ERROR TestCaseStepActionExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:18:54.421+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:18:54 ERROR TestCaseStepActionControlExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:18:54.625+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:18:54 ERROR TestCaseStepActionExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:18:54.640+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:18:54 ERROR TestCaseStepActionExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:18:54.640+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:18:54 ERROR TestCaseStepActionExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:18:54.953+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:18:54 ERROR TestCaseStepActionExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:18:55.265+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:18:55 ERROR TestCaseStepActionExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:18:55.265+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:18:55 ERROR TestCaseStepActionExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:18:57.140+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:18:57 ERROR TestCaseStepActionExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:18:57.140+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:18:57 ERROR TestCaseStepActionExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:18:57.218+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:18:57 ERROR TestCaseStepActionExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:19:02.218+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:02 ERROR TestCaseStepActionExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:19:02.234+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:02 ERROR TestCaseStepActionExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:19:02.531+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:02 ERROR TestCaseStepActionControlExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:19:02.531+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:02 INFO  RecorderService:40 - [TAG Commander - 0207B - step: 2 action: 5]Doing screenshot.
|#]

[#|2016-06-07T20:19:04.828+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:04 INFO  WebDriverService:40 - WebDriverService: screen-shot taken with succes: screenshot884979218884891566.png(size1632171)
|#]

[#|2016-06-07T20:19:04.828+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:04 INFO  RecorderService:40 - [TAG Commander - 0207B - step: 2 action: 5]Create directory for execution 32934079
|#]

[#|2016-06-07T20:19:04.843+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:04 WARN  RecorderService:40 - [TAG Commander - 0207B - step: 2 action: 5]Screen-shot size exceeds the maximum defined in configurations screenshot884979218884891566.png destination: TAGCommander-0207B-St2Sq5Ct1.jpg
|#]

[#|2016-06-07T20:19:04.890+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:04 INFO  RecorderService:40 - [TAG Commander - 0207B - step: 2 action: 5]Copy file finished with success - source: screenshot884979218884891566.png destination: TAGCommander-0207B-St2Sq5Ct1.jpg
|#]

[#|2016-06-07T20:19:04.906+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:04 INFO  RecorderService:40 - [TAG Commander - 0207B - step: 2 action: 5]Temp file deleted with success screenshot884979218884891566.png
|#]

[#|2016-06-07T20:19:04.906+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:04 ERROR TestCaseStepActionExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:19:05.265+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:05 ERROR TestCaseStepActionExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:19:10.265+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:10 ERROR TestCaseStepActionControlExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:19:10.609+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:10 ERROR TestCaseStepActionExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:19:15.609+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:15 ERROR TestCaseStepActionExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:19:15.640+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:15 ERROR TestCaseStepActionControlExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:19:15.640+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:15 ERROR TestCaseStepActionControlExecutionDAO:40 - Unable to execute query : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'End' at row 1
|#]

[#|2016-06-07T20:19:15.640+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:15 INFO  RecorderService:40 - [TAG Commander - 0207B - step: 3 action: 2]Doing screenshot.
|#]

[#|2016-06-07T20:19:17.687+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:17 INFO  WebDriverService:40 - WebDriverService: screen-shot taken with succes: screenshot1523333740293419488.png(size1781448)
|#]

[#|2016-06-07T20:19:17.687+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:17 WARN  RecorderService:40 - [TAG Commander - 0207B - step: 3 action: 2]Screen-shot size exceeds the maximum defined in configurations screenshot1523333740293419488.png destination: TAGCommander-0207B-St3Sq2Ct2.jpg
|#]

[#|2016-06-07T20:19:17.687+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:17 INFO  RecorderService:40 - [TAG Commander - 0207B - step: 3 action: 2]Copy file finished with success - source: screenshot1523333740293419488.png destination: TAGCommander-0207B-St3Sq2Ct2.jpg
|#]

[#|2016-06-07T20:19:17.687+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:17 INFO  RecorderService:40 - [TAG Commander - 0207B - step: 3 action: 2]Temp file deleted with success screenshot1523333740293419488.png
|#]

[#|2016-06-07T20:19:19.703+0200|INFO|sun-appserver2.1|org.cerberus.engine.execution.impl.SeleniumServerService|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|Stop Selenium Server|#]

[#|2016-06-07T20:19:19.796+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:19 INFO  ExecutionRunService:40 - Execution Finished : UUID=be1cfcf3-21b5-4ca3-b045-d7eaf0fffed7__ID=32934079__RC=OK__TestName=PREPROD.PT.2016-06.02.TAG Commander_0207B_Verify tc_vars[product_page_type] on miniPDP (New PDP Layout)
|#]

[#|2016-06-07T20:19:19.796+0200|INFO|sun-appserver2.1|javax.enterprise.system.stream.out|_ThreadID=125;_ThreadName=httpSSLWorkerThread-38082-1;|2016-06-07 20:19:19 ERROR RunTestCase:364 - CerberusExecution {"screenSize":"(960, 510)","port":"5555","crbVersion":"Cerberus-1.1.5-SNAPSHOT","controlStatus":"OK","test":"TAG Commander","tag":"","build":"2016-06","version":"31.6.0","id":32934079,"revision":"02","verbose":0,"browser":"firefox","end":1465323559000,"browserFullVersion":"firefox 31.6.0 LINUX","controlMessage":"The test case finished successfully","platform":"LINUX","status":"WORKING","executor":"Selenium","testCaseStepExecutionList":[{"id":32934079,"returnCode":"OK","testCaseStepActionExecutionList":[],"timeElapsed":1.875,"start":1465323535000,"test":"TAG Commander","description":"Open a PDP","fullEnd":20160607201857140,"fullStart":20160607201855265,"end":1465323537000,"step":1,"testcase":"0207B"},{"id":32934079,"returnCode":"OK","testCaseStepActionExecutionList":[],"timeElapsed":13.469,"start":1465323537000,"test":"TAG Commander","description":"Mini PDP display","fullEnd":20160607201910609,"fullStart":20160607201857140,"end":1465323550000,"step":2,"testcase":"0207B"},{"id":32934079,"returnCode":"OK","testCaseStepActionExecutionList":[],"timeElapsed":7.078,"start":1465323550000,"test":"TAG Commander","description":"Calculate TagCommader Variable","fullEnd":20160607201917687,"fullStart":20160607201910609,"end":1465323557000,"step":3,"testcase":"0207B"}],"finished":"N","testcase":"0207B","url":"preprod.laredoute.pt","country":"PT","ip":"192.168.135.150","environment":"PREPROD","start":1465323530000,"capabilities":[]}
|#]

We believe that it is related.
that

**Comment by bcivel** [comment]
Thanks @mbessa @gmoita 
I was related as you suspected.
fixed with the commit 1b91d0b
