### ISSUE TITLE
Property not calculated

### ISSUE THREAD

**Issue by mbessa** [vertigo17/Cerberus#803]
Hello,

In the following testcase execution getfromxml property was not calculated and show's as pending while test execution already stopped and Failed.

http://192.168.134.35/CerberusQA/ExecutionDetail.jsp?id_tc=32934035

**Comment by vertigo17** [comment]
So, basically, this issue has been created to homogenize the way xml is parsed in Cerberus. So now, you should put /text() at the end of the xpath when using getFromXml (before /text() was hardcoded inside Cerberus)
you can see the result here : http://192.168.134.35/CerberusQA/ExecutionDetail.jsp?id_tc=32934081

**Comment by vertigo17** [comment]
Anyway the execution should never finish in PE status.
I propose to leave the ticket open to confirm that even if /text() is not specified, the test failed with the correct message.
Can you retest it after deploy of #802

**Comment by bcivel** [comment]
I convert the value retrieved into String and it solved the issue.
So now, regarding this Node : 
<StatusCode>OK</StatusCode>
Putting  in value 2 //StatusCode/text() will give OK
Putting  in value 2 //StatusCode will give <StatusCode>OK</StatusCode>
