### ISSUE TITLE
Testcase execution with Synchroneous Set to "N"

### ISSUE THREAD

**Issue by mbessa** [vertigo17/Cerberus#804]
Hello,

When running a testcase with Synchroneous option set to "N ( Redirect to the execution before the end of the execution )", test case starts execution and redirect to testcaseexecution page with corresponding ID, but GUI is not displayed correctly (parts of webpage are missing) and do not refresh as expected, keeps in the same page even after testexecution stops.

Thanks,
MB

**Comment by bcivel** [comment]
Fixed with 4cce5d09a0021c80524912284b08c513bc5af95d
