### ISSUE TITLE
Test Battery - Remove multiple tests at once

### ISSUE THREAD

**Issue by dmarzlin** [vertigo17/Cerberus#816]
After adding wrong test cases to a test battery, I would have liked to remove all of them, but I had to remove them one after another.
It would be nice to have an option to be able to select multiple test entries and delete them all at once.

**Comment by bcivel** [comment]
Hello @dmarzlin 
We are working on the refactoring of this page. I added your suggestion to the related issue to keep it in mind
You can now follow the resolution here : #783
Thanks for your contribution
Benoit
