### ISSUE TITLE
Bug/Impossible to delete an Entry in Test Data Library

### ISSUE THREAD

**Issue by AbelZou** [vertigo17/Cerberus#820]
I created a New Entry in Data>Data Library (BETA). I want to delete it but when i click on the button delete entry and then i click on yes, but nothing is happening, and my cerberus bug, after some minutes waiting i got message of error  :      
An unexpected problem occurred. Unable to execute Delete operation(s)!

**Comment by pfoucray** [comment]
Apparently it works again today
