### ISSUE TITLE
Control issue verifyElement text lenght?

### ISSUE THREAD

**Issue by j0hnsa** [vertigo17/Cerberus#821]
Hello,

unable to create a control with a big xpath. I believe the problem might be the size:
Case: 
add control to a test for example verifyElementVisible with text:
xpath=//android.widget.TextView[@resource-id='com.ocito.laredoute:id/label_textView' and @text='42']/following-sibling::android.widget.LinearLayout/android.widget.ImageView[@resource-id='com.ocito.laredoute:id/label_view']

after saving the testcase control disappear.

**Comment by bcivel** [comment]
You're right. Limit is 200 char in database.
A workaround in you case could be to use a property to do that (where the limit is 2000 char).
Anyway, we will extend the field and give you feedback on new lenght

**Comment by vertigo17** [comment]
Limit is now at 2500 Characters (same as property limit).
