### ISSUE TITLE
Be able to enable/disable executions

### ISSUE THREAD

**Issue by abourdon** [vertigo17/Cerberus#831]
It could be great to enable/disable executions by just setting a global property. Thus, any execution would be canceled (`CA` test execution result) while property is on.

**Comment by bcivel** [comment]
I would advice to don't even record execution when parameter is on (I mean don't perform any insert in execution table).

**Comment by abourdon** [comment]
How about a campaign which is executing in the same time. Should we not keeping trace of canceled executions to inform user?

**Comment by bcivel** [comment]
For a campaign through runMultiple test, test sould stay in the queue table with the specific message (and CA status you're right).
For a campaign executed through an external script, result CA can be raised as well.

So It is as you said. I just wanted to make sure that in both case, no access to the testcaseexecution table.
