### ISSUE TITLE
Problems with new sorting in Cerberus 

### ISSUE THREAD

**Issue by j0hnsa** [vertigo17/Cerberus#834]
Hello,

In this testcase:http://192.168.134.35/Cerberus/TestCase.jsp?Load=Load&Test=Guided+Nav&TestCase=0060A  when adding a control to step 17 it adds the control in step 1 that is a step library.

We've noticed that this new sorting of steps gets often steps mixed up

**Comment by abourdon** [comment]
This bug was fixed by #825
