### ISSUE TITLE
TestCase Ran with wrong steps

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#835]
Cerberus is running steps deleted from the testcase. It is impossible to work with test creation.
![testcase_run](https://cloud.githubusercontent.com/assets/1914659/16419219/cf7b65e0-3d44-11e6-9557-17f5bf9c9935.png)
![testcase](https://cloud.githubusercontent.com/assets/1914659/16419218/cf7aa3f8-3d44-11e6-882f-cdf2df3f142a.jpg)

**Comment by abourdon** [comment]
Fixed by #825

**Comment by ruirpr** [comment]
So in the meantime how can we solve situations were cerberus keeps running deleted steps?
