### ISSUE TITLE
Test appears in TCList when changing System

### ISSUE THREAD

**Issue by pfoucray** [vertigo17/Cerberus#837]
Cerberus Version : 1.1.5-SNAPSHOT

Say you're doing something on test TEST01 which belongs to System01
Then wanna do something in System02. Systel02 doesn't have any Test01 (or TC belonging to it)
You then change system and find yourself on an empty TC list page.

Check TC list, it'll show TEST01 on last postition.
Refresh page, Test disappears, everything's back to "normal".

Bug ?

Keep up the nice work!
Regards,
PF

**Comment by bcivel** [comment]
solve since the last commit
