### ISSUE TITLE
getFromHtml does not work with '$' in text

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#838]
I'm trying to get price in USD from a product but it seems that using getFromHtml data-cerberus=txt_plp_discountedPrice1 does not work with the $19.49 (test PE forever) but works with value in euros. 

I'm also trying to use a getFromJs instead:
var text = document.querySelector('[data-cerberus="txt_plp_discountedPrice1"]').textContent; return text;
wich is correctly calculated in the properties but test fails to perform the action:
http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=33767713

Any ideia on how i can achieve this? 
Thanks!

**Comment by ruirpr** [comment]
Hi
I really need to get the price in $ from page, example http://preprod.laredoute.com/ppdp/prod-350003244.aspx

I can calculate the value using JS but cerberus fails to continue.

**Comment by bcivel** [comment]
corrected with my last commit.
