### ISSUE TITLE
Make a research on all words of a label in the tag in "Execution reporting by tag"

### ISSUE THREAD

**Issue by MichaelWil** [vertigo17/Cerberus#840]
Hi,

Currently when you are in the page : "ReportingExecutionByTag" you can display the drop down menu and the only option to find the expected tag is to use the scroll bar.

As the number of tags will surely increase, it'll be great to have a field in which when you type one word the search is done for all the tags for all position.

You can find an example here : https://select2.github.io/examples.html, in select boxes with labels.
![2016-06-29_141729](https://cloud.githubusercontent.com/assets/11719918/16451714/ef50e190-3e04-11e6-973b-f0c9f219cfa6.jpg)

Thanks and regards.

**Comment by bcivel** [comment]
@MichaelWil Thanks for the suggestion. 
I let you to test it and close the issue if it fit your needs.

**Comment by MichaelWil** [comment]
Hi,

Thanks for your quick action ! This is a real improvment regarding to the initial situation but i'd 2 things to be add (if possible) : 
1- make the typed letters visible (like you see "al" in my exemple). Currently nothing is visible.
2- display only the tag that meet the typed letters. Currently only the first label (corresponding to the request) is displayed.

Can you do that ?

Fell free to come back to me if you need any clarifications.

Thanks

**Comment by abourdon** [comment]
Hi Michael,

Improvement is done, I can so close this issue.

Regards,
Aurélien
