### ISSUE TITLE
verifyTextInPage * 

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#842]
I'm trying to use verifyTextInPage to verify: 
Disallow: /*dynaTraceMonitor

I made a step that looks for "Disallow: /" and it's OK
I made a step that looks for "dynaTraceMonitor" and it's OK
I made a step that looks for "Disallow: /*dynaTraceMonitor" and it's KO

So, cerberus can't find text with * or /* ? 
Thanks!

**Comment by bcivel** [comment]
verifyTextInPage verify a regex match in the page.
If the string you want to verify contains *, it will be interpreted as part of the regex.

If you use [*]  (Disallow: /[*]dynaTraceMonitor for example), it works. 

I let you confirm it's OK and close the issue.

**Comment by vertigo17** [comment]
Maybe we could add that in corresponding documentation.

**Comment by ruirpr** [comment]
Thanks for the explanation, it works!
