### ISSUE TITLE
Add a new 'Eval' Property type

### ISSUE THREAD

**Issue by abourdon** [vertigo17/Cerberus#848]
The 'Eval' Property type could take an expression that would be evaluated at runtime. Expression language would be dependent on the evaluation engine. For instance, in Groovy (because of its easily [Java integration](http://groovy-lang.org/integrating.html#integ-eval)) we could write something like this : 

`"foo bar".replace("bar", "baz")`

Then any `bar` words would be replaced by `baz` on the `foo bar` String (`foo baz` in our example).

An other interesting point, is that our _property interpretation mechanism_ could also be used, in order to produce more complex transformation between one or several properties. For instance:

`"%FOO%".replace("%BAR%", "%BAZ%")`

Then we could have the same powerful mechanism as our `executeJS` Property type, but now computed by our core engine instead of browser, and then compatible with any Application type, like Android one.

**Comment by abourdon** [comment]
Relates to #839

**Comment by cjmachado** [comment]
Hi,
I know this issue is already closed, but...
I noticed that this feature is already in QA. So, I was curious and logged in to Cerberus to try it out (you know me). I placed  the following code in the getFromGroovy property:

System.exit(0)

This effectively shuts down the Glassfish instance! And this is just an example of a possible code injection. For instance, any user who's allowed to create and run test cases can now delete the entire glassfish installation, drop the database, etc.

**Comment by abourdon** [comment]
Ah ah, well done :-) We will investigate a way to protect us and will be back to you soon.

Regards,
Aurélien

**Comment by abourdon** [comment]
Hi @cjmachado,

Could you please check from your side if you still execute some malicious code ? ;-)

Note that loops or recursivity are not considered as malicious because useful. We consider malicious an expression which can access to critical data, by using file system or database for example, or using a not allowed instruction as System.exit for instance.

Let's try to break Cerberus ;-)

Regards,
Aurélien

**Comment by cjmachado** [comment]
Nice one. 
I took a look at the code and I see you are sandboxing the groovy execution (Arigato Kohsuke!). Here are some of the examples I tried:

1) Try to kill the process

import static java.lang.System.exit  // class System not allowed
exit(1)

2) Try to kill the process

Runtime.getRuntime().exit(1) // class Runtime not allowed

3) Try to kill the process

ProcessBuilder pb = new ProcessBuilder("pkill", "-9", "java")  // class ProcessBuilder not allowed
pb.start()

4) Try to fill the process memory space

// 12 GB - throws OOME, but Cerberus survived
char[] c1 = new char[Integer.MAX_VALUE]
char[] c2 = new char[Integer.MAX_VALUE]
char[] c3 = new char[Integer.MAX_VALUE]

5) Try to delete files / directories

import java.io.File   // class File not allowed
File f = new File("~")
f.delete()

6) Try to destroy the database

import java.sql.Connection
import java.sql.ResultSet
import java.sql.Statement
import javax.naming.Context
import javax.naming.InitialContext
import javax.naming.NamingException
import javax.sql.DataSource

InitialContext ctx = new InitialContext()   // class InitialContext not allowed
DataSource ds = ctx.lookup("jdbc/cerberusLookupName")
Connection c = null
ResultSet r = null
Statement s = null
try {
  c = ds.getConnection()
  s = c.createStatement()
  r = s.executeUpdate("Drop database cerberus")
} finally {
    if (r != null) {
      r.close()
    }
    if (s != null) {
      s.close()
    }
    if (c != null) {
      c.close()
    }
}

Thanks for your work, @abourdon !

**Comment by cjmachado** [comment]
The only complaint I have is that this feature is rather slow, but it seems to be safe to use.

**Comment by abourdon** [comment]
Hi @cjmachado,

Thanks for your feedbacks and many thanks for the many tries you done!

Yes, I used the impressive work offers by the https://github.com/kohsuke/groovy-sandbox project.

And yes, the dynamic checks cause execution to be a bit slow, but now much safe to use.

Sincerely,
Aurélien
