### ISSUE TITLE
Add a new 'Transform' Property column

### ISSUE THREAD

**Issue by abourdon** [vertigo17/Cerberus#849]
A new 'Transform' column could be added to the Property array to execute a transformation process after the Property value computation. This column could be split into several ones as the following: 

- a combo list of actions (replace, toUppercase, addToDate, ...)
- one or several columns acting as parameters for the selected transform action.

This approach would be more _functionally understandable_ and each action could be developed following the needs, as we can already do with Step's actions or controls.

Let me know

**Comment by abourdon** [comment]
Relates to #839

**Comment by vertigo17** [comment]
I propose to close that issue as Groovy makes the work for complex tests.
