### ISSUE TITLE
Random GetFromDataLib SubData weird results? 

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#850]
I'm strugling to understand some results I'm getting.
In this execution http://192.168.134.35/CerberusRegression/ExecutionDetail.jsp?id_tc=34041204 the product is a 20 line result from the query P_PA_RDT_AVL_MULTI_MANAGER
, randomly choosed. For example 324396765. So far, so good.
Then, in Step8Action1 the MULTI_ID property is calculated and it contains %PRODUCT(MID)% wich results in AKM940. Here is the problem. If we look into the line with the 324396765, it should give the AVP387. Instead it is giving the value from the line before. Changing the PRODUCT to static, it works fine.
It looks like getting the subdata from a random result is messed up or making a new random wich does not sound right. 
For example in this execution, the subdata value is several lines bellow the original random product: http://192.168.134.35/CerberusRegression/ExecutionDetail.jsp?id_tc=34042418

![p_pa_rdt_avl_multi_manager](https://cloud.githubusercontent.com/assets/1914659/16615499/05cb6f70-436f-11e6-8960-e6f0b275606f.jpg)

Thanks!

**Comment by vertigo17** [comment]
This is for sure not normal although I was not able to replicate.

**Comment by vertigo17** [comment]
In fact this is nomal. Unfortunatly the current version do not disply the timestamps of calculation but with the lastest version, you will see that the Property has been refreshed with the last calculateProperty Action.
The global rule is that each time you call calculateProperty Action, you force the recalculation of every property it include. That include the Property of the calculateProperty but also any properties used inside the calculateProperty property.
The best is to avoid using calculateProperty Action as much as you can. Just use any property you need with %PROP% syntax of %PROP(SUBDATA)% and it will only be calculated once and reused again and again without any other calculation until you use calculateProperty.

Please retest removing calculateProperty when not needed.
