### ISSUE TITLE
Add comment for properties

### ISSUE THREAD

**Issue by R-Loic** [vertigo17/Cerberus#851]
Hello,

I think it would be interesting to have a new colonm in properties section for comments.(Just beside the value for example)
This enhancement would facilitate communications and readability of test cases. I've met several situations which this improvement would have been usefull.

Thanks

**Comment by abourdon** [comment]
To sum up what has been done:

- The new description field has been added from current & beta TestCase page

![screen shot 2016-07-12 at 16 01 27](https://cloud.githubusercontent.com/assets/1511715/16769772/5247abcc-484a-11e6-8d26-a254ac10bc05.png)

![screen shot 2016-07-12 at 16 01 58](https://cloud.githubusercontent.com/assets/1511715/16769771/5242184c-484a-11e6-8dd3-ea48cd18a806.png)

- The new description field has been added to the ExecutionDetail page

![screen shot 2016-07-12 at 16 02 26](https://cloud.githubusercontent.com/assets/1511715/16769773/5257acf2-484a-11e6-880c-f1b875fbea3b.png)

Regards,
Aurélien

**Comment by vertigo17** [comment]
Design on the new page is not correct. Let's put the description on the right side of the 1st line and hide the unnecessary field depending on the property function that is used.
Eg : when using text, Database, rowLimit should be hiden.

**Comment by abourdon** [comment]
Hi Benoit,

So design in the "old" TestCase and TestCase execution are corrects?

Regarding the new TestCase page, then you would have:

- the three fields in the same first line: property name, value and description
- the other fields in the second line, by disabling those which are not necessaries depending the type of the property.

Is it ok for you?

**Comment by vertigo17** [comment]
On execution page, separate the description in a different td. Don't forget to put the tooltip = description.

Old TestCase looks OK.

On new page that will be more:
1st line: Property name, countries, type, database, rowLimit, Length, Nature, desciption
2nd line: Action buttons, Value

If 1st line makes the size of fields too small, we will need to finish implementation of js function setPlaceholderProperty() that will hide the unnecessary data: database, rowLimit, Length, Nature Depending on type of property.
If the size is still too small, we will add a button and put optional information on a new line at the bottom.

**Comment by vertigo17** [comment]
js error:
![selection_127](https://cloud.githubusercontent.com/assets/5342048/16819375/7672220e-494c-11e6-8cc6-7d8a068b1eee.jpg)
Please correct ASAP.
You can get it there:
http://localhost:8080/Cerberus/TestCaseScript.jsp?test=Performance%20Monitor&testcase=5014M

**Comment by abourdon** [comment]
This issue can be closed.

The new issue #864 has been created to keep trace on the improvement for automatically hide the property columns according to its type.
