### ISSUE TITLE
Execution thread pool is working weirdly

### ISSUE THREAD

**Issue by abourdon** [vertigo17/Cerberus#853]
Assume we want to execute 10 test cases by setting the `cerberus_execution_threadpool_size` to 1. Then we would have 1 execution at a time, as we can see from the _Cerberus Monitoring_ page (_Number of Workers In Execution_ = _1/1_).

But, when I'm executing the 10 test cases, I can see that more than 1 test case is executed at at time.

**Comment by bcivel** [comment]
Can you detail a bit more the way to reproduce?
When you see more than 1, did you submit only the runMultiple or did you execute other signle test from run page?

**Comment by abourdon** [comment]
I was using the beta run test case page
