### ISSUE TITLE
bug / Cant' set New Password

### ISSUE THREAD

**Issue by pfoucray** [vertigo17/Cerberus#854]
Cerberus Version : 1.1.5-SNAPSHOT

link seems inactiv working on ff 46

<button id="changePassword" class="btn btn-primary col-xs-6" type="button">Change Password</button>

regards,
PF

**Comment by bcivel** [comment]
Corrected with my last commit

**Comment by pfoucray** [comment]
not even 5 hours to commit !!
Thx !

regards,
PF
