### ISSUE TITLE
Allow to group testcase using labels

### ISSUE THREAD

**Issue by bcivel** [vertigo17/Cerberus#855]
In order to group testcase whatever the criterias, it could be useful to give the possibility to attach labels on them.

I identify these change
**Create Label table and objects (including entities, dao, services...etc)**
This table will store the label name and style at a system level. We can already introduce a parentLabel column to allow to link label together.
>ID (INT autoinc), System (Varchar45), Label (Varchar45), Style (Varchar250), ParentLabel (INT), Creator (Varchar10), last_modified(Timestamp)
>>_Unicity on System, Label_

**Create TestCaseLabel Table and objects (including entities, dao, services)**
This table will store the list of label for test, testcase.
>ID, Test, Testcase, LabelID
>>_Unicity on Test, Testcase, labelId_

**GUI Modification**
>Change on TestCaseList to display labels
<img width="1530" alt="capture d ecran 2016-07-10 a 18 58 45" src="https://cloud.githubusercontent.com/assets/5376184/16714867/6bc97844-46d0-11e6-9dc2-c37d8c6699cf.png">
>Management of labels can be done on a specific page Label

**Comment by vertigo17** [comment]
in order to comply with #473 

Creator (Varchar10), last_modified(Timestamp)

is to be replaced by :

UsrCreated varchar(45)
DateCreated timestamp
UsrModif varchar(45)
DateModif timestamp

**Comment by pfoucray** [comment]
Hi,

noticed two little bugs regarding labels :
1 ) on label page, when deleting label, popin shows "missing doc !!!"
2 ) on TC list page, when updating label with little button to the left (Actions Column), it updates every TC already having a label, with the same selection)

regards,
PF
