### ISSUE TITLE
Wait for element stops Campaign execution when element is not found [Android]

### ISSUE THREAD

**Issue by j0hnsa** [vertigo17/Cerberus#858]
Hello,

when using the action wait and the object used is an element of the page we are supposed to look for the wait action takes long to execute and the campaign stops without executing the rest of the tests it was supposed to, Can you change the behavior of wait action to secure that test fails after a period of time looking for some element and campaign carries on.

**Comment by abourdon** [comment]
Hi,

I've just check from my side and the wait for an object path is working. Is the bug still occurs? If yes, could you please post logs of your Appium server?

Regards,
Aurélien

**Comment by j0hnsa** [comment]
Hello Aurélien,

It happens occasionally today had the same issue in attachment are some logs from appium and from selenium. Campaign stops because cant create a new session as the previous is "hanged".

Best Regards
[logsappium.txt](https://github.com/vertigo17/Cerberus/files/377628/logsappium.txt)
[logsselenium.txt](https://github.com/vertigo17/Cerberus/files/377631/logsselenium.txt)

**Comment by j0hnsa** [comment]
No longer replicated.

Thanks
Best Regards
