### ISSUE TITLE
remove the usage of preStat.setNString in TestCaseCountryPropertiesDAO

### ISSUE THREAD

**Issue by vertigo17** [vertigo17/Cerberus#860]
setNString is not suppoted in MariaDB so we need to remove its usage.

TestCaseCountryPropertiesDAO:40 - Unable to execute query : java.sql.SQLFeatureNotSupportedException: NStrings not supported

**Comment by vertigo17** [comment]
I tested on my side replacing all preStat.setNString to preStat.setString and get no regression on Checkout Basket Product Block-0081 as seen in #800.
@bcivel  can you test on your side trying to replicate the issue ?

**Comment by bcivel** [comment]
I tried replacing setNString to setString and problem occured again.

I tried adding this parameters (connectionProperties useUnicode=yes;characterEncoding=utf8;) in connection Pool parameters but it didn't solve this issue.


<img width="1628" alt="capture d ecran 2016-07-14 a 22 43 08" src="https://cloud.githubusercontent.com/assets/5376184/16856172/120c267a-4a19-11e6-8225-9010d1d39fca.png">

**Comment by bcivel** [comment]
@vertigo17 
_In testCaseCountryPropertiesDAO class, findCountryByProperty method (line 204):_
replacing **preStat.setNString(6,testCaseCountryProperties.getValue1());**
by **preStat.setBytes(6, testCaseCountryProperties.getValue1().getBytes("UTF-8"));**
works fine with MySQL.
Could you confirm if it can work with MariaDB?

**Comment by vertigo17** [comment]
It does.
I will commit the change.
