### ISSUE TITLE
Special characters are not well displayed

### ISSUE THREAD

**Issue by abourdon** [vertigo17/Cerberus#871]
Hi,

Special characters are not well displayed on different pages. For instance:

* When using an use step:

![screenshot](https://cloud.githubusercontent.com/assets/1511715/17050469/4e2ad126-4ff3-11e6-9e77-6c3af577ad6b.png)

* When accessing to the single execution page:

![screenshot2](https://cloud.githubusercontent.com/assets/1511715/17050472/4fbe7344-4ff3-11e6-8024-4882c6470a1e.png)

And so on.

It could be great to do a whole check on all pages.

Note, I'm using the Cerberus 1.1.3.1 version but maybe this issue is also related to the SNAPSHOT one.

Regards,
Aurélien

**Comment by vertigo17** [comment]
Complete check has been done but only on new pages.
old testcase needs to be standardize the same way as the new one.

**Comment by abourdon** [comment]
Hi @vertigo17,

And so, old pages could be "standardized" the same way?

Regards,
Aurélien

**Comment by bcivel** [comment]
corrected with my last commit.
Thanks
