### ISSUE TITLE
TC Page not beta / automatic property creation

### ISSUE THREAD

**Issue by pfoucray** [vertigo17/Cerberus#872]
Cerberus Version : 1.1.6-SNAPSHOT

getting the following message into prompt box.
I have a country. Apparently, TC is correctly configured
message :
"An unexpected problem occurred. It was not possible to update table."

regards,
PF

**Comment by abourdon** [comment]
Actually, this feature is no longer valid as property input is now named as "value2" input. Then input could contain any string, and not only property name.

So this feature will be deactivated from the next commit.

Regards,
Aurélien
