### ISSUE TITLE
Unable to Launch Tests with appium running on MAC

### ISSUE THREAD

**Issue by j0hnsa** [vertigo17/Cerberus#873]
Hello,

I've been Having some issues launching tests with devices connected to MAC and maybe some configuration may have to be changed. When a test is launched app is installed it starts but it fails immediately. Below are some logs_
Logs on Hub:

2016-07-27 11:33:54 - 0 [Checkout Summary|0008C|FR|PREPROD] : 'FA' - 8 The test case failed to be executed. Could not start Selenium. org.openqa.selenium.WebDriverException: No such context found. (WARNING: The server did not provide any stack trace information
Command duration or timeout: 24.59 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'risrvdev1', ip: '192.168.134.35', os.name: 'Windows 2003', os.arch: 'x86', os.version: '5.2', java.version: '1.7.0_80'
Driver info: io.appium.java_client.android.AndroidDriver._
)
Appium Logs:

Launching Appium with command: export ANDROID_HOME="/Users/itsqdtests/Library/Android/sdk/"; '/Volumes/Appium/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --address "172.16.9.196" --port "5555" --debug-log-spacing --log-level "debug" --automation-name "Appium" --platform-name "Android" --platform-version "6.0.1" --full-reset --dont-stop-app-on-reset --device-ready-timeout "50000"

[Appium] Welcome to Appium v1.5.3

[Appium] Non-default server args:

[Appium]   address: '172.16.9.196'
[Appium]   port: 5555
[Appium]   debugLogSpacing: true
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '6.0.1'
[Appium]   automationName: 'Appium'
[Appium]   fullReset: true
[Appium]   deviceReadyTimeout: 50000
[Appium]   dontStopAppOnReset: true
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"Android"}'
[Appium]   --platform-version => --default-capabilities '{"platformVersion":"6.0.1"}'
[Appium]   --automation-name => --default-capabilities '{"automationName":"Appium"}'
[Appium]   --full-reset => --default-capabilities '{"fullReset":true}'
[Appium]   --device-ready-timeout => --default-capabilities '{"deviceReadyTimeout":50000}'
[Appium]   --dont-stop-app-on-reset => --default-capabilities '{"dontStopAppOnReset":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:

[Appium]   platformName: 'Android'

[Appium]   platformVersion: '6.0.1'
[Appium]   automationName: 'Appium'
[Appium]   fullReset: true
[Appium]   deviceReadyTimeout: 50000
[Appium]   dontStopAppOnReset: true

[Appium] Appium REST http interface listener started on 172.16.9.196:5555

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 17 ms - 83 

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"Appium","app":"/Users/itsqdtests/Desktop/Payload/LaRedoutePreprod_7_2.apk","autoWebview":true,"deviceName":"Android","platformName":"Android","browserName":"","browser":"firefox"}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"Appium"...

[Appium] Creating new AndroidDriver session
[Appium] Capabilities:

[Appium]   automationName: 'Appium'
[Appium]   app: '/Users/itsqdtests/Desktop/Payload/LaRedoutePreprod_7_2.apk'
[Appium]   autoWebview: true
[Appium]   deviceName: 'Android'
[Appium]   platformName: 'Android'
[Appium]   browserName: ''
[Appium]   browser: 'firefox'
[Appium]   platformVersion: '6.0.1'
[Appium]   fullReset: true
[Appium]   deviceReadyTimeout: 50000
[Appium]   dontStopAppOnReset: true

[BaseDriver] The following capabilities were provided, but are not recognized by appium: browser.

[BaseDriver] Session created with session id: 7121e4b8-beb0-42eb-a12f-5fe74fc79964
[debug] [AndroidDriver] Getting Java version

[AndroidDriver] Java version is: 1.8.0_92

[ADB] Checking whether adb is present

[ADB] Using adb from /Users/itsqdtests/Library/Android/sdk/platform-tools/adb
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android 6.0.1
[debug] [ADB] Setting device id to 3300ec51d0d3a269
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","getprop","ro.build.version.release"]

[AndroidDriver] Using device: 3300ec51d0d3a269

[ADB] Checking whether adb is present

[ADB] Using adb from /Users/itsqdtests/Library/Android/sdk/platform-tools/adb
[debug] [ADB] Setting device id to 3300ec51d0d3a269
[BaseDriver] Using local app '/Users/itsqdtests/Desktop/Payload/LaRedoutePreprod_7_2.apk'
[debug] [AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","wait-for-device"]

[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","echo","ping"]

[debug] [Logcat] Starting logcat capture

[debug] [AndroidDriver] Pushing settings apk to device...

[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","install","/Volumes/Appium/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/io.appium.settings/bin/settings_apk-debug.apk"]

[debug] [AndroidDriver] Pushing unlock helper app to device...

[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","install","/Volumes/Appium/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-unlock/bin/unlock_apk-debug.apk"]

[ADB] Getting device platform version

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","getprop","ro.build.version.release"]

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","dumpsys","window"]

[AndroidDriver] Screen already unlocked, doing nothing

[debug] [AndroidDriver] Parsing package and activity from app manifest

[ADB] Checking whether aapt is present
[ADB] Using aapt from /Users/itsqdtests/Library/Android/sdk/build-tools/23.0.3/aapt
[ADB] Extracting package and launch activity from manifest
[debug] [ADB] badging package: com.ocito.laredoute
[debug] [ADB] badging act: com.ocito.laredoute.ui.splashscreen.SplashScreenActivity
[debug] [AndroidDriver] Parsed package and activity are: com.ocito.laredoute/com.ocito.laredoute.ui.splashscreen.SplashScreenActivity
[debug] [ADB] Uninstalling com.ocito.laredoute

[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","am","force-stop","com.ocito.laredoute"]

[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","uninstall","com.ocito.laredoute"]

[ADB] App was not uninstalled, maybe it wasn't on device?

[AndroidDriver] Remote apk path is /data/local/tmp/f112cab33ade421a07fde26b9e5f042e.apk

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","ls","/data/local/tmp/f112cab33ade421a07fde26b9e5f042e.apk"]

[debug] [AndroidDriver] Checking if app is installed

[debug] [ADB] Getting install status for com.ocito.laredoute
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","getprop","ro.build.version.sdk"]

[debug] [ADB] Device API level: 23

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","pm","list","packages","-3","com.ocito.laredoute"]

[debug] [ADB] App is  not installed

[AndroidDriver] Apk is not yet installed
[AndroidDriver] installing apk from remote

[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","mkdir","-p","/data/local/tmp"]

[AndroidDriver] Clearing out any existing remote apks with the same hash

[debug] [AndroidDriver] Removing any old apks
[debug] [AndroidDriver] Except ["f112cab33ade421a07fde26b9e5f042e"]

[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","ls","/data/local/tmp/*.apk"]

[debug] [ADB] Uninstalling com.ocito.laredoute

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","am","force-stop","com.ocito.laredoute"]

[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","uninstall","com.ocito.laredoute"]

[ADB] App was not uninstalled, maybe it wasn't on device?

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","pm","install","-r","/data/local/tmp/f112cab33ade421a07fde26b9e5f042e.apk"]

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[debug] [AndroidDriver] Extracting strings from apk /Users/itsqdtests/Desktop/Payload/LaRedoutePreprod_7_2.apk null /var/folders/mj/47pk4ml54bb8t54rklsh81pw0000gn/T/com.ocito.laredoute

[debug] [ADB] Extracting strings for language: default
[debug] [ADB] Device API level: 23

[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","getprop","persist.sys.locale"]

[debug] [ADB] Current device property 'persist.sys.locale': pt-PT

[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [ADB] Reading strings from converted strings.json

[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","push","/var/folders/mj/47pk4ml54bb8t54rklsh81pw0000gn/T/com.ocito.laredoute/strings.json","/data/local/tmp"]

[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","forward","tcp:4724","tcp:4724"]
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","push","/Volumes/Appium/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-android-bootstrap/bootstrap/bin/AppiumBootstrap.jar","/data/local/tmp/"]

[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","ps","uiautomator"]

[ADB] No uiautomator process found to kill, continuing...

[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: -P, 5037, -s, 3300ec51d0d3a269, shell, uiautomator, runtest, AppiumBootstrap.jar, -c, io.appium.android.bootstrap.Bootstrap, -e, pkg, com.ocito.laredoute, -e, disableAndroidWatchers, false, -e, acceptSslCerts, false

[HTTP] <-- GET /wd/hub/status - - ms - - 

[debug] [UiAutomator] Moving to state 'online'

[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Loading json...

[AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[debug] [ADB] Device API level: 23
[debug] [ADB] Getting connected devices...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","am","start","-n","com.ocito.laredoute/com.ocito.laredoute.ui.splashscreen.SplashScreenActivity","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [ADB] Waiting for pkg: 'com.ocito.laredoute' and activity: 'com.ocito.laredoute.ui.splashscreen.SplashScreenActivity' to be focused

[debug] [ADB] Possible activities, to be checked: com.ocito.laredoute.ui.splashscreen.SplashScreenActivity, .ui.splashscreen.SplashScreenActivity, .com.ocito.laredoute.ui.splashscreen.SplashScreenActivity
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","dumpsys","window","windows"]

[debug] [ADB] Found package: 'com.ocito.laredoute' and activity: '.ui.splashscreen.SplashScreenActivity'

[AndroidDriver] Setting auto webview to context 'WEBVIEW_com.ocito.laredoute' with timeout 2000ms

[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","cat","/proc/net/unix"]

[debug] [AndroidDriver] Found webviews: []

[debug] [AndroidDriver] Available contexts: ["NATIVE_APP"]

[HTTP] <-- GET /wd/hub/status - - ms - - 

[debug] [AndroidDriver] Getting a list of available webviews

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","cat","/proc/net/unix"]

[debug] [AndroidDriver] Found webviews: []
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP"]

[debug] [AndroidDriver] Getting a list of available webviews

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","cat","/proc/net/unix"]

[debug] [AndroidDriver] Found webviews: []
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP"]

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [AndroidDriver] Getting a list of available webviews

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","cat","/proc/net/unix"]

[debug] [AndroidDriver] Found webviews: []
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP"]

[debug] [AndroidDriver] Shutting down Android driver

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","am","force-stop","com.ocito.laredoute"]

[HTTP] <-- GET /wd/hub/status - - ms - - 

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","am","force-stop","io.appium.unlock"]

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [ADB] Pressing the HOME button

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","input","keyevent",3]

[HTTP] <-- GET /wd/hub/status - - ms - - 

[debug] [ADB] Uninstalling com.ocito.laredoute

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/itsqdtests/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","3300ec51d0d3a269","shell","am","force-stop","com.ocito.laredoute"]

not sure if this is related to this issue (https://github.com/appium/appium/issues/5089) but any help would be great!

Thanks

**Comment by j0hnsa** [comment]
Hello,

Same Issue seems to be happening on iOS tests:

[debug] [iOS] Retrieving contexts and views

[debug] [iOS] Selecting by url: true (expected url: 'undefined')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json

[debug] [RemoteDebugger] Page element JSON: []
[debug] [iOS] No web frames found.
[iOS] Could not find any webviews yet, refreshing/retrying
[HTTP] <-- GET /wd/hub/status - - ms - - 

[debug] [iOS] Retrieving contexts and views

[debug] [iOS] Selecting by url: true (expected url: 'undefined')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json

[MJSONWP] Encountered internal error running command: Error: Could not navigate to webview; there are none!
    at IosDriver.spinHandles$ (lib/commands/context.js:478:13)
    at tryCatch (/Volumes/Appium/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Volumes/Appium/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Volumes/Appium/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Volumes/Appium/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Volumes/Appium/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Volumes/Appium/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Volumes/Appium/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[debug] [RemoteDebugger] Page element JSON: []
[debug] [iOS] No web frames found.
[HTTP] <-- POST /wd/hub/session 500 114204 ms - 183 
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 8 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 12 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 9 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 8 ms - 83 


Note: Not sure if this issue is related

**Comment by j0hnsa** [comment]
Now the output I'm getting is:
The test case failed to be executed. Could not start Selenium. org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not navigate to webview! Err: Cannot read property 'split' of undefined (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 28.34 seconds Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46' System info: host: 'risrvdev1', ip: '192.168.134.35', os.name: 'Windows 2003', os.arch: 'x86', os.version: '5.2', java.version: '1.7.0_80' Driver info: io.appium.java_client.ios.IOSDriver.

**Comment by bcivel** [comment]
Hello,
We can't do anything in Cerberus to solve this issue.
After a bit of investigation, I can advice to downgrade your appium version to 1.4.13, since the revision since 1.5.0 are still unstable.

**Comment by abourdon** [comment]
This issue has been resolved thanks to https://github.com/vertigo17/Cerberus/commit/da6302c1c4d80bdfdd89018657ec763b699259dd.

Regards,
Aurélien
