### ISSUE TITLE
Time to run a query far too long (sometimes)

### ISSUE THREAD

**Issue by MichaelWil** [vertigo17/Cerberus#874]
Hi,

A new tests was implemented included a query to bring a specific kind of article. Sometimes the time to run is normal and sometimes it can takes more than 1.000 sec .... 
http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=34747495 step 2 : 1970 sec
http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=34771901 step 2 : 1197 sec

I can say that the time to run the query in itself is normal (outside Cerberus).

So the first thing which is not normal is (of course) the time to run and the second is that no timeout are failing the test. Letting a test running for more than 30 min makes no sense.

Thanks

**Comment by vertigo17** [comment]
The time spent is on the execution of the SQL. You can see it on PRODUCT property calculation that took resp 32 and 19 minutes.
I change that as enhansment in order to introduce a timeout when executing external SQL.
timeout needs to be configurable by parameter at system level.

**Comment by vertigo17** [comment]
2 new parameters added for that purpose:
cerberus_propertyexternalsql_timeout
cerberus_actionexecutesqlupdate_timeout
both have 60 (seconds) as default value.
