### ISSUE TITLE
Appium / hidekeyboard doesnt work sometime

### ISSUE THREAD

**Issue by vitoo** [vertigo17/Cerberus#876]
Hi,
When using hidekeyboard i got this error : 

`{"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Soft keyboard not present, cannot hide keyboard)","origValue":"Soft keyboard not present, cannot hide keyboard"}`

Here is a solution [here ](http://stackoverflow.com/questions/35030794/soft-keyboard-not-present-cannot-hide-keyboard-appium-android?answertab=votes#tab-top)

Any other idea ? thanks 

version : Cerberus1.1.5

**Comment by bcivel** [comment]
Hello @vitoo 
We can try to implement what you propose but on top of that, we need to replicate the issue.

Could you tell us which  version of android API you are using? Which version of appium? Which device/emulator?

Thanks

**Comment by vitoo** [comment]
Hi Benoit,

Appium : 1.4.16.1
Android 6.0 - API level 23 (on Android virtual device)

` Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Soft keyboard not present, cannot hide keyboard)","origValue":"Soft keyboard not present, cannot hide keyboard"},"sessionId":"f6c95f5e-5e4a-484d-a7ea-20b584c19f99"}`

**Comment by abourdon** [comment]
Hi @vitoo,

Thanks for you report and the linked answer. So now, keyboard is already hidden if necessary.

Cheers,
Aurélien

**Comment by vitoo** [comment]
Hi @abourdon, i've fix this issue by adding a wait of 3000 ms just before the hideKeyboard action. 

Thanks

**Comment by abourdon** [comment]
@vitoo great if this workaround works for you. But be ware, this one is not sustainable and you need two actions to really do just one. As soon as the 1.1.6 version will be released you could use the `hideKeybord` action without any trick.

Cheers,
Aurélien

**Comment by abourdon** [comment]
Note the `click` action is now able to handle (x;y) coordinates. It could be used as workaround if the `hideKeyboard` action is not working.

See the #1088 for more details.

Aurélien
