### ISSUE TITLE
The 'type' action doesnt replace text input on android

### ISSUE THREAD

**Issue by vitoo** [vertigo17/Cerberus#878]
Hi,

The type action doesnt replace the text input on android, like it does on web apps.
Is it normal ?

Thank you

Cerberus Version : 1.1.5

**Comment by bcivel** [comment]
Hello,
No it's not normal.
Could you provide a bit of detail? Which android API version? Which Appium version?
Thanks

**Comment by vitoo** [comment]
Hi,

Appium : 1.4.16.1
Android 6.0 - API level 23 (on Android virtual device) 

In the appium log i've got  :  Got data from client: {"cmd":"action","action":"setText","params":{"text":"INNA","replace":false}}


Full log :
```
info: [debug] Pushing command to appium work queue: ["setText",{"text":"INNA","replace":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"setText","params":{"text":"INNA","replace":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: setText
info: [debug] [BOOTSTRAP] [debug] Using currently-focused element.
info: [debug] [BOOTSTRAP] [debug] Text not cleared. Assuming remainder is hint text.
info: [debug] [BOOTSTRAP] [debug] Sending plain text to element: INNA
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
```

**Comment by abourdon** [comment]
It works well against both a real and virtual device, from the latest Cerberus SNAPSHOT version. Please wait for the new version and try again.

From now, I close this one. Do not hesitate to reopen it if you will face to same problem again.
