### ISSUE TITLE
Test execution cannot find sub-data

### ISSUE THREAD

**Issue by ffazendeiro** [vertigo17/Cerberus#881]
When executing test using the data lib cerberus is not able to retrieve sub data and the test case stays with PE status:
![image](https://cloud.githubusercontent.com/assets/17747042/17302087/652c40c2-5812-11e6-82e8-0756e8fd145e.png)
Test data is correctly defined (test case is not using NOTINUSE feature).
Test case execution: http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=34362989

**Comment by gmoita** [comment]
And even with action result = NA, test case stays in PE status.

**Comment by vertigo17** [comment]
The screenshot you provided do not correspond to the issue.
Anyway, from the screenshot provided, it looks like you forgot the % around the variable.
It should be %ACCOUNT(PASSWORD)%

**Comment by ffazendeiro** [comment]
Hi,
Actually we don't use %% for action type and it works with the previous version:
![image](https://cloud.githubusercontent.com/assets/17747042/17434605/4aa3a99a-5b03-11e6-99b1-19a210b067c9.png)
![image](https://cloud.githubusercontent.com/assets/17747042/17434621/5b519040-5b03-11e6-9d2c-825a2395bdd8.png)

With this new version if we use %% the variable is not recognized:
![image](https://cloud.githubusercontent.com/assets/17747042/17434657/9199d66c-5b03-11e6-86b2-3698b07d11b3.png)
And test fails:
![image](https://cloud.githubusercontent.com/assets/17747042/17434666/a00fd926-5b03-11e6-83d3-4c2bc2ee7516.png)
Should we create a new varaible? something like:
![image](https://cloud.githubusercontent.com/assets/17747042/17434852/bbd28d42-5b04-11e6-8f4c-d0ff1d33035a.png)
In this case it will re-calculate the Data Lib (no problem if it is static but a major issue if it is from a dynamic query).

**Comment by vertigo17** [comment]
No this looks as a bug that I will check.
Can you provide the correct execution ID ?

**Comment by ffazendeiro** [comment]
Test ID for the current version: http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=35114547
Test ID For the new version: http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=34365413 
This test uses a step (3 -> http://192.168.134.17/Cerberus/TestCase.jsp?Load=Load&Test=MADIBA_LIB&TestCase=0001B#stepAnchor_1) to login into the site.
Please let me know if you need more information.

Just as a note and amending my previous comment, if we use "text" instead of "getFromData_Lib":
![image](https://cloud.githubusercontent.com/assets/17747042/17435885/a1fb4204-5b0b-11e6-8460-ad08df558fb3.png)
We can get a sub data from a data lib without it being recalculated.

**Comment by vertigo17** [comment]
@ffazendeiro it should be fixed now.
The initial usage was correct you can put ACCOUNT(PASSWORD)

NB : on future versions, the Property field of all actions will disappear and be replaced by a new field.
We will end up with 2 generic fields of every action Value1 and Value2.
On those 2 fields %PROP% or %PROP(SUBDATA)%, will have to be used in stead of PROP or PROP(SUBDATA). That will simplify the usage as in all cases, you will always use %TOTO% syntax (or %PROP(SUBDATA)%).

Property Field will move to another place called ConditionalValue1 with a new field attached to that will be ConditionalOperator. Those 2 field will allow us to execute an action only on certain condition (like if a Property exist on a given country OR a value in a list).

The only exception will be to force calculation of a property with calculateProperty action where Value1 will take the value of a Property (ie PROP).

But all that will be for a later release ;-)
