### ISSUE TITLE
Test stays pending when no data is available

### ISSUE THREAD

**Issue by ffazendeiro** [vertigo17/Cerberus#882]
Using the NOTINUSE feature and data lib to retreive data if there is no mora data available the action will return NA with the massage "retrieved but there are no more data available" which is correct but the execution stays pending:
![image](https://cloud.githubusercontent.com/assets/17747042/17302314/89119d10-5813-11e6-9db6-b238002578f0.png)
Test case execution: http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=34362989

**Comment by vertigo17** [comment]
In fact that was happening anytime a property getFromDataLib gets no result.
It should be fixed now.
Thanks for the issue.
