### ISSUE TITLE
Multiple test case/test case beta : the execution queue stops working

### ISSUE THREAD

**Issue by vitoo** [vertigo17/Cerberus#883]
Hi,

The execution queue always stops working a little before the middle of the queue when launching multiple executions with the Run test case beta.

Any idea on how to fix this ?
Screenshot : ![http://puu.sh/qowNk/f291b99acf.png](http://puu.sh/qowNk/f291b99acf.png)

Thank you

Cerberus 1.1.15

**Comment by abourdon** [comment]
Closed by previous commit
