### ISSUE TITLE
The save button is outside the boundaries of my screen

### ISSUE THREAD

**Issue by ageneauNOR** [vertigo17/Cerberus#886]
In TestData Lib, when I open the dialog to create, modify or edit the sub-data, I cannot click on the save button, it is outside of my screen's boundaries and there's no overflow.

![image](https://cloud.githubusercontent.com/assets/20062436/17508639/3aaf8e3a-5e16-11e6-98dd-581858714586.png)

Is it possible to adjust the position so that it fits in the screen?

Thank you

**Comment by vertigo17** [comment]
I was not able to reproduce but adjust the layout with the same config as the other screens.
Can you provide the 
1/ the browser you use. Loos like Firefox
2/ the resolution of the screen
3/ If you have the same problem on other modal in the same screen or any other screen

**Comment by ageneauNOR** [comment]
I am having this issue on chrome.

My screen resolution is 1920 1080.

It does not happen on other devices.

However I don't think my screen ratio is 16:9.

**Comment by vertigo17** [comment]
Thanks
What i meant is if you add the issue in other Cerberus screens such as application or environment screen ?
Are you able to pick the last version to confirm my fix is working ?

**Comment by vertigo17** [comment]
It should be fixed with last commit as this screen is now following the same standard as the other.
Please reopen is still the case.
