### ISSUE TITLE
First test is not executed in multiple test execution

### ISSUE THREAD

**Issue by vitoo** [vertigo17/Cerberus#896]
Hello,

In  Cerberus 1.1.5 - Run test case (beta), the first test case stay in NE. 
Here 0001A stay NE and the rest (0001B to 0022B) is executed.
It happens most of the time, but not every time.

![image](https://cloud.githubusercontent.com/assets/995694/17881788/597fc31e-6908-11e6-9a7e-20870d8d1b4d.png)

Have you ever encountered this problem ?

Thank you

**Comment by abourdon** [comment]
Related to #883 and fixed by 49416e7

**Comment by vitoo** [comment]
Looks like this issue happen again

![image](https://cloud.githubusercontent.com/assets/995694/20003532/3d9f472e-a287-11e6-85fd-db965620c2dc.png)

@abourdon @bcivel
