### ISSUE TITLE
"Run the same Test Case again" / Environment missing

### ISSUE THREAD

**Issue by pfoucray** [vertigo17/Cerberus#900]
Cerberus Version : 1.1.5-SNAPSHOT

Hi,

when launching TC execution with same parameters as previous (button bottom of page : Cerberus/ExecutionDetail.jsp?id_tc=) if environment isn't activ / available anymore, Cerberus will automaticaly chosse the 1st one in the dropdown menu, not alerting the user.

This can lead to mistake / misunderstads in test campaigns analysis. Warning environment has changed might be helpful.

Best regards,
PF

**Comment by bcivel** [comment]
@pfoucray ,
This feature is available on the new RunTest page. 
Thanks for the contribution
Benoit
