### ISSUE TITLE
Build Content filters/buttons not working

### ISSUE THREAD

**Issue by mbessa** [vertigo17/Cerberus#905]
Hello,

In CerberusQA (http://192.168.134.197/CerberusQA/BuildContent.jsp)
All the filters in Build content page aren't working. This applies to table filters and button filters.
![image](https://cloud.githubusercontent.com/assets/5825695/18095338/93ab41fa-6ece-11e6-83f6-c2768151d842.png)

![image](https://cloud.githubusercontent.com/assets/5825695/18095353/9d858898-6ece-11e6-84d7-e50e0d997151.png)

This issue compromise new revisions creations.

Cerberus Version : 1.1.6-SNAPSHOT

**Comment by bcivel** [comment]
fixed
