### ISSUE TITLE
Environment activation "[undefined]" text in displayed

### ISSUE THREAD

**Issue by mbessa** [vertigo17/Cerberus#906]
Hello,

When activating an environment with a new revision, in application column the text [undefined] is displayed for all applications:
(http://192.168.134.197/CerberusQA/Environment.jsp)
![image](https://cloud.githubusercontent.com/assets/5825695/18095787/f6995c10-6ecf-11e6-90d6-5d9a66e69342.png)

Cerberus Version : 1.1.6-SNAPSHOT

**Comment by bcivel** [comment]
fixed with the last commit
