### ISSUE TITLE
ifPropertyExists does not work with subdata

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#910]
Hi, 
test fails when C.Ope is ifPropertyExists and the C. Val is a subdata. 
Please take a look at the screenshot in Example: http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=35907700 
![subdataif](https://cloud.githubusercontent.com/assets/1914659/18180657/c9c54968-707f-11e6-89e0-0c3af468ecc1.jpg)

And this is the execution with 'allways': http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=35907779

Plase note that data is being imported this way and will have a huge impact in failing tests.

**Comment by vertigo17** [comment]
Yes this is normal.
ifPropertyExist require a property and nothing else. We should not put a subdata there.
I will add an update that clean au subdata on that field.
