### ISSUE TITLE
Strange behaviour of verify control when using the Exe RC

### ISSUE THREAD

**Issue by ffazendeiro** [vertigo17/Cerberus#912]
Although RC (to continue the execution is action PE) seems to be working properly (test execution is continuing and step result is OK and action is FA) some controls (verify) seem to be executed almost instantly.

For example (below) the verify execution took 481 ms so the result was KO (did not find the element) but the page was still loading (not from the first action but from action5). Meaning that if control waited just a little longer the control5-1 should be ok.
![image](https://cloud.githubusercontent.com/assets/17747042/18246024/a107d1d8-7360-11e6-8d61-f48992e08e52.png)
Test execution: http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=35912796 

This can be bypassed using a wait . If we put a wait (in this case for an element only present on the other page) the verify seems to work fine. Taking in this case 1.9 s and found the element.
![image](https://cloud.githubusercontent.com/assets/17747042/18246016/9771a72a-7360-11e6-9daf-188527f3aa13.png)
Test execution: http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=35912806 

Could this be due to the page always stays loading (between the two action 1 and 5) and the verify mistaken as the page being already loaded?
This can produce some false KO that needs to be taking into account when using Exe RC (a wait is necessary on the second action before any control).

**Comment by vertigo17** [comment]
Looks more like the verifyRegexInElement do not wait for the element before making the check.

**Comment by vertigo17** [comment]
As shared together, there are no issues but in fact what happened is that the control is on an element that is always displayed but only updated to the right value few seconds after the button is clicked.
Solution is to add a wait action on a field that appears only after the button is clicked in order to perform the control only after that wait.
