### ISSUE TITLE
force user agent with cerberus

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#915]
Hi,
is it possible to force the user agent in Cerberus? For example, run a test with a iphone behaviour? 
Thanks!

**Comment by bcivel** [comment]
Hello,
Yes, you can define a user agent in the robot configuration. (On Robot Page).
So, once defined, when you run test pointingthis robot, the user agent defined will be used.
 Thanks

**Comment by amarlot** [comment]
Hi Benoit,

We can't do it at Test Case level ? as it's only for a few tests.

Thanks,
Alex

**Comment by ruirpr** [comment]
Thanks Benoit, I was not aware of that. 
Can you give a example of how to configure a robot for iphone? 
Thanks!

**Comment by vertigo17** [comment]
this is here:
![selection_144](https://cloud.githubusercontent.com/assets/5342048/18361584/bd2607a0-7602-11e6-8db2-78d9b06a83ee.jpg)

We cannot do at testcase level (yet) but could be an option.
Then we would pick first the value at execution level (robot) if not defined we pick the value at testcase level and if not defined we leave it empty to pick the real one of the robot.

**Comment by bcivel** [comment]
Not really fan to put it at the testcase level because it is an execution parameter. In most of the cases, the testcase could be ran in many context, and many user agent.

Another way to simplify the management of this parameter could be reviewing the way battery/campain works.
for example: 
- adding parameters in test battery, 
- or allowing to link campain.

**Comment by amarlot** [comment]
Hi Benoit,

Just to be sure to explain the business need : 

We have some redirection set up between the mainsite and mobile site. If you arrive from Mainsite and have an iphone you need to be redirection to the mobile website with redirection : url has to be changed (without the .aspx).

My goad is to test : Redirection is working fine (mainsite > mobile) and .aspx was removed for some page (HP/PLP/BASKET).

Hope it's clear.
Alex

**Comment by vertigo17** [comment]
Issue is now fixed and user agent can be defined at testcase level:
![selection_146](https://cloud.githubusercontent.com/assets/5342048/18567142/241f7cb8-7b97-11e6-9db3-13cd931f8983.jpg)


Here is the rule:
If User Agent is defined at testcase level and empty at robot level, The execution will force it during the execution.
If User Agent is not defined at testcase level but defined at robot level, The execution will force it during the execution.
If user Agent is forced at the 2 level with the same value, Execution will force it during the execution.
If user Agent is forced at the 2 level with a different value, Execution will failed with the following error message:

_ReturnCodeDescription	User Agent has been specified at robot and TestCase level with different values. TestCase : 'titi' Robot : 'tutu'_
