### ISSUE TITLE
Run Test Case - Beta - Cerberus1.1.6-SNAPSHOT-921

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#919]
Hi,
i was checking the new Run Test Case page and found some problems. The tests start, open a lot of browser blank pages in the server and stay NE. Is this page suposed to work? Thanks!
![screen shot 2016-09-08 at 11 46 58-fullpage](https://cloud.githubusercontent.com/assets/1914659/18346835/5359f5c2-75ba-11e6-9c6c-3246d5b088fe.png)
![screen shot 2016-09-08 at 11 45 48-fullpage](https://cloud.githubusercontent.com/assets/1914659/18346834/535474f8-75ba-11e6-8d95-1efc21e6b4b0.png)
![blankpages](https://cloud.githubusercontent.com/assets/1914659/18346859/6afbefaa-75ba-11e6-8d27-567311055179.jpg)

**Comment by bcivel** [comment]
Hello @ruipr,

Yes, it works as expected. when you run multiple tests, you're redirected to the reportingExecutionByTag page with all your perimeter in NE (Non executed).

Then, Cerberus execute the tests you required taking into account the parameter "cerberus_execution_threadpool_size" to parallelize the execution.

Note that the way the engine work is beeing reviewed with the issue #914, but the user experience will be the same.

Thanks
Benoit
