### ISSUE TITLE
Can't communicate with iOS app

### ISSUE THREAD

**Issue by vitoo** [vertigo17/Cerberus#924]
Hello,

Cerberus Version : 1.1.5

I'm trying do use Appium iOS on the Xcode iPhone Simulator.
So i use the .app file (not .ipa)

I've tried many configurations without success.
Appium 1.5.3 / 1.5.2 / 1.4.13
On Appium 1.5.3, the inspector works fine with our App. The app start when i run cerberus test case but then i got some error, no action is triggered. 

My Robot Config : 
![image](https://cloud.githubusercontent.com/assets/995694/18633679/c097159a-7e7d-11e6-9300-c139dc92572d.png)

Error on Cerberus : 
> The test case failed to be executed. Could not start Selenium. org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: **Could not navigate to webview; there are none! (WARNING: The server did not provide any stacktrace information)**

I've tried with the [Ui-Catalog app](https://github.com/appium/ios-uicatalog) and with our App.

With our app this error is shown in Appium log : 

> Error: Could not connect to a valid app after 20 tries.

So i've got some questions : 

- Should we use simulator or real iPhone ?
- Which Mac Appium version should we use with Cerberus ? 
- Any idea to fix my issue ?

Many thanks !

**Comment by vitoo** [comment]
It works with this java script : https://gist.github.com/vitoo/0aa849ea4da57a001be06b4c59c9bc18

Not with Cerberus 1.1.5

**Comment by vitoo** [comment]
Fixed by setting capabilities : autoWebview : false 

Related to #873

**Comment by vitoo** [comment]
When running campaign the capability "autoWebview" is set to true and we got the appium error : 

> Error: Could not connect to a valid app after 20 tries.

**Comment by abourdon** [comment]
Hi @vitoo,

I don't understand well. You said it worked by setting `autoWebview` to `false`. And then by setting it to `true`, then you still have error.

So this issue can be closed isn't it? If you re-open it because of the autoWebview setting, I think it is more related to a lack of documentation (which will be fixed by the new Documentation page  (#913)) than a real bug.

If you agree with that, we can close this issue.

Regards,
Aurélien

**Comment by vitoo** [comment]
I've set iOS Robot capability `autoWebview `to `false`

When running single test, it works.

When running multiple test (beta runner) the `autowebview ` capability is overrided, appium receive it as `true` so it dont work

> Error: Could not connect to a valid app after 20 tries.

**Comment by abourdon** [comment]
Closed by previous commit
