### ISSUE TITLE
No border for every fields on Windows 10

### ISSUE THREAD

**Issue by NotoriousBig** [vertigo17/Cerberus#927]
Hello, 

There is no border for every fields in the TestCaseScript.jsp. 
I've the same result with Firefox 48.0.2, chrome Version 53.0.2785.116 m (64-bit) and IE 11

![test case - internet explorer](https://cloud.githubusercontent.com/assets/13114629/18700511/f450c2fe-7fd7-11e6-8de0-ad4e888abd4c.jpg)

![test case - mozilla firefox](https://cloud.githubusercontent.com/assets/13114629/18700542/1b5df826-7fd8-11e6-8007-648798fbfa62.jpg)

![run test - mozilla firefox](https://cloud.githubusercontent.com/assets/13114629/18700603/7b17d70a-7fd8-11e6-889c-81dca2610444.jpg)

regards
Seb

**Comment by bcivel** [comment]
Was due to bootstrap class that has been override on testcasescript page.
It has been corrected and you should now see the border like in the other page.
Thanks for your contribution
