### ISSUE TITLE
In case of many test cases, the beta RunTests page is slow to be loaded

### ISSUE THREAD

**Issue by abourdon** [vertigo17/Cerberus#929]
In case of many test cases, the beta RunTests page is slow to be loaded.

Maybe we could only load test cases that can be visible from the list, instead of loading everything. This could be done by giving a _number of results_ filter which is initialized to 10 for instance.

**Comment by vertigo17** [comment]
Good idea but then we need some kind of pagination with capability to keep selection when moving from 1 page to another.
Does not seem easy to implement. What could be done is to limit the value by a parameter and display a warning with 'parcial result' in case the nb of row reach that limit.
That issue should not exist when accessing the page from the 'run again the same execution' as it loads only the specific testcase in the list.

**Comment by vertigo17** [comment]
Following a conversation with Benoit the best is to add a field/combo in filter section to limit the load to 50 testcases by default. If users wants more and is ready to wait, he still can modify it.

**Comment by abourdon** [comment]
Let's develop it ;-)

**Comment by abourdon** [comment]
The beta Run Test Case page has already been developed to take query parameters into account:
- `test`
- `testcase`
- `environment`
- `country`
- `tag`
- `browser`

Then, the _run again the same execution_ feature is already operational.

**Comment by abourdon** [comment]
Following conversation with Benoit, we think is better to just develop this new filter as the others, and so by not keeping selection when filter value is changing. If user wants to keep the current selection, then he can add it to the execution queue, as he can do with actual filters.
