### ISSUE TITLE
java.lang.NullPointerException for run multiple tests when searching for test cases

### ISSUE THREAD

**Issue by ffazendeiro** [vertigo17/Cerberus#931]
On the page /RunTestsTriggerBatchExecution.js when searching for test to be exceuted on the Test Case filter the error java.lang.NullPointerException is showed after clicking on the Search button:
![image](https://cloud.githubusercontent.com/assets/17747042/18706320/7236c388-7fe9-11e6-9d19-bd9fcdf5a564.png)

**Comment by bcivel** [comment]
Hi @ffazendeiro ,
Sorry, I didn't seen you issue so I created a duplicated one #933 
It is fixed with the last commit
Thanks
Benoit
