### ISSUE TITLE
Calculate property is not overwriting the value

### ISSUE THREAD

**Issue by ffazendeiro** [vertigo17/Cerberus#937]
We use the action calculateProperty to get a vule but it is lso used during the test with another calculateProperty action to overwrite the initial value.

Example of a test failed with the new version:
http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=36866348
Example with previous cerberus version:
http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=36834416

Could you please confirm if there is an issue (property must indeed be overwriten when using calculateProperty) or is this a new behaviour?
In this case we must create new properties.
Thanks

**Comment by ffazendeiro** [comment]
Hi,
A control test case was create to better undertsand and check further non-regression
http://192.168.134.17/Cerberus/TestCase.jsp?Load=Load&Test=Cerberus&TestCase=9408A
Hopes it helps.
Thanks.

**Comment by bcivel** [comment]
Thanks for the testcase. It helped a lot.
It's corrected with my last commit
