### ISSUE TITLE
TC List Page / Edit Test Case Script button : Open in new tab

### ISSUE THREAD

**Issue by pfoucray** [vertigo17/Cerberus#938]
Cerberus Version : 1.1.6-SNAPSHOT-928

Hi,

just adding to back log a little feature we lost in newest versions of TC List page : The possibility to "middle click" or "right click" buttons like previous html<a> links.

Using Cerberus a lot, I constantly open many Test Cases pages from TC List page, and this feature was realy handy !

Thx a lot for all the new features anyways,
Best Regards,
PF

**Comment by bcivel** [comment]
fixed
