### ISSUE TITLE
New value %SYS_TESTCASE_NAME%

### ISSUE THREAD

**Issue by R-Loic** [vertigo17/Cerberus#941]
Hello,
It would be interesting to have a new value %SYS_TESTCASE_NAME% which returns test case number (screenshot).

![testcasenumber](https://cloud.githubusercontent.com/assets/18569182/18784573/4e40eb10-8193-11e6-90ca-03e5b2d905a9.JPG)

Thank you

Cerberus Version : 1.1.6-SNAPSHOT

**Comment by bcivel** [comment]
Hello @R-Loic 
I implemented %SYS_TESTCASE% that return the value of the testcase (in your case 1022C)
Thanks for the contribution
Benoit
