### ISSUE TITLE
PE status with OpenURL

### ISSUE THREAD

**Issue by R-Loic** [vertigo17/Cerberus#942]
Hello,

I have an issue with openURL.
The step keeps pending if the value of OpenURL does not exist.
In my example I forgot the % for TEMPLATIZE_1L 

![pending](https://cloud.githubusercontent.com/assets/18569182/18791317/89284dda-81b2-11e6-9eb1-fbc8c30387c8.JPG)

Cerberus Version : 1.1.6-SNAPSHOT

**Comment by bcivel** [comment]
Hello @R-Loic 
Corrected checking if value1 start with http://, https://, ftp://, ftps://
If not, then force http://value1.

In your case, if you forgot again to put %%, then Cerberus will try to open http://TEMPLATIZE_1L. So you will see where is the problem.
