### ISSUE TITLE
Groovy error

### ISSUE THREAD

**Issue by R-Loic** [vertigo17/Cerberus#943]
Hello,

Groovy returns this error whereas on webconsole the script is OK : 

Groovy evaluation error: java.util.concurrent.ExecutionException: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed: Script1.groovy: 1: expecting EOF, found 'else' @ line 1, column 56. ngth() == 9){"0"+ "168183321"}else{"1681 ^ 1 error 

Execution : 
http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=37063825

Thank you

Cerberus Version : 1.1.6-SNAPSHOT

**Comment by abourdon** [comment]
Hi,

The calculated expression was exactly the following:

`&#8203;​if("168183321".trim().length() == 9){"0"+ "168183321"}else{"168183321"}`

As you can see, there is an invisible character at the beginning. By removing it, then expression is well calculated.
You probably copied/pasted expression from a software which have added this invisible character.

Regards,
Aurélien
