### ISSUE TITLE
Calculate Property is always OK

### ISSUE THREAD

**Issue by ffazendeiro** [vertigo17/Cerberus#944]
With this new version of cerberus (Cerberus 1.1.6-SNAPSHOT and Database Version: 928) Calculate property is always returning OK (when no data available) and the test continues being executed.
http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=37104518 (executesql)
http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=37104548 (JS)
http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=37104552 (DataLibrary)
If the property is NA the calculate property action should be FA and the test should stop with FA and control message "_The test case could not be run because of missing testing data._".
Is it correct?

**Comment by vertigo17** [comment]
Correct Filipe,
I also seen that last WE.
I already fixed the NA in stead of FA on last version but not yet the Action that should return FA as well.
