### ISSUE TITLE
Unable to update Environment parameters

### ISSUE THREAD

**Issue by NotoriousBig** [vertigo17/Cerberus#946]
Hello, 

When I update an application parameter I got stuck in loading 👍 

![environment - mozilla firefox](https://cloud.githubusercontent.com/assets/13114629/18873080/015b7698-84be-11e6-9a29-5eaccf348550.jpg)

go on http://cerberus.siege.red/Cerberus/Environment.jsp
click the pencil button 'edit environment'
go on 'Application' tab (my system is empty there)
Click 'Add Application'
Select an application (I only have one application)
fill in 'host' => http://dev.servicespms.siege.red
fill in 'context root' => RedouteFrance/Order/Order/1.0
save and watch the infinite loading screen
 
Séb

**Comment by bcivel** [comment]
Due to variable1,2,3,4 that are not present in the modal

**Comment by bcivel** [comment]
fixed
