### ISSUE TITLE
[Enhancement]Display contents on fly over

### ISSUE THREAD

**Issue by chtixof** [vertigo17/Cerberus#949]
On tabular displays (example : Integration/Build Content), the display of the cells is often truncated (materialized by ...).

Could you implement a mouse-fly-over (hover) feature to display the full cells in a popup ?

Thanks.

**Comment by bcivel** [comment]
@chtixof 
fixed with my last commit. 
Full content is now displayed on mouseOver, only if text is wrapped

![Uploading Capture d’écran 2016-10-10 à 16.55.50.png…]()
