### ISSUE TITLE
Search engine doesn't work in the report analyse

### ISSUE THREAD

**Issue by MichaelWil** [vertigo17/Cerberus#951]
Hi,

When you go to a report execution (for example : http://192.168.134.17/Cerberus/ReportingExecutionByTag.jsp?Tag=WEB_THESEUS_ALL_PREPROD_2016092812), when you use the search engine you get a an internal server error.

Please find enclosed an example.
![2016-09-21_140758](https://cloud.githubusercontent.com/assets/11719918/18946966/74d48c44-8631-11e6-875a-142a2295c131.jpg)

Can you please take a look and fix ?

Thanks

**Comment by bcivel** [comment]
duplicated #934 
Corrected. fixed #934
