### ISSUE TITLE
Improve the behaviour of the PE put in the "Exe RC" function

### ISSUE THREAD

**Issue by MichaelWil** [vertigo17/Cerberus#953]
Hi,

THis function is working as the test carries on in every circonstances.

But in some specifics cases the next instruction is blocked because the loading of the page is not stopped.

For example the action like "type" or "click" can't be execute.

You've got an example here http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=37148634. 

Sometimes adding this instruction the test can carry on without any issue but it doesn't seem very normal that this case isn't directly handle by Cerberus without any specific additional instruction.

Can you please take a look and try adding this behaviour whether in the "PE" and/or in the "type" and "click" instruction, please ?

Thanks

**Comment by bcivel** [comment]
@MichaelWil : This should linked to the fact that the implicit wait and explicit wait on selenium are set with the same value. That mean Cerberus wait for the element to be present to click on it but without parsing the dom anymore.

@ffazendeiro
I set a couple of parameters to be able to tune it. Implicit wait is set to 0 by default, as it was before the last release, meaning that Cerberus will ask Selenium to parse the dom to find fields every some milliseconds until he find it or until the explicit timeout is reached.
Could you have a try, and reopen the issue if it happen again?

Thanks

linked to #765
