### ISSUE TITLE
unable to add the first step in new testcase (beta page)

### ISSUE THREAD

**Issue by NotoriousBig** [vertigo17/Cerberus#954]
Hello, 

Clicking on the big "+" button does nothing with a brand new testcase. 

![test case - mozilla firefox](https://cloud.githubusercontent.com/assets/13114629/18949022/c01fcdb4-8639-11e6-95d5-9808c71c04c3.jpg)

as a workarround I use the old page

Séb

**Comment by bcivel** [comment]
Hello @NotoriousBig 
In fact, it was a bit confusing as the button you tried to click was the one to add action, and not steps.
To create a step, you have to click on add step.
I hide the + button to avoid confusion in the future.
It appear only when a step is created.

<img width="1455" alt="capture d ecran 2016-10-10 a 21 50 51" src="https://cloud.githubusercontent.com/assets/5376184/19249043/a59302b0-8f33-11e6-92d9-e632f3960c04.png">
