### ISSUE TITLE
Fix the tests that stays in PE

### ISSUE THREAD

**Issue by MichaelWil** [vertigo17/Cerberus#956]
Hi,

It seems that since the last update the number of tests that stay in PE are increasing. This is all the more true that this issue is supposed to be fixed.

Some factual facts. I asked Filipe to provide me an extract, for 3 different days (26/09, 27/09 and 28/09) with all executions that wee required to being able to say a GO/NOGO. And here are the results 
* 26/09 : 35 tests finished in PE (list of the concerned execution below)
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37068215
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37075241
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37074652
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37075280
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37078447
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37071642
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37076347
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37074868
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37080369
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37072321
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37071599
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37067223
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37067257
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37067293
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37072361
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37067674
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37072567
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37068770
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37071963
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37069762
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37070330
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37068513
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37066701
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37066737
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37068317
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37065918
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37066741
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37071021
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37066730
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37071703
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37072400
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37074212
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37070257
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37074938
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37076074

 * 27/09 : 24 tests finished in PE (list of the concerned execution below)
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37106646
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37115507
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37107029
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37107502
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37108990
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37109648
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37109820
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37118005
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37113389
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37117068
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37109987
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37107127
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37117437
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37108674
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37112235
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37114794
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37120805
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37120518
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37120707
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37113355
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37109894
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37120819
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37120829
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37120829

* 28/09 : 22 tests finished in PE (list of the concerned execution below)
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37156443
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37150398
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37156520
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37151501
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37152720
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37160421
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37154884
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37157176
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37157183
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37160016
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37156637
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37151718
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37150807
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37157506
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37151298
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37151398
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37153211
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37155386
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37152009
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37161678
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37155555
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=37155463

Just one more information if the number of PE tests is decreasing this is linked to the fact than less and less tests were ran (from 5348 executions the 26 to 3892 the 28).

Thanks to take a look and to analyse to see what's happening.

**Comment by vertigo17** [comment]
@MichaelWil please analyse those PE and try to reproduce them in order to open relevante tickets.
That ticket is too generic and need analysis before beeing reopen.
