### ISSUE TITLE
Cannot send New chain notification email

### ISSUE THREAD

**Issue by ffazendeiro** [vertigo17/Cerberus#958]
Hi,
On the page environment page it is not possible to send a new chain notification email. The button create after clicking in "Preview Notification" is always disable (even with the environment is active):
![image](https://cloud.githubusercontent.com/assets/17747042/18994173/7d1755f6-871e-11e6-92ca-a83908e1b90a.png)
Could you please check?
Thanks.

**Comment by gmoita** [comment]
This is a regression.
