### ISSUE TITLE
Issue on Execute campaign script

### ISSUE THREAD

**Issue by vitoo** [vertigo17/Cerberus#959]
Cerberus Version : 1.1.6-928

Hello,

I got an error using the script to do crontab execution :

https://github.com/vertigo17/Cerberus/blob/master/tools/CampaignExecution/execute_campaign.pl

This url is generated : 

`http://dcerbpoc01.fral.labo:18080/Cerberus/GetCampaignExecutionsCommand?&campaign=2&campaignname=CED_Full&environment=&on=20&robot=robot_firefox&screenshot=1&tag=1003_CED_Full&timeout=150000`

To get the command URL : 

`http://10.130.114.156:18080/Cerberus//RunTestCase?&&Test=CED&TestCase=0001A&Browser=firefox&Country=RX&Environment=INTE&ss_ip=10.130.114.205&ss_p=4444&Tag=1003_CED_Full&screenshot=1
`

When the command URL is loaded we obtain this error : 

`2016-10-03 08:47:46 - 0 [CED|0001A|RX|INTE] : '' - 69 outputformat parameter value '' is not valid.`

It worked before on Cerberus 1.1.5

Any idea to fix this ?

Thank you,

Victorien

**Comment by vitoo** [comment]
Fixed by adding &outputformat=compact

**Comment by bcivel** [comment]
I @vitoo, You've got it :-)
I added outputformat in the script.

**Comment by bcivel** [comment]
fixed
