### ISSUE TITLE
Issue with database in cerberus

### ISSUE THREAD

**Issue by vitoo** [vertigo17/Cerberus#960]
Cerberus Version : 1.1.6

## Issue

Initial issue, after updating from 1.1.5 to 1.1.6 : 

`You cannot perform executeSqlUpdate action on a JDBC ressource using Cerberus connection pool. Please create new connection with dedicated rights.`

![image](https://cloud.githubusercontent.com/assets/995694/19042016/ac738a72-898a-11e6-91a1-9703dba39327.png)

So we try to add a new Database and we got a Select field instead of an input field : 

![image](https://cloud.githubusercontent.com/assets/995694/19041989/96ade732-898a-11e6-9349-ae564dd899f7.png)

So how to add a database in Cerberus ? Is there any workarround to use in the cerberus mysql database ?

Thanks

Victorien

**Comment by vertigo17** [comment]
Database entries are managed in public invariant: PROPERTYDATABASE

Go to Administration / invariants menu entry
Select 'Public' tab
Click on 'Create Invariant'
select 'PROPERTYDATABASE' in IdName
input the name of your database in value.
Click on Save button.

--> The database will then be available in the environment combo.
