### ISSUE TITLE
Can't add new properties in Edit TestCaseBeta

### ISSUE THREAD

**Issue by vitoo** [vertigo17/Cerberus#962]
Cerberus Version : 1.1.6-928
## Issue

When adding a new property in Edit test case beta, the save button stay disabled : 
![image](https://cloud.githubusercontent.com/assets/995694/19068856/9771e73c-8a24-11e6-8039-92c8ce5e066a.png)

Thanks for your help

**Comment by bcivel** [comment]
Hi @vitoo,
For the moment, button is disabled because it is not implemented yet. To save the properties, you have to close the modal, and save your testcase.
I close this issue because it is part of another issue #575 
Thanks for your contribution
