### ISSUE TITLE
RunTest BETA. Issue when reexecute test from different system.

### ISSUE THREAD

**Issue by vertigo17** [vertigo17/Cerberus#963]
Cerberus Version : 1.1.7-SNAPSHOT-936

When opening the run page from the link inside the execution detail page :
![selection_151](https://cloud.githubusercontent.com/assets/5342048/19104676/3bdb6cc6-8ade-11e6-88bb-5b9d0519a97c.jpg)
The testcase list do not load in case the system of the test case is not the same as the system of the screen header.
![selection_152](https://cloud.githubusercontent.com/assets/5342048/19104715/617964ba-8ade-11e6-8034-e74d273ca4a9.jpg)

On top of that, even if the page load  the test case is not selected in case the value selected is not in the 1st 50 row loaded:
You can reproduce with:
http://192.168.134.197/CerberusQA/RunTests1.jsp?test=Cerberus&testcase=9630A&country=RX&environment=PROD&browser=firefox&tag=

I suggest that when calling with test and testcase parameter feeded, we force the loading of the list of test case with the single value selected.
In case the user wants to select another test, he can hit the search button in order to reload the full list.
That will speedup the loading of the page when just rerunning the same testcase + avoid the system compatibility issue.

**Comment by vertigo17** [comment]
Both subjects still not working.

**Comment by Foudro** [comment]
1st subject must be fixed now,

for the second one, if it doesn't work it is because the old page setted a brocken object in your localStorage, empty your localstorage and this must mork better.

**Comment by vertigo17** [comment]
Working fine.
Thanks.
