### ISSUE TITLE
Pagination error : empty list

### ISSUE THREAD

**Issue by mviaene** [vertigo17/Cerberus#964]
Hello,

There is a problem with the last visited pagination page.

Reproduction :
- Visit a test case list page with multiple pagination pages
- Go to the last pagination page
- Visit an other test case list page with less pagination than the first one
==> You're list is empty

Workaround :
Clic on the "First" pagination button

Cerberus Version : 1.1.3.1

Best regards,
Maxime

**Comment by bcivel** [comment]
Hello Maxime,
This issue has been corrected the release 1.1.6.
Do you have the possibility to upgrade to the latest version?
Benoit

**Comment by mviaene** [comment]
Thanks for you're answer.

So, I'll upgrade as soon as I can.

Maxime
