### ISSUE TITLE
PE status with wrong action wait

### ISSUE THREAD

**Issue by R-Loic** [vertigo17/Cerberus#965]
Hello,

![wait](https://cloud.githubusercontent.com/assets/18569182/19185890/e2c4179e-8c83-11e6-86d0-995fcfc882d8.JPG)

In my example, I forgot to create propertie %WAIT%, Cerberus doesn't detect the wrong value %WAIT% (NotANumber) and keeps pending until the timeout defined.

Cerberus Version : 1.1.6-SNAPSHOT

**Comment by vertigo17** [comment]
@R-Loic, this is a normal behaviour.

If WAIT Property has not been defined, this is a normal behaviour.
I suppose the application tested is GUI/APK/IPA so Cerberus will interpret the %WAIT% as being the element to wait ?
If application tested is a different kind, Cerberus should wait the default time to wait (cerberus_action_wait_default parameter) in case the value entered is not integer.

Please confirm that the resulting status is not PE but FA. If PE, this is still a bug.

NB : The reason behind this behaviour is to allow having % in html field name or any action/control/property values after decode.  (there could be some SQL where % needs to stay unchanged)
