### ISSUE TITLE
[Appium] press Android back button ? 

### ISSUE THREAD

**Issue by vitoo** [vertigo17/Cerberus#966]
Hello,

I need to press device back button in a android Apps that doesnt show any menu or back button inside the frame App. 

In cerberus, how can we do the : 

> driver.pressKeyCode(AndroidKeyCode.BACK);

Looks like its not yet implemented : https://github.com/vertigo17/Cerberus/blob/633eb55c61293be126d4317d777e303dd9a00153/source/src/main/java/org/cerberus/service/appium/impl/AndroidAppiumService.java#L98

i don't know if we can implement this on iOS too.

Thanks for your help,

Victorien

**Comment by bcivel** [comment]
Hello Victorien,

For sure we can implement that feature as it make sense. Or maybe you can have a try to implement it a do a pull request if you want...You're welcome :-)

I propose that we do it only for Android as the same button doesn't exists on iOS.

So, we let you to implement that feature, as I'm sure you're interested in development. But please tell me if not, or if you're too busy, I'll implement it asap.

Thanks
Benoit

**Comment by vitoo** [comment]
Yes i'll try to do the pull request today :)
