### ISSUE TITLE
Appium Bug with last 1.1.7 version

### ISSUE THREAD

**Issue by vitoo** [vertigo17/Cerberus#972]
Hi,

After updating to the last 1.1.7 version, there is a bug with appium/android execution.
When an element is not found, appium keep searching this element in an infinite loop instead of using the timeout. 
And it does crash the glassfish server 

Hope you can fix it

Thank you

Victorien

**Comment by bcivel** [comment]
Hello @vitoo 
It's fixed now. Thanks for your contribution
Benoit
