### ISSUE TITLE
display Calculate Property value

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#976]
Hi, 
is it possible to show the calculateproperty result instead of the name? Thanks

![image](https://cloud.githubusercontent.com/assets/1914659/19472118/d76b12d8-951d-11e6-9b4e-65e5a60c9686.png)

**Comment by vertigo17** [comment]
@ruirpr, I will put the result value in return message and not in value1Init that contain the value of calculateProperty before the decode neither Value1 that is the property name really used after the decode to calculate the property.
That will looks like that :
![selection_153](https://cloud.githubusercontent.com/assets/5342048/19500174/1a7334d4-959b-11e6-8505-501c91760733.jpg)
